### ISSUE TITLE
@NotNull instead of @GraphQLNonNull

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [leangen/graphql-spqr#102]
Hi there!

Would be possible to allow `graphql-spqr` to work with `@NotNull` the same it works with `@GraphQLNonNull`? It would improve code readability, increase code compatibility with 3rd party validation tools, and would reduce code verbosity.

We have a lot of not null on our graphql/service methods, so this would help a lot.

Best regards,
Rafael Pacheco.

**Comment by rafaelrenanpacheco** [comment]
I just tested with `@NotNull` and it works as expected :sweat_smile:

**Comment by kaqqao** [comment]
Yup, it does :) Both `@NotNull` and `@NonNull` work, and so do the JetBrains annotations.

**Comment by josemduarte** [comment]
In case this is useful for anyone: `@NotNull` annotation works only with javax.validation > 2.0.0. 

With javax.validation 1.1.0 the `@NotNull` annotation is not picked up by spqr.

A test demonstrating the issue: https://github.com/josemduarte/graphql-spqr/commit/9a0ddb20729aee78c3b17ff03d8f1eab3d9fad56

**Comment by kaqqao** [comment]
@josemduarte This is to be expected... In  javax.validation 1.x, `@NotNull` can not be applied to type (it doesn't have `ElementType.TYPE_USE` as target), while in javax.validation 2.x it does.

What this means is that in your example the annotation is being applied to the method, not the return type of the method. And SPQR does not (and should not) consider the method annotations in this context.

**Comment by kaqqao** [comment]
Yup, I see how this can easily lead to confusion...

There are ways to still take method annotations into account, with some customization, but if upgrading javax.validation is an option, I'd still go for that.
