### ISSUE TITLE
Query generating param names as arg0, arg1 ...

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [leangen/graphql-spqr#103]
Hi there!

I have the following method in a service:

```java
@GraphQLQuery(name = "usuarioPapeis")
public Page<UsuarioPapel> getUsuarioPapeis(@NotNull Integer page,
                                           @NotNull Integer size) {
    return usuarioPapelRepository.findAll(PageRequest.of(page, size));
}
```

The generated graphql schema for this method expects the param names to be **arg0** and **arg1** instead of **page** and **size**. In order to generate the page and size param names I have to add the `@GraphQLArgument(name = "...")` annotation for each parameter, resulting in a very verbose service.

Is it possible to generate the graphql schema using the parameter name without using the annotation, or is it a java limitation?

Best regards,
Rafael Pacheco.

**Comment by kaqqao** [comment]
Yup, it's possible, you just need to tell the compiler to keep the parameter names by adding the `-parameters` flag.
In Maven you can pass with e.g.:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.7.0</version>
    <configuration>
        <compilerArgs>
            <arg>-parameters</arg>
        </compilerArgs>
        <source>1.8</source>
        <target>1.8</target>
    </configuration>
</plugin>
```

You'll might also want to set the same in your IDE. For IntelliJ, add `-parameters` under `Build, Execution, Deployment -> Compiler -> Java Compiler -> Additional command line parameters`.

**Comment by rafaelrenanpacheco** [comment]
Thanks for the fast response! Using maven-compiler-plugin solved the problem at the `mvn` level, and the `Additional command line parameters` solved at the IntelliJ level.

Btw, maven-compiler-plugin has now a dedicated configuration to set the _parameters_ flag:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.7.0</version>
    <configuration>
        <parameters>true</parameters>
    </configuration>
</plugin>
```

About IntelliJ, there is an [open issue](https://youtrack.jetbrains.com/issue/IDEA-143742) asking IntelliJ to support maven-compiler-plugin configuration.

Best regards,
Rafael Pacheco.

**Comment by kaqqao** [comment]
Ah, nice tips! Thanks :)
