### ISSUE TITLE
Question: How to handle polymorphysim

### ISSUE THREAD

**Issue by TinusJ** [leangen/graphql-spqr#105]
Hi, previously i asked about an issue i had, the problem seemed to be how i was handling inheritance.

How can i fix the following issue.

Entity 

```
public class Event extends BaseEntity{
 private String eventName;

// Getters and setters
}
```
Base Entity

```
public abstract class BaseEntity extends BaseEntityFunction implements Comparable, Serializable{
   @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

// Getters and setters 
}
```

Then my query 
`{findById(id:1){eventName}}`

Service

` @GraphQLQuery(name = "findById")
    public Event  getById(@GraphQLArgument(name = "id") Integer id) {
        return null;
    }`

GraphQL init

`            EventService eventService = new EventService();
            GraphQLSchema schema = new GraphQLSchemaGenerator()
                    .withOperationsFromSingleton(eventService)
                    .generate();
            GraphQL graphQL = GraphQL.newGraphQL(schema).build();

            ExecutionResult result = graphQL.execute(query);`

Error im getting

`Error The type of member "getClassName" belonging to io.bone.SpecialView is missing generic type parameters and can not be mapped. For details and possible solutions see https://github.com/leangen/graphql-spqr/wiki/Errors#ambiguous-member-type
[Ljava.lang.StackTraceElement;@64b2142d`

This happens to all the Entities, i looked at the possible solutions but cant seem to get it right

**Comment by TinusJ** [comment]
No I have not yet, Still struggling with the abstract part. I closed this due to several abstract issue closed, so will try that first. 

Currently i have this 
`     ResolverBuilder filteringBuilder = new AnnotatedResolverBuilder().withFilters( //add a filter
                    m -> (!(m instanceof Method) || !((Method) m).isBridge()) && !m.isSynthetic());

            GraphQLSchema schema = new GraphQLSchemaGenerator()
                    .withOperationsFromSingleton(eventFacade, TypeFactory.innerClass(EventFacade.class, AbstractFacade.class), filteringBuilder)
                    .withBasePackages(basePackages)
                    .generate();
            GraphQL graphQL = GraphQL.newGraphQL(schema).build();`

But im not sure if im doing it correctly

**Comment by kaqqao** [comment]
Recent versions of SPQR (you're on 0.9.7, right?) already correctly filter out the bridge and synthetic methods, so you don't need to customize that.
As for the `EventFacade`, does it have a generic type (`EventFacade<T>`)? If not, you don't need the `TypeFactory` stuff. If it is, you must provide the full generic type, e.g.

```java
.withOperationsFromSingleton(eventFacade, new TypeToken<EventFacade<Something>>(){}.getType())
```
This is you know the generic type (`Something` in my example). Only if that's dynamic, you need the `TypeFactory`:
```java
.withOperationsFromSingleton(eventFacade, TypeFactory.parameterizedClass(EventFacade.class, dynamicClass))
```

`TypeFactory#innerClass` is for dynamically producing types representing inner classes, it's highly unlikely you need that.

If you're still having issues, post what your `EventFacade` and `AbstractFacade` (and whatever else is relevant) look like.

**Comment by kaqqao** [comment]
The error you quoted above is about the `getClassName` method from `SpecialView`. Where is that coming from and what does it look like?

What you've shown up to now is perfectly vanilla and doesn't require any special setup. You're on v0.9.7, right?

**Comment by TinusJ** [comment]
I am on 0.9.7 The error is one of the other entities similar to Event

**Comment by TinusJ** [comment]
```
Error The type of member "getClassName" belonging to za.co.picksmart.entity.bone.Event is missing generic type parameters and can not be mapped. For details and possible solutions see https://github.com/leangen/graphql-spqr/wiki/Errors#ambiguous-member-type
[Ljava.lang.StackTraceElement;@62714c8b
```

**Comment by kaqqao** [comment]
As I said, this setup is the most basic one and whatever makes it special is outside of what you've shown so far... Without knowing exactly what the types look like, it is simply impossible for me to answer.

The only way I'd be able to help you is if you could provide a minimal example demonstrating the issue. Maybe create a small throw-away project on GitHub that reproduces the issue, or something like that?

**Comment by kaqqao** [comment]
I've just noticed that in your examples you sometimes register `eventService` and sometimes `eventFacade` in `withOperationsFromSingleton`.
Which one contains the query method? Especially in the last example, you register `eventFacade` but query for the `event` method which is on the `EventService`. If this is not just a typo, it is no wonder the query is not found. It indeed doesn't exist on the registered (`EventFacade`) bean, at least according to your examples.

Also, the query `{ event (id: 1) }` because it is missing a sub-selection, e.g.
```graphql
{
  event (id: 1) {
      id
  }
}
```

I made a quick test that replicates your setup as closely as I could recreate it from your samples: https://github.com/kaqqao/tinusj/blob/master/src/main/java/kaqqao/spqr/sample/GraphQLTest.java
It works just fine. I suspect that apart from the errors above, you have a method with an ambiguous generic return type (`getClassName `). If the generic type is not possible to detect statically, e.g. because it is an unconstrained type variable or a wildcard, you either have to filter that method out and not map it to GraphQL at all, or map the generic type as `Object` using `schemaGenerator.withTypeTransformer(new DefaultTypeTransformer(true, true))` .

**Comment by TinusJ** [comment]
Thanks for the example, appreciate it.

Im only using the EventFacade sorry for the confusion. It contains the business code and the jpa query.

Still got the same issue. Will look further into it today using the example. 

Just to recap this is what the EventFacade looks like 
```

@Stateless
public class EventFacade extends AbstractFacade<Event> {

     @GraphQLQuery(name = "event")
    public Event findById(@GraphQLArgument(name = "id") Long id) {
// JPA Query 
    }

}
```

**Comment by TinusJ** [comment]
@kaqqao When i debug my facade looks like this in the servlet

![image](https://user-images.githubusercontent.com/16685359/39781928-dc500e22-5310-11e8-8bed-cfaa6b7f2044.png)

I believe this is where the issue is, just not sure how to fix it.

**Comment by kaqqao** [comment]
Hm, could be that the type somehow gets mangled by the generated proxy...
Try registering it with an explicit type:

```java
.withOperationsFromSingleton(eventFacade, new TypeToken<AbstractFacade<Event>>(){}.getType())
```

**Comment by TinusJ** [comment]
Ok so i tried it and it still gives the same. This is what my servlet looks like.

`
@WebServlet(value = "/bql")
public class GraphQLServlet extends HttpServlet {

    private static final Logger LOG = LoggerFactory.getLogger(GraphQLServlet.class);
    private static final String[] basePackages = new String[]{"za.co.picksmart.entity"};

    @EJB
    private EventFacade eventFacade;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        ServletOutputStream sout = response.getOutputStream();
        response.setContentType("text/plain;charset=UTF-8");
        try {
//            String query = "{ event (id: 1) { id }}";//request.getParameter("q");

            GraphQLSchema schema = new GraphQLSchemaGenerator()
                    .withBasePackages(basePackages)
                    .withOperationsFromSingleton(eventFacade,new TypeToken<AbstractFacade<Event>>(){}.getType())
                    .generate();

            GraphQL graphQL = GraphQL.newGraphQL(schema).build();

            ExecutionResult result = graphQL.execute("{ event (id: 1) {id}}");

            sout.print(result.getData().toString());
            response.setStatus(200);
        } catch (Exception e) {
            sout.println("Error " + e.getMessage());
            sout.println(e.getStackTrace().toString());

            response.setStatus(400);
        }

    }`

**Comment by TinusJ** [comment]
Closing this, found the culprit

```
    GraphQLSchema schema = new GraphQLSchemaGenerator()
                .withBasePackages(basePackages)
                .withTypeTransformer(new DefaultTypeTransformer(true, true))  // 1
                .withOperationsFromSingleton(eventWrapper) // 2
                .generate();
```

I switched this when i tested it first. 1 with 2 

Thanks for an awesome lib.
