### ISSUE TITLE
How can I know the fields in the query body?

### ISSUE THREAD

**Issue by cwang92** [leangen/graphql-spqr#109]
I hava a query like this:
```
@GraphQLQuery(name = "m_ShipmentHeader")
  PagedElements<ShipmentLogicalRecord> getShipmentHeader(
      @GraphQLArgument(name = "filterArgs") Operator<ShipmentFilterArgs> filterArgs,
      @GraphQLArgument(name = "pagingArgs") ShipmentPagingArgs pagingArgs);
```
When I search 
```
{
    m_ShipmentHeader(filterArgs: {...}, pagingArgs: {...}) {
      elements {
        d_TrackingId
        d_lateness
      }
    }
}
```

Is that a way in my code I can know what are the fields inside the elements? I.E, is that possible I could have a List or Set that contains{d_TrackingId, d_lateness} in this case?

**Comment by kaqqao** [comment]
`DataFetchingEnvironment` provides you this info via `DataFetchingEnvironment#getSelectionSet`. You can obtain `DataFetchingEnvironment` via `@GraphQLEnvironment ResolutionEnvironment env`:
```java
@GraphQLQuery(name = "m_ShipmentHeader")
PagedElements<ShipmentLogicalRecord> getShipmentHeader(
               Operator<ShipmentFilterArgs> filterArgs,
               ShipmentPagingArgs pagingArgs,
               @GraphQLEnvironment ResolutionEnvironment env) {
    
    DataFetchingFieldSelectionSet selectionSet = env.dataFetchingEnvironment.getSelectionSet().get();
    Map<String, List<Field>> fieldsByName = selectionSet.get(); //contains d_TrackingId and d_lateness
}
```

If it's really just the field names you need, there's a shortcut: `@GraphQLEnvironment Set<String> subSelectionFieldNames`.

Btw, you don't need `@GraphQLArgument` everywhere. Just configure the compiler and IDE to preserve param names as described [here](https://github.com/leangen/graphql-spqr/issues/103).
