### ISSUE TITLE
JacksonValueMapperFactory constructor is now private

### ISSUE THREAD

**Issue by miguelocarvajal** [leangen/graphql-spqr#115]
Hello!

I was using spqr version 0.9.5 and when upgrading to version 0.9.7 I notice that the constructor for JacksonValueMapperFactory is now private:

`private JacksonValueMapperFactory(ObjectMapper prototype, TypeInfoGenerator typeInfoGenerator, Configurer configurer)`

Was this done for a particular reason? We can't even pass a custom ObjectMapper (for Spring auto wiring) since it is private.

Thanks for the help!

**Comment by kaqqao** [comment]
Ah, it just got turned into a builder as it was growing large. You still have access to all the customizations, don't worry :)

E.g. to use an existing `ObjectMapper`:
```java
JacksonValueMapperFactory.builder()
  .withPrototype(objectMapper)
  .build();
```

**Comment by miguelocarvajal** [comment]
De madre! I should've caught that. Sorry for the noise!
