### ISSUE TITLE
Question: Introspection queries blocking. 

### ISSUE THREAD

**Issue by thelesteanu** [leangen/graphql-spqr#118]
Is there a way in SPQR to block all introspection queries?

**Comment by kaqqao** [comment]
This is provided by graphql-java. You can use `NoIntrospectionGraphqlFieldVisibility` as your `GraphqlFieldVisibility` when configuring the schema.
If you want this set globally, for everyone:

```java
generator.withSchemaProcessors(
  (schemaBuilder, buildContext) -> schemaBuilder.fieldVisibility(new NoIntrospectionGraphqlFieldVisibility()))
```

I'll also add a direct way: `generator.withFieldVisibility(...)` but it doesn't exist now.

If you want to transform an existing schema on per-request basis:

```java
schema.transform(builder -> builder.fieldVisibility(new NoIntrospectionGraphqlFieldVisibility()))
```

**Comment by thelesteanu** [comment]
Thanks a lot, Bojan! I really appreciate it 😃 Keep up the good work!
