### ISSUE TITLE
How to validate fields of @GraphQLArgument ? 

### ISSUE THREAD

**Issue by ferguardiola** [leangen/graphql-spqr#120]
Hello, 

This is  fantastic library but is not well documented... 

I'd like ot know if it possible to validate fields af a type used as GrapQLArgument..

I have the service AuthService with the method

```
@GraphQLMutation(name = "create")
    public User createUser(@GraphQLArgument(name = "userRequest") UserRequest userRequest) throws ServiceException {
        User user = new User();
        user = mapUser(user, userRequest);
        return userDAO.store(user);
    }

```
Then the Class UserRequest
```

public class UserRequest {

    @GraphQLQuery(name = "name")
    @NotEmpty(groups = CreateChecks.class)
    private String name;

    @GraphQLQuery(name = "surname")
    @NotEmpty(groups = CreateChecks.class)
    private String surname;


```
I sent the JSON
```

{
  "query": "mutation ($userRequest : UserRequestInput!) { create(userRequest: $userRequest) { name } } ",
  "params": {
  	"userRequest" : 
    	{ "name" : "Name" } 
   }
}
```

I'd like that if change 
```

    @GraphQLQuery(name = "surname")
    @GraphQLNonNuLL 
    @NotEmpty(groups = CreateChecks.class)
    private String surname;
```

Then the method createUser was not called as the suname is missing and returns an error..  Is it possible do something like that ?? How ?? I miss documentation on this things

Is it possibkle to create validationGroups as in REST with GraphQL ?? 

Thank you!

**Comment by ferguardiola** [comment]
Ok

I see that with 

    public void setSurname(@GraphQLNonNull String surname) {
        this.surname = surname;
    }

I can do that.. 

Is any possibility to user other kind of validation @NotEmpty ? or user a cusotm validator ? How cna be done ?

**Comment by kaqqao** [comment]
Bean Validation rules, as specified by [JSR 380]()https://beanvalidation.org/2.0/ (and JSR 303 before that), are normally triggered by the (web) framework.
I think you can make Spring trigger them as on any managed bean, so it _might_ be possible to use them in that fashion with SPQR. If you're not using Spring or a similar injection framework, the only way to trigger would be from SPQR itself, which is currently not possible, but there's [a feature request](https://github.com/leangen/graphql-spqr/issues/62) for that, which i plan to tackle after 1.0 release (in the following couple of months).

You could also try implementing a `FieldValidation` (offered by graphql-java directly), as exemplified [here](https://github.com/graphql-java/graphql-java/blob/2f8f3de1d722ec0128b960c5e565405057fa76ff/src/test/groovy/readme/InstrumentationExamples.java#L161). If this satisfies your needs, it's a safe way to do validation.

Note that `FieldValidation` gets access to `GraphQLFieldDefinition`, which in SPQR is an instance of `MappedGraphQLFieldDefinition` which gives access to the underlying method, which can then be used to get the annotations. BUT, this is an internal API that is going to change very very soon, into a public and more usable form. So, for the moment, I recommend staying away from that specific approach.

**Comment by ferguardiola** [comment]
Thank you for so fast answer. 

I'm using DropWizard with Guice (Guicey) https://github.com/xvik/dropwizard-guicey

I've been searching and exists a guice-validator. So it can be used https://github.com/xvik/guice-validator

**Comment by kaqqao** [comment]
This looks like it could do what you need. Please post back how it goes, I'm curious to know if it's a viable option.

**Comment by ferguardiola** [comment]
Yes it works! 

 Install a ValidationModule in GUICE, then annotated the services with @ValidateOnExecution and you can use any validation on methods (including validation groups, custom validation, etc..)

public User createUser(@GraphQLArgument(name = "userRequest") @Valid UserRequest userRequest) throws ServiceException {

public class UserRequest {

    @NotBlank(groups = CreateChecks.class, message = "Name must be not empty")
    private String name;

**Comment by kaqqao** [comment]
Cool! Thanks for posting back.
I'll remember it as a viable solution for other users.

**Comment by JohannesFluegel** [comment]
If you use Spring Framework, you can write:
```
@Entity
public class MyEntity {
  @NotBlank
  @GraphQLQuery(description = "The description")
  private String myField
```

```
@Service
@Transactional
@Validated
public class MyService {
  @GraphQLMutation(name = "createEntity")
  public MyEntity createEntity(@GraphQLArgument(name = "entity") 
    @Valid MyEntity entity) {
      ...
```
If you try to create the entity with
```
mutation {
  createEntity(entity: {
    myField: ""
  }) {
    id
  }
}
```
you will get an error message like
```
{
  "data": {
    "createEntity": null
  },
  "errors": [
    {
      "message": "Exception while fetching data (/createEntity) : 
         createEntity.entity.myField: may not be empty",
```

**Comment by kaqqao** [comment]
Excellent! Thanks for posting the details :)

**Comment by avkarthk** [comment]
Hi kaqqao,  
we are using springboot and graphql. Looking to implement validation groups (use case same) as mentioned by @ferguardiola. Can we use guice-validator for validating groups. Please note that we are using spring boot.

**Comment by avkarthk** [comment]
Any update on this?
