### ISSUE TITLE
No concrete subtypes

### ISSUE THREAD

**Issue by miguelocarvajal** [leangen/graphql-spqr#121]
Hello,

We are having an issue deploying a Spring Boot app, we get the following warnings:

`No concrete subtypes of org.springframework.data.domain.Pageable found`

This seems to be related to ClassUtils.findImplementions use of ClassLoader. When a deployable JAR is generated, the class loader is LaunchedURLClassLoader. In development it is sun.misc.Launcher.

Not sure if this is a bug or something I am doing wrong?

Thanks!

**Comment by miguelocarvajal** [comment]
It's definitely the way that Spring Boot generates the JAR.

I came up with a fix that I'm not in love with which recursively checks the JARs processed.
Reason why I don't like this solution is because now all of the JARs included in the Spring Boot (which is everything) are checked which slows down initialization a bit.

Any ideas on  how to better implement a solution to this?

```
diff --git a/src/main/java/io/leangen/graphql/util/classpath/ClassFinder.java b/src/main/java/io/leangen/graphql/util/classpath/ClassFinder.java
index a92306d..2f3d2d9 100755
--- a/src/main/java/io/leangen/graphql/util/classpath/ClassFinder.java
+++ b/src/main/java/io/leangen/graphql/util/classpath/ClassFinder.java
@@ -31,6 +31,7 @@ import java.util.regex.Matcher;
 import java.util.regex.Pattern;
 import java.util.stream.Collectors;
 import java.util.stream.Stream;
+import java.util.jar.JarInputStream;
 import java.util.zip.ZipEntry;
 import java.util.zip.ZipFile;
 
@@ -370,17 +371,49 @@ public class ClassFinder {
              e.hasMoreElements(); ) {
             ZipEntry entry = e.nextElement();
 
-            if (!entry.isDirectory() && entry.getName().toLowerCase().endsWith(".class")) {
-                try {
-                    log.trace("Reading {}", entry.getName());
-                    readClass(zip.getInputStream(entry), classVisitor);
-                } catch (IOException ex) {
-                    log.warn("Can't open '{}' in zip file '{}' : {}", entry.getName(), zipName, ex.getMessage());
+            if (!entry.isDirectory()) {
+                String entryName = entry.getName();
+
+                if (entryName.toLowerCase().endsWith(".class")) {
+                    try {
+                        log.trace("Reading {}", entryName);
+                        readClass(zip.getInputStream(entry), classVisitor);
+                    } catch (IOException ex) {
+                        log.warn("Can't open '{}' in zip file '{}' : {}", entryName, zipName, ex.getMessage());
+                    }
+                } else if (entryName.toLowerCase().endsWith(".jar")) {
+                    try {
+                        processOpenJar(new JarInputStream(zip.getInputStream(entry)), entryName, classVisitor);
+                    } catch (IOException ex) {
+                        log.warn("Can't open '{}' in zip file '{}' : {}", entryName, zipName, ex.getMessage());
+                    }
                 }
             }
         }
     }
 
+    private void processOpenJar(JarInputStream zipInput, String jarName, ClassVisitor classVisitor) throws IOException {
+        ZipEntry entry;
+        while ((entry = zipInput.getNextEntry()) != null) {
+            String entryName = entry.getName();
+
+            if (!entry.isDirectory()) {
+                if (entryName.toLowerCase().endsWith(".class")) {
+                    try {
+                        log.trace("Reading {}", entryName);
+                        readClass(zipInput, classVisitor);
+                        zipInput.closeEntry();
+                    } catch (IOException ex) {
+                        log.warn("Can't open '{}' in zip file '{}' : {}", entryName, jarName, ex.getMessage());
+                    }
+                } else if (entryName.toLowerCase().endsWith(".jar")) {
+                    processOpenJar(new JarInputStream(zipInput), entryName, classVisitor);
+                    zipInput.closeEntry();
+                 }
+             }
+         }
+    }
+
     private void processDirectory(File dir, Map<String, ClassInfo> foundClasses) throws ClassReadingException {
         Collection<Path> files = findFiles(dir, Files::isRegularFile, path -> path.toString().endsWith(".class"));
         ClassVisitor classVisitor = new ClassInfoClassVisitor(foundClasses, dir);
```

**Comment by kaqqao** [comment]
Is it because Spring creates a fat JAR (which contains other JARs)? If that's the case, then what you're doing is probably the right thing. Shouldn't be _too_ slow if you filter by package.

It's actually a priority for me to replace the home-grown solution for classpath scanning with [FastClasspathScanner](https://github.com/lukehutch/fast-classpath-scanner), if for no other reason then for Java 9 modulepath compatibility.

What you could do is maybe use Spring's own `ClassPathScanningCandidateComponentProvider`. Or not use implementation discovery at all, but a custom strategy that immediately gives an implementation since I guess you already know what the concrete class to use is. How does your method with `Pageable ` look like? Is `Pageable `

**Comment by miguelocarvajal** [comment]
Yup. We're using `AutoScanAbstractInputHandler`.

I did think of using something like `ClassPathScanningCandidateComponentProvider` but that would make spqr Spring specific which we don't want. Your solution of implementing FastClasspathScanner seems like the most optimum.

Like you said, our solution isn't that slow. Just didn't feel like it was the best one. It solves our needs and should fix it for anybody else that runs into this issue until FastClasspathScanner is implemented.
