### ISSUE TITLE
Authorization in GraphQL

### ISSUE THREAD

**Issue by ferguardiola** [leangen/graphql-spqr#125]
Hello,

Is there any way to introduce authorization in GraphQL ?

So i have for example 

```
  @GraphQLMutation(name = "createUser")
    @ValidationGroups(CreateChecks.class)
    public User createUser(@GraphQLArgument(name = "userRequest") @Valid UserRequest userRequest) throws ServiceException 
   
   @GraphQLQuery(name = "getUserById")
    public User getUserById(@GraphQLArgument(name = "id") @NotNull Integer id) throws ServiceException {
 
```

I want only users with a specific role (CREATE_USEr) can execute createUser. 

I have the authorzation in the web tier (JAX-RS), but the entry point for all operation in GraphQL is in a single point, so i can't do:
```

    @RolesAllowed(CREATE_USER)
    @POST
    @Path("/gql")
    public Object graphQL(GQLQuery gqlQuery) throws Exception { 
       //Executes the graph (invoques the service)
   }
```
because then only user with role CREATE_USER could execute getUserById and that's not what i want- So is there any way to do that with graphQL ?

Thank you!

**Comment by ferguardiola** [comment]
Hello again,

Well looking it can be done in guice with Interceptors.

1)  First we need an AuthFilter (I'm usgin JwtAuthFilter (JsonWebToken) in the web tier that authenticates the user and then load it on a ThreadLocal variable 
```
public class MyAuthenticator implements Authenticator<Map<String, ?>, User> {

 public Optional<User> authenticate(Map<String, ?> params) throws AuthenticationException {
   //Authenticate the user using the params in the map.. then you got the object User
  ActiveUser.set(user);
}


public class ActiveUser {

    private static InheritableThreadLocal<User> userThreadLocal = new InheritableThreadLocal<>();

    public static void set(User user) {
        userThreadLocal.set(user);
    }

    public static User get() {
        return userThreadLocal.get();
    }
}

```
2) Create the Interceptor where we will check if the user has the roles we want. The roles are obtained from the annotated method in our service

```

public class AuthorizerInterceptor implements MethodInterceptor {

    public Object invoke(MethodInvocation invocation) throws Throwable {
        RolesAllowed rolesAllowed = invocation.getMethod().getAnnotation(RolesAllowed.class);
        if (ActiveUser.get().getAuthorizations().stream()
                .anyMatch(authorization -> Arrays.asList(rolesAllowed.value()).contains(authorization.getRole().getName()))) {
            return invocation.proceed();
        } else {
            throw new AuthorizationException("User " + ActiveUser.get().getUserName() + " not authorized");
        }
    }

}

```

3) Annotae the service with the annotation we want to check (RolesAllowed) in this case

```
@RolesAllowed("MyRole")
 public User createUser(@GraphQLArgument(name = "userRequest") @Valid UserRequest userRequest) throws ServiceException {
   
``` 
4) Bind the injector with GUICE

In the AbstractModule in GUICE

bindInterceptor(Matchers.any(), Matchers.annotatedWith(RolesAllowed.class), new AuthorizerInterceptor ());

Then it works!

**Comment by kaqqao** [comment]
Awesome you figured it out!
I was going to suggest solving it by the framework and not SPQR directly, which is exactly what you ended up doing.
Btw, there is already [a feature request](https://github.com/leangen/graphql-spqr/issues/92) for making meta data of this type easily accessible from an `Instrumentation` or from a `GraphQLFieldVisibility` implementation.
I aim to start working on it soon.

**Comment by kaqqao** [comment]
Hey, I've just noticed you never clean up the `ActiveUser ` thread-local, which can cause nightmarish bugs, where one a wrong user remains bound after a thread is returned to the pool.
I strongly suggest you add something like `ActiveUser.set(null)` to somehow be executed at the end of the request (a simple servlet filter or a request listener should suffice).

Also, unless you _really_ know what you're doing, `InheritableThreadLocal` is not recommended, because you then also need to somehow ensure to clean up the context for the spawned threads. Instead, if thread jumping is even required, it is usually a better idea to create a custom `Executor` that cleanly propagates and cleans up the context, akin to Spring's `DelegatingSecurityContextExecutor`.

**Comment by ferguardiola** [comment]
Hi, 

Thank you, i will take in care.

**Comment by ashifqureshi** [comment]
Hi Kaqqao,

When you are planning to release Authentication and Authorization support.

Thank you!
