### ISSUE TITLE
Best way to handle sparse relationships

### ISSUE THREAD

**Issue by anderkh** [leangen/graphql-spqr#128]
First off, I want to say how much I like graphql-spqr.  It's right in line with my view about generating a schema from what you already have.

I have a situation that I'd like your opinion on.  I'm generating my graphql schema from objects that are built from an ORM (apache Cayenne).  It works well, except in certain situations where manually controlling the graphql schema might be easier, but I may be just plain wrong!

In the database I have tables that represent profile questions, the options for those profile questions, and the answers that members have given for those profile questions.

I would like to do a single query that will return all the questions, plus the answers that a particular member has already answered.

If I root the query in "Member", I don't get the unanswered questions without jumping through hoops.  If I root the query in "ProfileQuestion", I would need to pass in a member and add instance variables so that the values are accessible from the graph.

Am I going about this wrong?  Is there a better way?  Is there a way to add on to the generated schema so I could build something more custom?

Thanks for any thoughts!

**Comment by kaqqao** [comment]
Glad you're finding SPQR useful :)

I'm not 100% sure I got your question, but I think you're asking how to _attach_ a field (relationship) to a GraphQL type without touching the corresponding Java class. If that's the case, all you need to do is use `@GraphQLContext`:

```java
@GraphQLQuery
public List<Question> questions(@GraphQLContext Member member) {
   return dataBase.findQuestions(member.getId()); //get question's by member ID
}
```

This would result in the `Member` GraphQL type having a new field called `questions`. Using `@GraphQLContext` you can decouple the logic as it makes sense from the Java perspective, while keeping the fields nested as it makes sense from the GraphQL perspective.

If your question was how to effectively perform a `JOIN`:

* you'd add an extra argument to the method: `@GraphQLEnvironment ResolutionEnvironment env`
* obtain the `DataFetchingEnvironment`: `ResolutionEnvironment#dataFetchingEnvironment`
* get a selection set from it: `DataFetchingEnvironment#getSelectionSet`
* obtain the sub-selections from there, and based on that knowledge, optimize the query to eagerly JOIN

**Comment by anderkh** [comment]
The @GraphQLContext annotation works great!  Do you have a list somewhere of all the annotations and what they do?

**Comment by kaqqao** [comment]
Unfortunately, not yet :(
All annotations reside in [the same package](https://github.com/leangen/graphql-spqr/tree/master/src/main/java/io/leangen/graphql/annotations) so you can find them all there. Some of them have JavaDoc explaining their use, but in most cases you have to look at the tests to see them in action.
