### ISSUE TITLE
Errors during mutations?

### ISSUE THREAD

**Issue by anderkh** [leangen/graphql-spqr#129]
What is the correct way to deal with errors that occur during a mutation?  I tried throwing an exception in my mutation method, but that didn't help.

Thanks!

**Comment by kaqqao** [comment]
Sorry, but this is too vague to answer. How did throwing an exception not help?
All exceptions thrown from a resolver method will by default bubble up to the [SimpleDataFetcherExceptionHandler](https://github.com/graphql-java/graphql-java/blob/14d3969308b177be6c7eb61b0e8b2aa959948c4d/src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java) and be translated into a `GraphQLError` in the result.

Is this not what you're seeing or were you expecting a different behavior?

**Comment by anderkh** [comment]
Strange - it did not seem to do that (because that's what I was hoping it would do!).  I'll come back with more details.  Thanks.

**Comment by anderkh** [comment]
OK, this looks like more of a problem with Apollo on iOS.  You're right - the exception data comes back as a graph QL error. But for some reason, the Apollo client is giving me a null error.  I'll look further on that side.  Sorry to bother!

**Comment by kaqqao** [comment]
No worries, glad you're making progress :)
