### ISSUE TITLE
Mark function parameter as required

### ISSUE THREAD

**Issue by stoyandekov7** [leangen/graphql-spqr#138]
In GraphQL schema you can say something like:
```
type Query {
  user(id: String!): User
}
```
which will throw error if ID is not provided as argument. Is there a way to achieve this using `@GraphQLArgument` or simmilar annotation?

**Comment by kaqqao** [comment]
You can use the dedicated `@GraphQLNonNull` or any of the following:
`javax.annotation.Nonnull`, `javax.validation.constraints.NotNull`, `org.jetbrains.annotations.NotNull`, `lombok.NonNull`.

**Comment by stoyandekov7** [comment]
Brilliant, `@GraphQLNonNull` works as a charm. Thank you for the instant response!
