### ISSUE TITLE
0.9.8 release date

### ISSUE THREAD

**Issue by szantogab** [leangen/graphql-spqr#144]
Hi!

Can you tell me a date when 0.9.8 is expected to be released?

In the meantime, can I download the current 0.9.8-SNAPSHOT from a Maven repo? I would need the latest version of graphql-java.

Thanks,
Gabor

**Comment by szantogab** [comment]
@kaqqao Any info on this?

**Comment by kaqqao** [comment]
I don't really have a date. I work on this in my free time only, so it highly depends on pretty much everything else going on in my life. That said, I do expect to release 0.9.8 this week...

**Comment by szantogab** [comment]
@kaqqao Thank you, keep up the good work!

**Comment by kaqqao** [comment]
0.9.8 has been released. Check out the [changelog](https://github.com/leangen/graphql-spqr/blob/master/CHANGELOG.md).
