### ISSUE TITLE
MapToListTypeAdapter nullability

### ISSUE THREAD

**Issue by LaurenceGA** [leangen/graphql-spqr#145]
(Using the default MapToListTypeAdapter)
## Output types
If I have an object annotated like:
```java
@GraphQLNonNull
@GraphQLQuery(name = "field")
public Map<@GraphQLNonNull String, @GraphQLNonNull String>getField() {
  return null;
}
```
In the schema I get the field
```field [mapEntry_String_String]!```

The type mapEntry_String_String picks the non-nulls up fine for its fields, but I would expect the field to be of type
```field [mapEntry_String_String!]!```
as it doesn't make sense to have a null map entry in the list.

## Input types
If I have a field annotated like:
```java
@GraphQLNonNull
@GraphQLInputField(name = "field")
private Map<@GraphQLNonNull String, @GraphQLNonNull String> field;
```
Then in the schema I get the field
```field [mapEntry_String_String_input!]```
I would expect it to be
```field [mapEntry_String_String_input!]!``` as it's annotated to be non-null.
The object ```mapEntry_String_String_input``` picks up the annotations fine for its own fields.
Is there something I'm missing a way to mark these non-null myself? Seems like a bug to me.

### summary
* For output types it applies the ```@GraphQLNonNull``` annotation correctly, but should change to make the generated ```mapEntry``` object always non-null.
* For input types is applies the ```@GraphQLNonNull``` annotation to the generated ```mapEntry``` object instead of to the list itself, and should have the ```mapEntry``` object be always non-null.

**Comment by kaqqao** [comment]
Beautifully written report!
Will take a look. Thanks!

**Comment by kaqqao** [comment]
Can't seem to replicate your findings for input types... I always get a non-null list of map entries, as I'd expect:

```java
@Test
public void testNonNullMap() {
    GraphQLSchema schema = new GraphQLSchemaGenerator()
            .withTypeAdapters(new MapToListTypeAdapter<>())
            .withOperationsFromSingleton(new Service())
            .generate();

    ... //getting field: [mapEntry___String___String_input]!
}

public class Service {

    @GraphQLQuery
    public String test(Wrapper in) {
        return "";
    }
}

public class Wrapper {

    @GraphQLNonNull
    @GraphQLInputField(name = "field")
    public Map<@GraphQLNonNull String, @GraphQLNonNull String> field;
}
```

The schema ends up as I'd expect:

```graphql
input WrapperInput {
  field: [mapEntry___String___String_input]!
}
```

Am I doing something different than you?

And I agree on the point non-nullable entries, it should indeed be `field: [mapEntry___String___String_input!]!`. Taking care of that...

**Comment by kaqqao** [comment]
I made the entries non-nullable, so that change will land in 0.9.8.
The transparent treatment of private fields is in popular demand, so I'm starting the work on it. But I don't want to delay the 0.9.8 release any further, so this will land in 0.9.9.

In the meantime, I'll try replicating your setup, but if you have the time a simple test demonstrating the behavior you're seeing would be helpful.

Cheers!

**Comment by LaurenceGA** [comment]
Sure. The following test illustrates SPQR picking up private fields. This _only_ works with the ```GraphQLInputField``` annotations. Remove one on the ```InputType``` class and the test will fail.
Assertion is a bit complicated, but I think it illustrates the point.
```java
@Test
public void privateInputFieldsTest() {
  GraphQLSchema schema =
      new GraphQLSchemaGenerator()
          .withOperationsFromSingleton(new Mutations())
          .generate();

  Assert.assertEquals(
      ((GraphQLInputFieldsContainer)
              (schema
                  .getMutationType()
                  .getFieldDefinition("SomeMutation")
                  .getArgument("input")
                  .getType()))
          .getFieldDefinitions()
          .stream()
          .map(GraphQLInputObjectField::getName)
          .collect(Collectors.toSet()),
      Stream.of("number", "another", "text").collect(Collectors.toSet()));
}

private static class Mutations {
  @GraphQLMutation(name = "SomeMutation")
  public String someMutation(@GraphQLArgument(name = "input") InputType input) {
    return null;
  }
}

private static class InputType {
  @GraphQLInputField(name = "text")
  private String text;

  @GraphQLInputField(name = "another")
  private String another;

  @GraphQLInputField(name = "number")
  private int number;
}
```

**Comment by kaqqao** [comment]
Ah, this is an exceptional case indeed, because it is Jackson that looks at private fields and not SPQR, but Jackson is configured to respect `@GraphQLInputField` annotations, so it seems surprising.

I opened a separate issue #160 about annotation on private fields, so track that one for progress.
