### ISSUE TITLE
AutoDiscovery + scanPackages fails in a fat jar.

### ISSUE THREAD

**Issue by jeacott1** [leangen/graphql-spqr#150]
in a spring boot application packaged as a standard fat jar configuring scanPackages doesnt work.
```
@GraphQLInterface(
        ..
        implementationAutoDiscovery = true,
        scanPackages= "my.packagel"
```

it works fine if the app is exploded or run directly in an ide, but after packaging it simply hunts the entire output jar.

**Comment by kaqqao** [comment]
This is a known issue #121 in v0.9.7. It's fixed in v0.9.8 which will be released this week.
