### ISSUE TITLE
@GraphQLNonNull doesn't support nested static classes

### ISSUE THREAD

**Issue by benneq** [leangen/graphql-spqr#154]
I have some class hierarchy like this:
```
public class Foo {
    public static class Bar {
        // ...
    }
}
```

I can't use `@GraphQLNonNull` for `Foo.Bar` within a method argument:
```
@GraphQLMutation
public boolean setFooBar(@GraphQLNonNull Foo.Bar fooBar) {
    return true;
}
```

When I put `Bar` in a separate file it works as expected:
```
public class Bar {
    // ...
}
```

Maybe just adding `ElementType.PARAMETER` to `@GraphQLNonNull` is enough for this to work?

**Comment by kaqqao** [comment]
This is bug in Java itself, present in at least in Oracle JRE 8 & 9. Have not tested in OpenJDK or Oracle 10+.
You can find some more info [here](http://stackoverflow.com/questions/39952812/why-annotation-on-generic-type-argument-is-not-visible-for-nested-type).

I don't think making `@GraphQLNonNull` `ElementType.PARAMETER` would be a good idea, as it would appear to work in some cases and not in others (e.g. `List<@GraphQLNonNull String>` would still not work) which would only add to the confusion...

If you can, please test later Java versions and report the findings.
