### ISSUE TITLE
Pagination variables null value

### ISSUE THREAD

**Issue by andykdavies** [leangen/graphql-spqr#16]
Hi, We are having a problem using pagination variables, the query is being executed but returning all available records and ignoring any pagination variables passed. Having inspected our GraphQL controller the variables/values are correct but once they reach the OperationExecutor they each have a null value.

**Comment by andykdavies** [comment]
Sorry this is fixed now. The variables were sent as a separate object in the JSON and we weren't passing these through to GraphQL, only the query string was being passed through and hence the variables having null values.

**Comment by kaqqao** [comment]
Ah, I see. There indeed was a problem with treatment of scalar variables, so I thought this was related.
