### ISSUE TITLE
Take annotations on private fields into account (also enables Lombok support)

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr#160]
SPQR never looks at private elements, so annotating a private field will not work (with the exception of `@GraphQLInputField` with Jackson, but that is because Jackson takes private fields into account, not SPQR).

Many users are requesting this, mostly for compatibility with Lombok, AutoValue and other libraries, but as a general feature as well.

**Comment by gregdymek** [comment]
it's not only Lombok, I think it takes a precedence of method than field, annotations like GraphQLNonNull, GraphQLIgnore are not working if there are setters not annotated, field annotations are working only if there is no setter or getter
