### ISSUE TITLE
Nonnull ignored in mutation parameters in 0.9.8

### ISSUE THREAD

**Issue by stoyandekov7** [leangen/graphql-spqr#165]
In 0.9.8, it appears if you want to make a mutation argument mandatory, you have to use @GraphQLNotNull. Any other annotation (like javax.annotation.Nonnull) is ignored.

```
@GraphQLMutation
public User getUser(@Nonnull String username) { //this should make username non-nullable
}
```

**Comment by kaqqao** [comment]
The GraphQL spec has changed to better deal with non-null arguments with a default value.
https://github.com/facebook/graphql/pull/418
Not sure if/when this will take effect in graphql-java.
