### ISSUE TITLE
@JsonCreator on static method factory produces ClassCastException

### ISSUE THREAD

**Issue by kralask** [leangen/graphql-spqr#166]
Hello Team,
I noticed an error while annotating  a query method argument as @GraphQLArgument and having @JsonCreator annotation in argument class constructable with a static factory method marked as @JsonCreator :

code to reproduce:
```
package main;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import graphql.schema.GraphQLSchema;
import io.leangen.graphql.GraphQLSchemaGenerator;
import io.leangen.graphql.annotations.GraphQLArgument;
import io.leangen.graphql.annotations.GraphQLQuery;
import io.leangen.graphql.metadata.strategy.query.AnnotatedResolverBuilder;
import io.leangen.graphql.metadata.strategy.type.DefaultTypeInfoGenerator;
import io.leangen.graphql.metadata.strategy.value.jackson.JacksonValueMapperFactory;

public class Main {
    public static class Query {

        @GraphQLQuery(name = "getSomething")
        public Object getSomething(@GraphQLArgument(name = "request") Request request) {
            return null;
        }

    }

    public static class Request {

        private final String term;

        private Request(String term) {
            this.term = term;
        }

        @JsonCreator
        public static Request factory(@JsonProperty("term") String term) {
            return new Request(term);
        }

    }

    public static void main(String ... args) {
        final GraphQLSchema schema = new GraphQLSchemaGenerator()
                .withResolverBuilders(
                        //Resolve by annotations
                        new AnnotatedResolverBuilder()
                )
                .withOperationsFromSingleton(new Query(), Query.class)
                .withValueMapperFactory(JacksonValueMapperFactory.builder()
                        .withPrototype(new ObjectMapper())
                        .withConfigurer(new JacksonValueMapperFactory.AbstractClassAdapterConfigurer())
                        .withTypeInfoGenerator(new DefaultTypeInfoGenerator())
                        .build())
                .generate();
    }

}

```

StackTrace:

> Exception in thread "main" java.lang.ClassCastException: java.lang.reflect.Method cannot be cast to java.lang.reflect.Constructor
> 	at io.leangen.graphql.metadata.strategy.value.jackson.JacksonValueMapper.toInputField(JacksonValueMapper.java:83)
> 	at io.leangen.graphql.metadata.strategy.value.jackson.JacksonValueMapper.lambda$getInputFields$0(JacksonValueMapper.java:76)
> 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 	at io.leangen.graphql.metadata.strategy.value.jackson.JacksonValueMapper.getInputFields(JacksonValueMapper.java:77)
> 	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLInputType(ObjectTypeMapper.java:63)
> 	at io.leangen.graphql.generator.mapping.common.ObjectTypeMapper.toGraphQLInputType(ObjectTypeMapper.java:32)
> 	at io.leangen.graphql.generator.mapping.common.CachingMapper.toGraphQLInputType(CachingMapper.java:37)
> 	at io.leangen.graphql.generator.OperationMapper.toGraphQLInputType(OperationMapper.java:209)
> 	at io.leangen.graphql.generator.OperationMapper.toGraphQLArgument(OperationMapper.java:218)
> 	at io.leangen.graphql.generator.OperationMapper.lambda$toGraphQLField$4(OperationMapper.java:145)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 	at io.leangen.graphql.generator.OperationMapper.toGraphQLField(OperationMapper.java:146)
> 	at io.leangen.graphql.generator.OperationMapper.lambda$generateQueries$0(OperationMapper.java:89)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 	at io.leangen.graphql.generator.OperationMapper.generateQueries(OperationMapper.java:90)
> 	at io.leangen.graphql.generator.OperationMapper.<init>(OperationMapper.java:73)
> 	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:892)
> 	at main.Main.main(Main.java:51)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

- spqr version : 0.9.8
- Json Serializer/Deserializer : Jackson 2.8.8

Thanks
Kralask

**Comment by kaqqao** [comment]
Thanks for the report.

This bug was present in 0.9.7 but should have been fixed in 0.9.8.

The line numbers from the stack trace also do not correspond with 0.9.8. E.g. [line 83 in `JacksonValueMapper`](https://github.com/leangen/graphql-spqr/blob/master/src/main/java/io/leangen/graphql/metadata/strategy/value/jackson/JacksonValueMapperFactory.java#L83) does not contain any code.

Could you please verify 0.9.8 is being loaded? You might have multiple versions on the classpath or something...

**Comment by kralask** [comment]
Thanks for your quick reply.

I thought 0.9.8 was loaded indeed.
I will check it on Monday and come back to you.

Cheers

Le ven. 24 août 2018 à 19:58, Bojan Tomić <notifications@github.com> a
écrit :

**Comment by kralask** [comment]
I confirm version 0.9.8 solves this issue. thanks

**Comment by kaqqao** [comment]
Cool, cheers!
