### ISSUE TITLE
How to implement custom directives in SPQR V0.9.8?

### ISSUE THREAD

**Issue by sujivisva** [leangen/graphql-spqr#167]
How to implement custom directives in SPQR V0.9.8? Please provide some good examples.

**Comment by kaqqao** [comment]
Depending on the kind of directives you have in mind. Custom query directives are not yet supported. The others you might add via `GraphQLSchemaGenerator#withSchemaProcessors` and then register a directive.

But what use-case are you trying to implement?

I'm asking because directives might easily not be what you want, as in SPQR you can have access to much richer options.

**Comment by kaqqao** [comment]
I said it wrong (now corrected). Custom _query_ directives _are_ doable. It's the directives on schema elements (types etc) that you can't easily do yet.

That said, you can always add a custom `TyoeMapper` and add directives there.

**Comment by sujivisva** [comment]
We actually are trying to filter/omit/modify the results of a data fetcher of a particular field using custom directives, given like in graphql-java project tutorial. But since we are using SPQR V0.9.8, Seems it is not straight forward. 

And am also a beginner in SPQR. So please provide a good example to achieve this feature using custom directives or using any other feature of SPQR for me better understanding. Thanks.

**Comment by sujivisva** [comment]
Sorry, by mistake I closed

**Comment by kaqqao** [comment]
Can you point me to the tutorial you're referring to so I see if a similar thing can be done in SPQR?

**Comment by sujivisva** [comment]
Following is the url which I have referred.

3 examples
Authorization
Date Formatting
Chain of directives

We may end up using any/combination of the above like scenarios

https://graphql-java.readthedocs.io/en/latest/sdldirectives.html?highlight=directive

**Comment by sujivisva** [comment]
A gentle reminder, any update on my request?

**Comment by kaqqao** [comment]
Posted in #171:

> This is how we do in graphql-java project. How can it be achieved via SPQR?

```java
static GraphQLSchema buildSchema() {

    String sdlSpec = "" +
            "type Query {\n" +
            "    dateField : String @dateFormat \n" +
            "}";

    TypeDefinitionRegistry registry = new SchemaParser().parse(sdlSpec);

    RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()
            .directive("dateFormat", new DateFormatting())
            .build();

    return new SchemaGenerator().makeExecutableSchema(registry, runtimeWiring);
}
```

**Comment by kaqqao** [comment]
You can register an additional directive as such:

```java
generator.withSchemaProcessors(
    (schemaBuilder, buildContext) -> schemaBuilder.additionalDirective(...));
```

But (according to my current understanding), this only makes sense for query directive (something the client sends as a part of the query, like `@skip` or `@deffered`).

Directives like `@dateFormat` it simply make no sense in SPQR: they're there to help you when paring SDL and mapping it to your code. In SPQR, there's no SDL and you _start_ from your code.
E.g. `@dateFormat` is used to tell you that you need to provide date formatting to a specific field when mapping it to Java. In SPQR the field is generated from a method, so the method must already know what format it should return.

Still, sometimes field or type level directives can be useful in instrumentations. E.g. if you want to intercept field resolution and inspect the authentication directives.
In that case, I'd suggest you simply use annotations.

```java
public class BookService {
     
      @Auth(roles= {"Admin"}) //example annotation
      public addBook(Book book) { /*insert a Book into the DB */ }
}
```
As each `GraphQLFieldDefinition` is backed by a Java methods (or a field), you can get the underlying objects in you interceptor or wherever:

```java
GraphQLFieldDefinition field = ...;
Operation operation = Directives.getMappedOperation(field).get();

//Multiple methods can be hooked up to a single GraphQL operation. This gets the @Auth annotations from all of them
Set<Auth> allAuthAnnotations = operation.getResolvers().stream()
                .map(res -> res.getExecutable().getDelegate()) //get the underlying method
                .filter(method -> method.isAnnotationPresent(Auth.class))
                .map(method -> method.getAnnotation(Auth.class))
                .collect(Collectors.toSet());

```

Or, to inspect only the method that can handle the current request:

```java
Auth auth = .getApplicableResolver(argumentNames).getExecutable().getDelegate().getAnnotation(Auth.class);
```

Then you can inspect you annotations as you wish,

Of course, there's no real need to actually implement authentication this way, as you're probably using a framework like Spring or Guice or JAX-RS, that already has a way to intercept all methods and implement security. So you can just use that instead. Much simpler and safer. E.g. for Spring Security, just keep using it as normal:

```java
```

**Comment by kaqqao** [comment]
0.9.9 is out, with full directive support. Meta-annotate any annotation with `io.leangen.graphql.annotations.types.GraphQLDirective` and it well get mapped as directive on the target element.
To register a client directive, use `GraphQLSchemaGenerator#withAdditionalDirectives(AnnotatedType...)`.
To inject a directive value, annotated a parameter with `io.leangen.graphql.annotations.GraphQLDirective` (notice it's **not the same directive** as above).
