### ISSUE TITLE
issues with GraphQLInterface, and object input types for Mutations, specifying deprecation at class level...

### ISSUE THREAD

**Issue by kevinludwig** [leangen/graphql-spqr#168]
I'm having three separate issues, and not sure if they're bugs or (more likely) a misunderstanding by me of how to use the library. 

First, with respect to `@GraphQLInterface`, I've found that for an inheritance chain, I have to specify a custom type resolver, e.g. 

```
@GraphQLInterface(name = "SomeInterface", implementationAutoDiscovery = true)
interface SomeInterface {
    String id();
}

public abstract class SomeAbstractImpl implements SomeInterface {
    @GraphQLQuery
    @Overrides
    public String id() { return "test"; }
}

@GraphQLTypeResolver(SimpleTypeResolver.class)
public class SomeLeafImpl extends SomeAbstractImpl {
    @GraphQLQuery 
    public String more() { return "more stuff"; }
}

/* I didn't expect to have to implement this, and figuring out how to hook this in was not obvious
given the state of the documentation. */
public class SimpleTypeResolver implements TypeResolver {
    @Override
    public GraphQLObjectType resolveType(TypeResolutionEnvironment env) {
        String typeName = env.getObject().getClass().getSimpleName();
        return (GraphQLObjectType) env.getSchema().getType(typeName);
    }
}
```

Second issue (which I have no solution for at the moment), is if I have a mutation and that mutation has a complex object as input, I currently get the validation error saying it can't find the input type, e.g.

```
@Component
class RootMutation {
    @Autowired 
    SomethingService somethingService;

    @GraphQLMutation
    public SomethingInfo createSomething(SomethingInput somethingInput) {
        return somethingService.create(somethingInput);
    }

    public class SomethingInput {
        public String id;
        public String desc;
    }
}

```

Runs into `Validation error of type UnknownType: Unknown type SomethingInput`

Finally not sure how to specify deprecation at class level, e.g.

```
/* how do I specify deprecation of this entire thing?, is there a class-level annotation so that 
I can specify uses of this deprecated from one place? */
class SomeModel {
    @GraphQLQuery(deprecationReason="because")
    public String id() {return "1";}

    @GraphQLQuery(deprecationReason="also this")
    public String desc() {return "um";}
}
```

**Comment by kaqqao** [comment]
Something is off...

1) You should not have to add a custom `TypeResolver` almost ever. The built-in one should be able to handle most cases just fine. What problems did you encounter with it?

2) Complex inputs in mutations most definitely work (otherwise there would be many angry users and many failing tests). So there could be something strange in yiu setup. Can you show how you configure the generator etc?

3) You can't deprecate an entire type, only individual fields. But, it is true that SPQR could take a class-level annotation and treat it as if it were on every field. But there's no such feature at the moment, as mass deprecations are fairly uncommon so it wasn't requested yet.

**Comment by kaqqao** [comment]
Btw, types used as input are by default named `_type name_ + "Input"` (can easily be changed), so there's commonly no reason to name stuff `SomethingInput`.

The reason is that the same Java type must be differently mapped to a `GraphQLOutputType` and to a `GraphQLInputType`.

**Comment by kevinludwig** [comment]
OK so for the mutation case, it's fixed. It was two things. Firstly I had to rename the class so that it doesn't end in `Input` which made it visible. Then I had to make it a static inner class (not just inner class) because of issues Jackson has with construction of inner classes (related to my lack of constructors). So really, the fact that I had ended up naming it ending in `Input` made it not-visible (the lookup in the schema was probably failing I guess?) but without insight into the internal workings it would have been very difficult to figure out.

It would be great to get the type resolver issue figured out but at least now the project is building and the tests are passing. Thanks!

**Comment by kaqqao** [comment]
Yeah, your mutation example looks perfectly fine.

Not sure if it helps you, but it's possible to configure SPQR to use whatever custom annotations you already have (or no annotations at all, for that matter).

**Comment by kaqqao** [comment]
There's only one thing I can come up with that would explain the `Input` mystery. Did you see any warnings in the log about type name collisions?
The inner class thing makes perfect sense: it's impossible to create an instance of the an inner class without an instance of the outer - and there's no instance of the outer.

What issues do you have with the type resolver? What happens when you don't register a custom one?

**Comment by kevinludwig** [comment]
Without the type resolver i get 

java.util.concurrent.CompletionException: io.leangen.graphql.metadata.exceptions.UnresolvableTypeException: Exact GraphQL type for MyInterfaceComponent is unresolvable for an object of type com.demo.graphql.components.DerivedComponent`

**Comment by kaqqao** [comment]
Ah... I said the built-in resolver is _almost always_ enough, and it seems you falling into that _almost_ category 😦 

It could also be that something goes awry... If you can't exemplify the class hierarchy that causes this to happen, you may wish to look into it deeper yourself. Placing a break point [here](https://github.com/leangen/graphql-spqr/blob/graphql-spqr-v0.9.8/src/main/java/io/leangen/graphql/generator/DelegatingTypeResolver.java#L40) and following what happens when it tries to deduce the type would be a good starting point.

The algorithm goes like this:

* Get the class of the result and try to figure out the corresponding GraphQL type name (e.g. `DerivedComponent `)
* Check if there's known subtypes of the current field's type (e.g. `MyInterfaceComponent`) and which of those are compatible with the actual type of the result
* If there's 0 or 1 matching subtypes, the situation unambiguous and the exact GraphQL type can already be resolved
*  Otherwise, try to find an explicitly registered resolver (this what you have). If there's one, usr it to resolve the types.
* If no resolvers are found, it tries to deduce the exact matching Java subtype. Consider the result that is an instance of `DerivedComponent` and the field that is of type `MyInterfaceComponent`.
  * If there's no generics involved, the situation is trivial: `DerivedComponent` is already the matching subtype.
  * If there's generics involved, it gets murky. E.g. the result is an instance of `DerivedComponent`, but `DerivedComponent` is generic (`DerivedComponent<T> extends MyInterfaceComponent<T>`), and the field type is `MyInterfaceComponent<Something>`.
    * If all the needed generic information is present, it can be deduced the matching subtype is `DerivedComponent<Something>`.
    * If `DerivedComponent` has extra generic parameters (not coming from the parent), it is impossible to find the exact match and an exception is thrown. This is likely the situation you end up in.

**Comment by kevinludwig** [comment]
Here is an example with a passing and failing test showing the problem. 

https://github.com/kevinludwig/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/TypeResolverTest.java

The basic problem is:
```
interface A {}
class B implements A {};
class C extends B {}
```
And a query for `A` can not resolve the concrete type `C`. If I remove `B` (and copy the code in `B` into every implementation class `C` then it works.

**Comment by kaqqao** [comment]
Oh wow... not only is this a legit bug, it's also one that has been present since the beginning and somehow no one has noticed it 😨 
Thanks a bunch for the tests! I'll fix this immediately and it's shipping in 0.9.9.

**Comment by kevinludwig** [comment]
thanks, and no problem about the tests.

**Comment by windgaucho** [comment]
Hello @kevinludwig,

can you please show an example code about how you resolve the ````Validation error of type UnknownType: Unknown type SomethingInput```` I am having the same issue with a custom object input in a mutation and I can not figure out how to resolve it.

**Comment by kaqqao** [comment]
@windgaucho Check the generated schema. For one reason or another, the type you _believe_ is called `SomethingInput` is called something else, or doesn't exist.
Without seeing the underlying code and the resulting schema, it's impossible to say what happens.

**Comment by windgaucho** [comment]
@kaqqao Where I can check the generated schema?

Here is my code:

`UserService class`
````
package com.windgaucho.gymstudio.service;

import java.util.Date;
import java.util.List;
import java.util.Optional;

import com.windgaucho.gymstudio.exceptions.InvalidCredentialsException;
import com.windgaucho.gymstudio.graphql.types.UserData;
import com.windgaucho.gymstudio.model.Role;
import com.windgaucho.gymstudio.model.User;
import com.windgaucho.gymstudio.repository.RoleRepository;
import com.windgaucho.gymstudio.repository.UserRepository;
import com.windgaucho.gymstudio.security.jwt.JwtTokenUtil;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;

import io.leangen.graphql.annotations.GraphQLArgument;
import io.leangen.graphql.annotations.GraphQLMutation;
import io.leangen.graphql.annotations.GraphQLQuery;
import io.leangen.graphql.spqr.spring.annotation.GraphQLApi;

@GraphQLApi
@Service
public class UserService {
    @Autowired
    private JwtTokenUtil jwtTokenUtil;
    @Autowired
    private RoleRepository roleRepository;
    private UserRepository userRepository;

    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @PreAuthorize("hasRole('ADMIN')")
    @GraphQLQuery(name = "users")
    public List<User> getUsers() {
        return userRepository.findAll();
    }

    @PreAuthorize("hasRole('ADMIN')")
    @GraphQLQuery(name = "user")
    public Optional<User> getUserById(@GraphQLArgument(name = "id") int id) {
        return userRepository.findById(id);
    }

    @GraphQLMutation(name = "signin")
    public String signin(@GraphQLArgument(name = "username") String username,
        @GraphQLArgument(name = "password") String password) throws InvalidCredentialsException {
        Optional<User> user = userRepository.findByUsername(username);
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        if(user.isPresent()) {
            if (encoder.matches(password, user.get().getPassword())) {
                return jwtTokenUtil.generateToken(user.get().getUsername());
            } else {
                throw new InvalidCredentialsException("Invalid Credentials!");
            }
        } else {
            throw new InvalidCredentialsException("Invalid Credentials!");
        }
    }

    @PreAuthorize("hasRole('ADMIN')")
    @GraphQLMutation
    public User updateUser(@GraphQLArgument(name = "user") UserData user) {
        User userUpdate = this.userRepository.findById(user.id).get();
        if (userUpdate != null) {
            Role role = this.roleRepository.findById(user.idRole).get();
            if (role != null) {
                userUpdate.setUsername(user.getUsername());
                userUpdate.setLastname(user.getLastname());
                userUpdate.setFirstname(user.getFirstname());
                userUpdate.setEmail(user.getEmail());
                userUpdate.setEnabled(true);
                userUpdate.setRole(role);
                this.userRepository.save(userUpdate);
                return userUpdate;
            }
        }
        return null;
    }

    @PreAuthorize("hasRole('ADMIN')")
    @GraphQLMutation
    public boolean removeUser(int id) {
        boolean elimino = false;
        User user = userRepository.findById(id).get();
        if (user != null) {
            user.setFechaBaja(new Date());
            user.setEnabled(false);
            this.userRepository.save(user);
            elimino = true;
        }
        return elimino;
    }
}
````

`UserData input class`
````
package com.windgaucho.gymstudio.graphql.types;

public class UserData {
    private int id;
    private String username;
    private String lastname;
    private String firstname;
    private String email;
    private int idRole;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getIdRole() {
        return idRole;
    }

    public void setIdRole(int idRole) {
        this.idRole = idRole;
    }
}
````
and when I try to call the updateUser mitation I am getting the following error:
````
2019-02-14 00:01:54.351  WARN 79460 --- [nio-9010-exec-4] graphql.GraphQL                          : Query failed to validate : 'mutation updateUser($user: UserData!) {
  updateUser(user: $user) {
    id
    username
    firstname
    lastname
    email
    idRole
    role {
      id
      name
      __typename
    }
    __typename
  }
}
'
````
I am using graphql-spqr-spring-boot-starter, I will appreciate any help, I am stuck with this....

**Comment by windgaucho** [comment]
Hello, any hint on this? I am stuck....

**Comment by mprzydatek** [comment]
@windgaucho - did you solved this problem? (I'm also getting "Query failed to validate")

**Comment by windgaucho** [comment]
@mprzydatek Yes!! sorry about the delay :)
