### ISSUE TITLE
How to add RuntimeWiring while creating GraphQLSchema object using GraphQLSchemaGenerator class in SPQR V0.9.8?

### ISSUE THREAD

**Issue by sujivisva** [leangen/graphql-spqr#171]
This is how we do in graphql-java project. How can it be achieved via SPQR?

static GraphQLSchema buildSchema() {

    String sdlSpec = "" +
            "type Query {\n" +
            "    dateField : String @dateFormat \n" +
            "}";

    TypeDefinitionRegistry registry = new SchemaParser().parse(sdlSpec);

    RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()
            .directive("dateFormat", new DateFormatting())
            .build();

    return new SchemaGenerator().makeExecutableSchema(registry, runtimeWiring);
}

**Comment by kaqqao** [comment]
Please don't open duplicate issues. Merged with #167 .

**Comment by sujivisva** [comment]
Hi,

I am just trying to find different ways of achieving my goal. Adding RuntimeWiring is one of the way which I found (and it is not only used to create custom directives, there are other purposes as well). It is not my intention to create duplicate issues, if you feel so, apologies. Anyhow, thanks a lot for your response.

**Comment by kaqqao** [comment]
`RuntimeWiring` is used to wire behavior into a schema defined in SDL. There's no SDL in SPQR, and all behavior is already defined in the Java code you map.

You can customize various aspects, like type mapping, using custom `TypeMapper`s, value conversion, using custom `Input/OutputConverter`s etc.

**Comment by kaqqao** [comment]
If your use-case is better suited for starting from an SDL-defined schema, then using graphql-java directly is probably the best option.
