### ISSUE TITLE
Building GraphQLObject with specific POJO fields

### ISSUE THREAD

**Issue by Dave2605** [leangen/graphql-spqr#18]
While converting POJO to GraphQL object type GraphQLSchema.generate() method put there all POJO's fields that have getters. Is there any way to exclude some field from GQL object type?

**Comment by Dave2605** [comment]
sorry, its ok now, fixed it with overriding PublicResolverBuilder.isQuery method

**Comment by kaqqao** [comment]
Yup, that's the correct way to do it. I'll soon add support for `@GraphQLIgnore` on fields

**Comment by heruan** [comment]
While `@GraphQLIgnore` doesn't support fields, how can I exclude a getter for a certain bean?

**Comment by kaqqao** [comment]
It's actually really simple. Just add a custom `ResolverBuilder` when registering a bean:

```java
schemaGenerator.withOperationsFromSingleton(bean, new CustomResolverBuilder());
```

The custom builder could extend `AnnotatedResolverBuilder` (works off annotations) or `BeanResolverBuilder` (exposes getters and setters  only) but ignore some fields/methods based on annotations or any custom logic.
