### ISSUE TITLE
Upgrading from 0.9.7 to 0.9.8

### ISSUE THREAD

**Issue by efenderbosch** [leangen/graphql-spqr#183]
```java
        GraphQLSchemaGenerator generator = new GraphQLSchemaGenerator()
                .withNestedResolverBuilders(resolverBuilder)
                .withValueMapperFactory(valueMapperFactory)
                .withOutputConverters((config, defaults) -> defaults.drop(ObjectScalarAdapter.class));
```

This works fine under 0.9.7, but won't compile under 0.9.8.

In 0.9.7 ``ObjectScalarAdapter`` ``implements OutputConverter<Object, Map<String, ?>>`` but it does not in 0.9.78. Is there a replacement class? Or do we need to implement our own?

**Comment by kaqqao** [comment]
`ObjectScalarAdapter` has been removed, indeed, but all that line does is _dropping_ the `ObjectScalarAdapter`. So just remove the line :)

**Comment by kaqqao** [comment]
Would be funny if you implemented your own replacement solely for the purpose of dropping it :)

**Comment by efenderbosch** [comment]
I may or may not have already done that while waiting for a reply...

Thanks!
