### ISSUE TITLE
Reactive Support

### ISSUE THREAD

**Issue by cmdavinder** [leangen/graphql-spqr#185]
Hi there,

I am wondering if there are any plans for Reactive support for this library? 

All methods of DefaultGraphQLController are currently blocking. 

Thanks.

**Comment by kaqqao** [comment]
Yes, it is on the roadmap!
But would you mind opening an issue on the starter project instead of this one (the core library)?

**Comment by cmdavinder** [comment]
That's great! Thanks for the update Bojan. I will open an issue on the starter project.
