### ISSUE TITLE
RequestHeader for get headers in query

### ISSUE THREAD

**Issue by alexander171294** [leangen/graphql-spqr#186]
Hi!, I trying to get header user agent and another params.

I try this:
```
@GraphQLQuery(name = "getByCode")
	public UserDTO getByCode(@GraphQLArgument(name = "code") Date code, @RequestHeader(value="User-Agent") String userAgent) {
		
		
		UserDTO out = new UserDTO();
		return out;
	}
```

And this:
```
@GraphQLQuery(name = "getByCode")
	public UserDTO getByCode(@GraphQLArgument(name = "code") Date code, @ServletRequest request) {
		
		
		UserDTO out = new UserDTO();
		return out;
	}
```

How i can get the headers?

Thanks!

**Comment by kaqqao** [comment]
By default, SPQR Spring Boot Starter will use `DefaultGlobalContext` which contains the original request, as you have found out.

You can inject the context using `@GraphQLRootContext`:

```java
public ResponseDTO buscoYOfrezco(
			@GraphQLArgument(name = "busco") String busco, 
			@GraphQLArgument(name = "ofrezco") String ofrezco,
			@GraphQLRootContext DefaultGlobalContext context
			) {
...
}
```

You can also register a custom `ArgumentInjector` that would recognize Spring annotations like `@RequestHeader`. Take a look at the context injector for inspiration.

SPRQ Spring module will eventually have this built-in, but it's easily added manually as well.

**Comment by alexander171294** [comment]
Thanks for the info.

**Comment by dguduguntla** [comment]
The `DefaultGlobalContext` doesn't seem to have `getServletRequest()` method from version `0.0.4` of Spring Boot starter.  What is the best way to access request header value?

**Comment by kaqqao** [comment]
@dguduguntla The method is now called `getNativeRequest()` to align the naming across the implementations.

**Comment by kaqqao** [comment]
Yes, that would be correct.
You can also create a custom `ArgumentInjector` to e.g. use Spring's `@RequestHeader` annotation for the same purpose.
But, since this is about authorization, the best place to implement such concerns is actually in a `ResolverInterceptor`. See [this test](https://github.com/leangen/graphql-spqr/blob/graphql-spqr-v0.9.9/src/test/java/io/leangen/graphql/InterceptorTest.java#L34) for an example.
