### ISSUE TITLE
Schema Stiching

### ISSUE THREAD

**Issue by cmdavinder** [leangen/graphql-spqr#190]
Hi there, 

I am wondering if there is a way to perform Schema Stitching with SPQR similar to what Apollo GraphQL Tools offers - 
https://www.apollographql.com/docs/graphql-tools/schema-stitching.html

Just wanted to open this one up to ask if there is a plan to add a feature like this. If it is possible to implement Schema Stiching with current state of SPQR library, then I'd appreciate some guidelines as to how to go about it, so that I can work on it myself.

**Comment by kaqqao** [comment]
There's a couple of different efforts I'm aware of right now, but not sure how they relate to graphql-tools way of doing it.

* [Nadel](https://github.com/graphql-java/nadel), by graphql-java team, but it's still in an experimental alpha kind of stage.

* [graphql-braid](https://github.com/atlassian/graphql-braid) by Atlassian. Don't know much about this one except that it exists.

As for SPQR, stitching isn't really in the scope of this specific project, as this core library is about generating a schema from Java. But, the idea behind stiching is to connect _any_ GraphQL schema with any other, regardless of the way it was created. So any of the libraries mentioned above, or any future one should have no issue working with SPQR generated schemas.

That said, I'd like to eventually create a separate project around stiching as I have my own ideas on how it can be done to make best use of SPQR features. But that of course is still just a distant plan...

**Comment by cmdavinder** [comment]
Thanks. I wanted to pick up your brain on this. Good to know there are some projects out there trying to solve this problem. I feel this feature will definitely be needed by GraphQL Java community. 

Can I close this ticket then if you feel schema stitching will never be a part of SPQR?

**Comment by kaqqao** [comment]
Yup, I'd say close this one.
If I start implementing stitching, it will be in a separate module (like e.g. the Spring Starter module currently is).
