### ISSUE TITLE
Mutation @GraphQLArgument appending "Input" to type name 

### ISSUE THREAD

**Issue by cmdavinder** [leangen/graphql-spqr#191]
Hi there, 

I want to use a custom separate custom type as input for create/update Mutations on main domain object. Looks like SPQR is automatically appending "Input" at the end of the input type while generating schema. 

To clarify the problem. Here is what I am doing. 

Resolver method.

`    @GraphQLMutation(name = "createDiscussion")
    public Discussion createDiscussion(@GraphQLArgument(name = "discussionInput") final DiscussionInput discussionInput) {
        return discussionService.createDiscussion(discussionInput);
    }
`

`
//Getter
//Setter
class DiscussionInput {

    @GraphQLNonNull
    private String title;

    @GraphQLNonNull
    private String description;

    @GraphQLNonNull
    private Category category;

    @GraphQLNonNull
    private DiscussionSchedule schedule;

}
`

SPQR generated schema looks like below for this mutation -

`createDiscussion(discussionInput: DiscussionInputInput): Discussion
`

Discussion.java  class has many other properties e.g.  viewsCount, likesCount, etc. that I do not want clients to modify via create/update mutation on Discussion.  

Is there a way to remove extra "Input"?  

I tried > @GraphQLType(name = "DiscussionInput") on DiscussionInput class but it didn't solve the problem.

**Comment by cmdavinder** [comment]
I renamed it to something else without "Input" at the end. 

Thanks.

**Comment by kaqqao** [comment]
Btw, SPQR will usually figure out if there's a name collision and warn you, so it's not _as dramatic_ as I made it sound. But close ;)
