### ISSUE TITLE
Can't serialize value (status) : Invalid input for Enum 'Status'. Unknown value 'pendingPayment

### ISSUE THREAD

**Issue by Maclaon** [leangen/graphql-spqr#193]
how should i set some annotation on a inner enum type field of a class? 
```Java
public class Order {
	
        public enum Status {
		pendingPayment,
		pendingReview,
		pendingShipment,
	}

        // some other fields
        ... ...

        private Order.Status status; 
}
```

but, when post a query, it result 'Invalid input for Enum 'Status'. Unknown value 'pendingPayment'

**Comment by kaqqao** [comment]
Inspect the generated schema. What does the GraphQL enum look like? That may give a clue.

**Comment by Maclaon** [comment]
@kaqqao it may be [51](https://github.com/leangen/graphql-spqr/issues/51) cause my problem. how should i register  a custom TypeInfoGenerator in 0.9.8 for that i can not find `withMetaDataGenerator` method. below is my code:
 ```Java
    @PostConstruct
    private void graphqlControllerInit() {
        GraphQLSchema schema = new GraphQLSchemaGenerator()
                .withResolverBuilders(
                        //Resolve by annotations
                        new AnnotatedResolverBuilder())
                .withOperationsFromSingletons(goodsGraphqlService,
                        adPositionGraphqlService)
                .withTypeTransformer(new DefaultTypeTransformer(true, true))
                .withOperationBuilder(new DefaultOperationBuilder(DefaultOperationBuilder.TypeInference.LIMITED))
                .withValueMapperFactory(JacksonValueMapperFactory.builder().build())
                .generate();
        graphQL = GraphQL.newGraphQL(schema).build();
    }
```

**Comment by Maclaon** [comment]
i set `GraphQLType` annotation with all inner fields with same name in different class according to [Error with two classes with the same name in different packages](https://github.com/leangen/graphql-spqr/issues/51) that solves my problem！
