### ISSUE TITLE
How to register GraphQLApi bean that has Spring Transactional annotation

### ISSUE THREAD

**Issue by xiuwyang** [leangen/graphql-spqr#195]
Hi,

When I was trying to register a query bean that is annotated with Spring `@Transactional` to the scheme generator, came across this issue

```
io.leangen.graphql.metadata.exceptions.TypeMappingException: The registered object of type com.xx.web.query.UserQuery$$EnhancerBySpringCGLIB$$67931e06 appears to be a dynamically generated proxy, so its type can not be reliably determined. Provide the type explicitly when registering the bean. For details and solutions see https://github.com/leangen/graphql-spqr/wiki/Errors#dynamic-proxies
```

After looking at that linked documentation, and followed the solution provided on the documentation, still having the same issue, what am I doing wrong here?

UserQuery:
```
@GraphQLApi
@Component
@Transactional
public class UserQuery {
}
```

Schema generator:

```
 GraphQLSchema schema = new GraphQLSchemaGenerator()
            .withResolverBuilders(new AnnotatedResolverBuilder())
            .withOperationsFromSingleton(userQuery, UserQuery.class)
            .withValueMapperFactory(new JacksonValueMapperFactory())
            .generate();
```

Thank you.

**Comment by kaqqao** [comment]
This is an unfortunate limitation of the current version, but will be fixed in the next release.

Please open Spring Starter related issues in that project in the future.

**Comment by xiuwyang** [comment]
@kaqqao Thank you for the reply, sorry for opening this in the wrong project. When is the next release cut?

**Comment by kaqqao** [comment]
No hard deadlines as the project is volunteer work only... But I hope to release a new version by the end of this week.

**Comment by kaqqao** [comment]
@ssokeye Yes. Are you still having trouble?
