### ISSUE TITLE
Unresolvable dependencies in the POM

### ISSUE THREAD

**Issue by TiGz** [leangen/graphql-spqr#2]
Hi,

I'd really like to try this out in a new project but there are some custom dependencies in the POM (snapshot and also a custom version of the graphql library) that I don't have access to.

        <dependency>
            <groupId>io.leangen.geantyref</groupId>
            <artifactId>geantyref</artifactId>
            <version>1.1.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java</artifactId>
            <version>LEANGEN</version>
        </dependency>

Would it be possible to resolve those or offer a published binary? :0)

Many thanks!

Adam

**Comment by BaldyLocks** [comment]
Hi TiGz,
We're glad that you're interested in giving SPQR a go.
This is still not a release so we didn't switch to maintaining stable dependencies only yet. Probably in the next month when we release we'll switch to maintaining a stable master for releases.
As for the dependencies it should be safe to use released:
<dependency>
    <groupId>io.leangen.geantyref</groupId>
    <artifactId>geantyref</artifactId>
    <version>1.1.1</version>
</dependency>
which is on the central now.

But the graphql-java fork artifact is still not published anywhere, fastest solution would be to build it yourself and install it in your local repo, and we were also planing to put it on bintray in the next couple of days, maven central is a bit more complicated matter.

Hope this helps for now and we'll try to keep you updated.
Maybe Bojan (kaqqao) has more to add tomorrow.

Cheers,
Milos

**Comment by kaqqao** [comment]
This project is no longer depending on the forked version of graphql-java so the build issue should be solved. Currently, it depends on their nightly because we need some of the unreleased fixes. Once the next stable version of graphql-java is released, we will finally stabilize the dependencies.

@TiGz Can you confirm the build is now working for you?
