### ISSUE TITLE
Spring Security @PreAuthorize

### ISSUE THREAD

**Issue by Dave2605** [leangen/graphql-spqr#20]
Is there way to use spring security annotations on methods marked with @GraphQLQuery or @GraphQLMutation ?
graphql-spqr throwing and exception that it can't use dynamic proxies.

**Comment by string01** [comment]
Can you post a simple example of how you are applying Spring Sec. ? Also, the exception/trace being thrown. .
-d

**Comment by Dave2605** [comment]
It's again my fault, there is a solution for these case here
https://github.com/leangen/graphql-spqr/wiki/Errors
