### ISSUE TITLE
Support for schema and client directive mapping

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr#200]
SPQR should enable registration of custom schema and client directives, where _schema directives_ are directives on schema elements, such as types, field definitions etc and _client directives_ are directives on query elements, such as fields, fragments etc.

Since SPQR generates the schema from Java, the benefit of schema directives are questionable, as regular Java constructs such as annotation can be used seamlessly to provide any needed meta-data. Still, directives can sometimes be preferable as they are language-neutral GraphQL concepts (e.g. if the team also maintains a Node.js GraphQL server, and wishes to keep the implementations as similar as possible).

Client directives, on the other hand, have no alternative and are useful in many scenarios (basically whenever the client needs to provide some meta-data in addition to the query). SPQR should have a convenient way to map custom client directives and inject their deserialized values into the resolver methods.

## Adding custom directives

To customize the way directives are mapped, a user can register an implementation of `DirectiveBuilder` via `GraphQLSchemaGenerator#withDirectiveBuilder`.

There is an annotation-driven implementation `AnnotatedDirectiveBuilder` already provided, that works in a similar fashion to other default SPQR components.

## Schema directives

Any custom annotation meta-annotated with `io.leangen.graphql.annotations.types.GraphQLDirective` will be mapped as a directive on the annotated element.

E.g. imagine a custom annotation `@Auth(requiredRole = "Admin")` used to denote access restrictions:

```java
@GraphQLDirective //Should be mapped as a GraphQLDirective
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD}) //Applicable to methods
public @interface Auth {
        String requiredRole();
}
```

If a resolver method is then annotated with `@Auth`:

```java
@GraphQLMutation
@Auth(requiredRole = {"Admin"})
public Book addBook(Book newBook) { ... }
```

The resulting GraphQL field fill look like:

```graphql
type Mutation {
  addBook(newBook: BookInput): Book @auth(requiredRole : "Admin")
}
```

That is to say the `@Auth` annotation got mapped to a directive, due to the presence of `@GraphQLDirective` meta-annotation.

## Client directives

To register a client directive, `GraphQLSchemaGenerator#withAdditionalDirectives(java.lang.reflect.Type...)` should be used.

The given types will then be mapped as additional directives.

E.g. for a class such as:

```java
public static class Interrupt {
    // Public field used only to keep the example brief. A regular property would behave the same.
    public int after;
}
```

registered via `generator.withAdditionalDirectives(Interrupt.class)`, a client would be able to use the `@interrupt` directive:

```graphql
{
    books(searchString: "Monkey") @interrupt(after: 500) {
        title
    }
}
```

To customize the directive name, valid location etc, use the same `io.leangen.graphql.annotations.types.GraphQLDirective`:

```java
@GraphQLDirective(name = "timeout", locations = Introspection.DirectiveLocation.FIELD)
public static class Interrupt {
    @GraphQLInputField(name = "afterMillis") //Customize the fields as usual
    public int after;
}
```

Now the directive is called `@timeout`, is only applicable to a field and has an argument called `afterMillis`:

```graphql
{
    books(searchString: "Monkey") @timeout(afterMillis: 500) {
        title
    }
}
```

Now, to get a hold of the value provided by the client, use `@io.leangen.graphql.annotations.GraphQLDirective` (**different annotation than the one used to customize the mapping**):

```java
@GraphQLQuery
public List<Book> books(String searchString, @GraphQLDirective Interrupt timeout) {
    System.out.println(timeout.after); //Prints "500"
    ...
}
```

If the same directive is present multiple times, e.g.:

```graphql
query Books @timeout(afterMillis: 10) {
    books(searchString: "monkey") @timeout(afterMillis: 5) {
        id 
    }
}
```

The value injected by `@GraphQLDirective Interrupt timeout` will be the most specific one (the one on the field, with `afterMillis: 5` in this case).

It is also possible to specify the location for the directive value to be picked from:

```java
@GraphQLQuery
public List<Book> books(String searchString, @GraphQLDirective(locations = Introspection.DirectiveLocation.QUERY) Interrupt timeout) {
    System.out.println(timeout.after); //Prints "10", as provided on the query level
    ...
}
```

But it is also possible to inject all the values:

```java
@GraphQLQuery
public List<Book> books(String searchString, @GraphQLDirective List<Interrupt> timeouts) {
    System.out.println(timeouts); //Prints "[5, 10]". The most specific value goes first.
    ...
}
```

The same rules apply if there are multiple directives of the same type on the same level.

In some edge cases, it might be necessary to specify the name of the directive when injecting its value. E.g.

```java
@GraphQLQuery
public List<Book> books(String searchString, @GraphQLDirective(name = "timeout") Object timeouts) {
    ...
}
```
The explicit name is required because it's impossible to deduce anything from the `Object` type.

**Comment by xf564246963** [comment]
it does not support field.

`query Books {
    books(searchString: "monkey") {
        id @timeout(afterMillis: 5) 
    }
}`

`@GraphQLQuery
public List<Book> books(String searchString, @GraphQLDirective List<Interrupt> timeouts) {
    System.out.println(timeouts); //Prints null
    ...
}`

@GraphQLDirective timeouts 
print out null

how does it support @GraphQLDirective to get field?

**Comment by xf564246963** [comment]
it does not support field.

`query Books {
    books(searchString: "monkey") {
        id @timeout(afterMillis: 5) 
    }
}`

`@GraphQLQuery
public List<Book> books(String searchString, @GraphQLDirective List<Interrupt> timeouts) {
    System.out.println(timeouts); //Prints null
    ...
}`

@GraphQLDirective timeouts 
print out null

how does it support @GraphQLDirective to get field?
