### ISSUE TITLE
@Defer and Apollo Client

### ISSUE THREAD

**Issue by frieck** [leangen/graphql-spqr#202]
Hello!
Thanks for this awesome Library!

I have a question: Is it possible to implement a resolver that uses the **defer** directive and use it with Apollo GraphQL client?

Here is what I'm trying to achieve: Have a query that loads some information and with this Information I might have a lot of other appended data (for instance images and other stuffs). I don't need all the information at once, so I'm planning to use **defer**  and "lazy load" the heavy part.
The server is built with Spring Boot and I'm using Annotations, here is an example:
```java
@GraphQLQuery(name = "userInformation")
public List<UserInformation> getUserInformation(@GraphQLArgument(name = "userIDs") final Set<Long> userIds) {
    return this.userRepository.getUsers(userIds);
}

@GraphQLSubscription(name = "userData") // Need to be something related to defer?!
public Publisher<UserData> getUserData(@GraphQLContext UserInformation userInformation) {
    // load user data and return it as a Publisher???
}
```

The query will be something like this:
```graphql
query {
  userInformation(userIDs: [1, 2, 3]) {
    userName
    age
    email
    userData @defer {
      avatar
  }
}
```

Can you guys help me with that?
Thanks!

**Comment by kaqqao** [comment]
The support for `@defer` is coming from graphql-java itself and it currently doesn't comply with Apollo's semantics. There's not much for SPQR here, as this touches the core of how a query is executed. So the only thing I can tell you is to follow [this issue in graphql-java](https://github.com/graphql-java/graphql-java/issues/1210) for updates.

**Comment by soyoh** [comment]
Hey! first of all, thanks for this library it is awesome.

instead of opening a new thread, is it possible to upgrade `graphql-java` dependency? looks like the `@defer` implementation was merged https://github.com/graphql-java/graphql-java/pull/1221 couple of days ago in v 0.13

**Comment by kaqqao** [comment]
@soyoh In general, it's not advisable to upgrade graphql-java as almost every version contains breaking changes, which means SPQR's behavior will be unpredictable. v13 in specific contains a couple of breaking ones, so read through them if and they don't sound pertinent to your case, you can try upgrading at your own risk and _I think_ nothing will majorly spoil your day.
Either case, I'm already working to upgrade SPQR, so there should a new graphql-java 13 based version coming out soon.

**Comment by soyoh** [comment]
Thanks for the explanation. as I dont know the internals of SPQR that well, I'll until the next release, instead of braking things :sweat_smile:  cheers.
