### ISSUE TITLE
Fields ordering in input objects

### ISSUE THREAD

**Issue by piotr-swierczynski** [leangen/graphql-spqr#206]
Hi! Thanks once again for this almighty library! Is there any straight forward way of ordering fields in schema description, when it comes to input objects? My issue comes from the fact, that in gettable object, we are able to set order by `@GraphQLType(fieldOrder = {"id", "firstName"})`, but this doesn't affect input object type. Is there a simple way of doing field ordering for input objects?

**Comment by piotr-swierczynski** [comment]
Forgot to mention. I'm using SPQR 0.9.7.

**Comment by kaqqao** [comment]
I think this currently left to Jackson/Gson completely. But I agree that there should be a way to control it.

**Comment by kaqqao** [comment]
Oh, forgot to say: thanks for the kind words 😊

**Comment by piotr-swierczynski** [comment]
Ok, thanks for response. For now, I'm closing the issue. But, when the time comes, it would be great to contribute with this little feature. Can't wait for doc.

**Comment by kaqqao** [comment]
Let's keep it open, so we don't lose track of the feature.

**Comment by kaqqao** [comment]
Superceded by  #279
