### ISSUE TITLE
Using Spring devtools and 0.9.8 breaks checkUniqueness

### ISSUE THREAD

**Issue by pepijno** [leangen/graphql-spqr#211]
Using Spring boot `2.0.7.RELEASE` with the spring-boot-devtools and spqr `0.9.8` breaks `checkUniqueness` of `Validator`.

The `compare` method of the `NonNullMapper` (which is used by `GraphQLSchemaGenerator` which in turn is called by the Validator) checks if two classes are equal. However, using spring-boot-devtools, some instances of a class have the `RestartClassLoader` as classloader while other instances of the same class have the `AppLoader` as classloader. Therefore, the compare method says the two classes are not equal leading to a lot of warnings at startup and also unexpected exceptions (the one from #51).

In version `0.9.7` this problem was not encountered.

**Comment by kaqqao** [comment]
Have you perhaps tried upgrading ClassGraph version as in #51? Not sure what changed here since 0.9.7 apart from FastClasspathScanner -> ClassGraph upgrade. Have you maybe investigated yourself (since you already have the setup ready)?

**Comment by pepijno** [comment]
I wasn't able to reproduce the issue myself for now, so I will close this issue.
