### ISSUE TITLE
How to override DataFetcherExceptionHandler?

### ISSUE THREAD

**Issue by thanhpd56** [leangen/graphql-spqr#219]
I want to customize message of each error, when exception occurred.
Now the message like this: Exception while fetching data (/login) : {message}"
However, i want message to some thing else without "Exception while fetching data"
I use graphql-spqr-spring-boot-starter.
Thanks.

**Comment by kaqqao** [comment]
There's a couple of possibilities. To override the `DataFetcherExceptionHandler`, you have to override the execution strategy when assembling the `GraphQL` object:

```java
GraphQL.newGraphQL(schema)
              .queryExecutionStrategy(new AsyncExecutionStrategy(new CustomExceptionHandler()))
              .mutationExecutionStrategy(new AsyncSerialExecutionStrategy(new CustomExceptionHandler()))
              .build();
```

Since you're using the starter, turn the above into a bean:

```java
@Bean
public GraphQL graphQL(GraphQLSchema schema) {
    return GraphQL.newGraphQL(schema)
            .queryExecutionStrategy(new AsyncExecutionStrategy(new CustomExceptionHandler()))
            .mutationExecutionStrategy(new AsyncSerialExecutionStrategy(new CustomExceptionHandler()))
            .build();
}
```

This is the way to go if you want to customize the exception handling globally. If you just want to provide your own error in one specific location (or provide a partial result), return a `DataFetcherResult` from a resolver:

```java
@GraphQLQuery
public DataFetcherResult<List<Book>> findBooks(String keywords) {
    try {
        return new DataFetcherResult<>(db.findBooks(keywords), Collections.emptyList());
    } catch (Exception e) {
        List<GraphQLError> customErrors = buildErrorsFromException(e);
        return new DataFetcherResult<>(nullOrPartialResult, customErrors);
    }
}
```

**Comment by vishalaestro** [comment]
how can i add the custom error according to the specification, because it return both error and data object even during exception case, below is my code
`public class CustomDatafetcherExceptionHandler implements DataFetcherExceptionHandler {

	@Override
	public void accept(DataFetcherExceptionHandlerParameters handlerParameters) {
		  	Throwable exception = handlerParameters.getException();
	        SourceLocation sourceLocation = handlerParameters.getField().getSourceLocation();
	        ExecutionPath path = handlerParameters.getPath();
	        CustomGraphQLError error = new CustomGraphQLError(path, exception, sourceLocation);
	        handlerParameters.getExecutionContext().addError(error);
	}

}
`

**Comment by HelLViS69** [comment]
You can define your own CustomException and catch it in the CustomGraphQLError


```
@Bean
public GraphQL graphQL(GraphQLSchema schema)
{
	return GraphQL.newGraphQL(schema)
			.queryExecutionStrategy(new AsyncExecutionStrategy(new CustomExceptionHandler()))
			.mutationExecutionStrategy(new AsyncSerialExecutionStrategy(new CustomExceptionHandler()))
			.build();
}

private static class CustomExceptionHandler implements DataFetcherExceptionHandler
{
	@Override
	public void accept(DataFetcherExceptionHandlerParameters params)
	{
		Throwable exception = params.getException();
		SourceLocation sourceLocation = params.getField().getSourceLocation();
		ExecutionPath path = params.getPath();

		CustomGraphQLError error = new CustomGraphQLError(path, exception, sourceLocation);
		params.getExecutionContext().addError(error);
	}

	private static class CustomGraphQLError extends ExceptionWhileDataFetching
	{
		private CustomGraphQLError(ExecutionPath path, Throwable exception, SourceLocation sourceLocation)
		{
			super(path, exception, sourceLocation);
		}

		@Override
		public Map<String, Object> getExtensions()
		{
			Throwable exception = getException();

			if (exception instanceof CustomException) {
				String message = ((CustomException) exception).getMessage();

				Map<String, Object> attributes = new HashMap<>();
				attributes.put("message", message());

				return attributes;
			}

			return null;
		}
	}
}
```
