### ISSUE TITLE
Support for graphql-java v6

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr#22]
graphql-java had a major release that brings a ton of new features and some breaking changes.
To properly support it, grahql-spqr needs to:

1. support v4 with the current feature-set
2. enable usage of the new features of v4 from within spqr itself

I'll probably split this issue into sub-issues when I start working on it.

**Comment by heruan** [comment]
Hope #27 may be a good starting point 😉

**Comment by brettcooper** [comment]
Any update on this?  We had to manually bump graphql-java to 4.0 because enum types were not properly returning with a GraphQL query and in 4.0, there is a fix for that.

**Comment by heruan** [comment]
This should be updated to "Support for graphql-java v6", I suppose.

**Comment by kaqqao** [comment]
Thankfully, there's very few breaking changes, so the first commit adding v6 compatibility is in master (based on @heruan 's v4.2 PR). `CompletableFuture`s should work as expected.
I'm now working on supporting subscriptions.

**Comment by heruan** [comment]
> I'm now working on supporting subscriptions.

This is the one! 👍

**Comment by kaqqao** [comment]
Subscriptions should now work :) It was a pretty tiny change, really.
I want to refactor the code around it somewhat, to avoid the duplication but, in general, the basic support is complete.

The resolver method *has to return a `Publisher`*, and by default you expose it via the new `@GraphQLSubscription` annotation (other strategies are applicable as usual).
There's [a minimal test](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/SubscriptionTest.java) showcasing the usage (with more coming), but [graphql-java-subscription-example](https://github.com/graphql-java/graphql-java-subscription-example) is much more comprehensive for that purpose.

I could now really use some brainstorming and opinions on what should SPQR provide around subscriptions. Is the basic support currently available all? Could it do more to support common usage?

**Comment by oleg-savko** [comment]
Hi, Im very exciting for supporting subscription for spqr (and supporting graphql-java v6). 
Can u tell please, when u roughly speaking plan to release it?
And also, can i found snapshot versions somewhere in maven repositories?

**Comment by kaqqao** [comment]
I'm planning a release with subscriptions tomorrow (0.9.5).
I currently do not deploy SNAPSHOTs anywhere, but could start if it makes people's lives easier.

Feature wise, this is pretty much it for v1.0.0. I'm only planning to fix bugs, refactor some things and add docs.

**Comment by heruan** [comment]
SNAPSHOTs would be useful to test your commits before releasing, without the need of a local copy of the repo. Great to know we are approaching v1.0.0! 🎉

**Comment by kaqqao** [comment]
Closing this one as v0.9.5 has been out for a while.
