### ISSUE TITLE
How to use multiple types?

### ISSUE THREAD

**Issue by alturkovic** [leangen/graphql-spqr#220]
I have searched through issues, tests and examples but cannot find an example on how to use multiple types. I have an abstract class `TaskRecurringDescription` and several implementations, one of which is `TaskRecurringDescriptionCron`.

My service looks like (Spring `org.springframework.data.domain.Page`, not relay):
```
@Service
@GraphQLApi
@AllArgsConstructor
public class TaskRecurringDescriptionService {
  private final TaskRecurringDescriptionRepository repository;

  @GraphQLQuery
  public Page<TaskRecurringDescription> taskRecurringDescriptions(@GraphQLArgument(name = "page", defaultValue = "0") final int page,
                                                                  @GraphQLArgument(name = "size", defaultValue = "10") final int size,
                                                                  @GraphQLArgument(name = "direction", defaultValue = "\"ASC\"") final Direction direction,
                                                                  @GraphQLNonNull @GraphQLArgument(name = "properties", defaultValue = "[\"id\"]") final String... properties) {
    return repository.findAll(PageRequest.of(page, size, direction, properties));
  }
}
```

Then, I try to execute the following query: 
```
{
  taskRecurringDescriptions {
    content {
      id
      ... on TaskRecurringDescriptionCron {
        cron
      }
    }
  }
}
```

I am getting error message: `Validation error of type UnknownType: Unknown type TaskRecurringDescriptionCron @ 'taskRecurringDescriptions/content`.

What am I doing wrong? How can I get GraphQL to pickup implementations of `TaskRecurringDescription` and recognize them?

**Comment by kaqqao** [comment]
If `TaskRecurringDescription` is an interface, you can add `@GraphQLInterface(name="TaskRecurringDescription", implementationAutoDiscovery=true)`. Autodiscovery by default uses ClassGraph to scan the classpath. You can provide a custom `ImplementationDiscoveryStrategy` if you wish.

**Comment by kaqqao** [comment]
That is if I got you right 😶 You want to automatically register the implementing types, right?
