### ISSUE TITLE
Serialize Enum type using value instead of name

### ISSUE THREAD

**Issue by valasatava** [leangen/graphql-spqr#222]
Hi! I'm new to this library and GraphQL in general. I seek for an advice on how to go about handling Enums. We use the graphql-spqr library to convert our POJOs into a GraphQL schema that is then passed to the servlet (from graphql-java-servlet library). For Enums we face an issue - they get serialized with names. Is there a way to make use of values so users see them in JSON payload and not Enums names? Thank you in advance!

**Comment by valasatava** [comment]
I have tried to override a configuration of objectMapper in graphql servlet to use `objectMapper.enable(SerializationFeature.WRITE_ENUMS_USING_TO_STRING); ` but this didn't help.

**Comment by valasatava** [comment]
Thank you for the prompt response! It seems that custom type mapper won't solve my issue. Just a pet example here:
`public enum MyTypeEnum {
   _1_VALUE("first value"),
    _2_VALUE("second value");
}`

I'd like the client get:
`{
  "data": {
    "my_type": "first value"
}`

but what currently goes through is:
`{
  "data": {
    "my_type": "_1_VALUE"
}`

GraphQL schema won't tolerate arbitrary string as Enum name but that's okey. What I want is that client receives a corresponding to name value when queries a GraphQL endpoint. Is there a way to achieve this? I will appreciate any comments or thoughts.

**Comment by valasatava** [comment]
After considering different approaches, we have decided to change a tack. Instead of exposing fields as 'enums' to the client in GQ API we want go with exposing them as 'scalars'. We still want to have a server side validation. Is it possible to map Java 'enums' to GraphQL 'scalars' in the process of schema generation?

**Comment by kaqqao** [comment]
Yes, you fully control the mapping of each type (class).
As noted above, you can pre-empt (or fully replace) the default `EnumMapper` with a custom one that will map some or all enums the way you like.
See other `TypeMapper` implementations for inspiration.

Once you have a custom mapper implement it, register it with:

```java
// To fully replace the built-in mapper
generator.withTypeMappers((conf, current) -> current.replace(EnumMapper.class, new CustomEnumMapper()))
```
or
```java
// To pre-empt the built-in mapper with your own
// Useful in case you e.g. only want it to handle certain but not all enums
generator.withTypeMappers((conf, current) -> current.insertBefore(EnumMapper.class, new CustomEnumMapper()))
```

**Comment by kaqqao** [comment]
Since there has been no response in a while, I take it you solved the problem, so I'll close this issue.
If not, feel free to reopen it.
