### ISSUE TITLE
Runtime arguments with spqr

### ISSUE THREAD

**Issue by bhaskar-p7** [leangen/graphql-spqr#225]
I am using graphql spqr 0.9.9 version. When I request with static data it is working fine. But if I pass runtime arguments it is complaining like "Variable 'id' has coerced Null value for NonNull type 'Long!'", I am using apollo client to request spring boot server. Event graphiql I am getting the same error. Stuck with this for a long time. I am not getting without spqr i.e. It is working if I am using plain graphql. Below is the screen shot.

![capture](https://user-images.githubusercontent.com/46965527/51612067-517d7a80-1ee6-11e9-93fd-3f73ccae2efe.PNG)

**Comment by bhaskar-p7** [comment]
Here is my controller code : 
@RestController
public class TestController{

	private final GraphQL graphQL;
	private static Logger logger = LoggingUtility.getLogger();

	public IntermediaryAgreementController(AgreementService agreementService) {
		GraphQLSchema schema = new GraphQLSchemaGenerator()
						// .withResolverBuilders(new AnnotatedResolverBuilder())
						.withOperationsFromSingleton(agreementService, AgreementService.class)
						.withValueMapperFactory(new JacksonValueMapperFactory()).generate();

		
		graphQL = GraphQL.newGraphQL(schema).build();
	}

	@CrossOrigin(origins = "*", allowedHeaders = "*")
	@PostMapping(value = "/graphql", consumes = MediaType.APPLICATION_JSON_UTF8_VALUE, produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
	@ResponseBody
	public Map<String, Object> graphql(@RequestBody Map<String, Object> request, HttpServletRequest raw) {
		logger.info("request " + request);
		logger.info("raw " + raw.getQueryString());
		logger.info("graphQL " + graphQL);

		ExecutionResult executionResult = graphQL.execute(ExecutionInput.newExecutionInput()
						.query(String.valueOf(request.get("query"))).context(raw).build());
		return executionResult.toSpecification();
	}
}

**Comment by fhoner** [comment]
Not sure about this, but you probably have to pass the variables from your RequestBody to the ExecutionInput.
```
Map<String, Object> variables = extractFromRequest();
 ExecutionInput executionInput = ExecutionInput.newExecutionInput()
                .query(request.get("query"))
                .variables(variables)
    ...
```

**Comment by bhaskar-p7** [comment]
request.get("variables") is returning json string. I converted that into map and passed to variables. It worked for me. I am not sure why spqr is not taking care of it.

**Comment by fhoner** [comment]
Thats outside of the scope of spqr I would say. How should the graphql instance know your query, operation and variables if not passing them through?
The spring boot starter project may handle this for you (?), I dont know.

**Comment by kaqqao** [comment]
Exactly as @fhoner said. SPQR can't help you here because you're not using SPQR at that point.
It's your custom code that is handling the web calls.

If you want full web scaffolding, look at SPQR Spring Boot Starter.

**Comment by bhaskar-p7** [comment]
I am just wondering how are my variables executed when I remove spqr annotations libararies?

**Comment by kaqqao** [comment]
@bhaskar-p7 I really can't tell without seeing your setup. Are you using some other library too? There's nothing in Graphql-java by itself to deserialize the input values or handle web. So without SPQR you're either doing it yourself (which you'd know) or using something else. How do assemble the schema when not using SPQR?

**Comment by bhaskar-p7** [comment]
Here is my application.properties from spring boot.

> graphql:
>  tools:
>         schema-location-pattern: "**/*.graphqls"
>         introspection-enabled: true
>       servlet:
>            mapping: /graphql
>            enabled: true
>            corsEnabled: true
>            exception-handlers-enabled: true

My schema definations starts like this:
type Query {
     agreement(id: String!): Agreement
}

This is what I have in my controller. AgreementResolver  extends GraphQLQueryResolver.
@Bean
 public AgreementResolver query() {
 return new AgreementResolver();
 }

I am thinking GraphQLQueryResolver is the doing the trick to resolve query with variables.

**Comment by kaqqao** [comment]
You're using [graphql-java-tools](https://github.com/graphql-java-kickstart/graphql-java-tools). This is a completely different library. You shouldn't be mixing the two.
Please ask on that project for further assistance.

**Comment by bhaskar-p7** [comment]
That is correct. Sorry, I could have mentioned that at the first point.
