### ISSUE TITLE
Upgrade version of ClassGraph

### ISSUE THREAD

**Issue by natasha4** [leangen/graphql-spqr#227]
Hi!

Working with graphql-spqr version 0.9.9 I faced the issue that classes marked with annotations `@GraphQLType` and `@GraphQLInterface(name = "name", implementationAutoDiscovery = true)` are not provided as GraphQL types. 

After some investigation I found that my problem connected with `classgraph` library. As it scans the classpath and it does that wrongly in the case when classpath is passed via manifest-file of classpath jar. 
Today I tested the latest version of the ClassGraph `4.6.25` and works properly. I think my problem was fixed by https://github.com/classgraph/classgraph/issues/305.

It would be great to upgrade the library version to the latest.

Thank you!

**Comment by kaqqao** [comment]
Thanks for reporting this! I'll upgrade it for the next release.

**Comment by natasha4** [comment]
Hello @kaqqao !

I checked the latest version 0.9.9 and this still depends on the version 4.6.7 of classgraph.
```
<dependency>
    <groupId>io.github.classgraph</groupId>
   <artifactId>classgraph</artifactId>
   <version>4.6.7</version>
</dependency>
```
So looks like this issue was not closed by the latest release.

**Comment by kaqqao** [comment]
0.9.9 was released months ago... I upgraded in the master branch but have yet to release it. Will add a version label.

**Comment by natasha4** [comment]
@kaqqao Thank you for clarification! Will wait for the next release.
