### ISSUE TITLE
ZoneId in Java as scalar

### ISSUE THREAD

**Issue by ati90ati** [leangen/graphql-spqr#228]
Hello,

In Java we have the `java.time.ZoneId` object and I want to have it as scalar in GraphQL.
So I have this `GraphQLScararType` implementation:

    public class CustomZoneIdType {
    
        public static GraphQLScalarType getScalarType() {
            final Class<ZoneId> type = ZoneId.class;
    
            return new GraphQLScalarType(type.getSimpleName(), type.getSimpleName() + " for datetime",
    
                    new Coercing<ZoneId, String>() {
                        @Override
                        public String serialize(final Object input) {
                            if (input == null) {
                                return null;
                            }
                            return input.toString();
                        }
    
                        @Override
                        public ZoneId parseValue(final Object input) {
                            if (input == null) {
                                return null;
                            }
                            if (input instanceof String) {
                                return ZoneId.of((String) input);
                            }
                            throw new CoercingParseValueException("Invalid input for parsing ZoneId from object");
                        }
    
                        @Override
                        public ZoneId parseLiteral(final Object input) {
                            if (input == null) {
                                return null;
                            }
                            if (input instanceof StringValue) {
                                return ZoneId.of(((StringValue) input).getValue());
                            }
                            throw new CoercingParseValueException("Invalid input for parsing ZoneId from literal");
                        }
                    });
        }
    
    }

Also in the `GraphQLSchemaGenerator` I've registered it like this:

                .withAdditionalTypes(Arrays.asList(
                        CustomZoneIdType.getScalarType())
                )
                .generate();

The problem is that when having the `ZoneId` as a field on an output it works well and the `serialize` method is called well.
But when having it on an input object it is generated as `ZoneIdInput` and I cannot pass a string to it because it requires a map from me:

    "errorDescription": "Could not resolve type id 'ZoneId' as a subtype of [simple type, class java.time.ZoneId]: known type ids = [] (for POJO property 'zoneId')\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.mypackage.MyClass[\"zoneId\"])"

I have `io.leangen.graphql:spqr version 0.9.6`.

Please help me discovering what I'm doing wrong.

Regards,
Attila

**Comment by kaqqao** [comment]
What you want to do is register a custom mapper to handle `ZoneId` class, similar to how `ScalarMapper` handles the other scalars.

```java
public static class ZoneIdMapper extends CachingMapper<GraphQLScalarType, GraphQLScalarType> {

    @Override
    protected GraphQLScalarType toGraphQLType(String typeName, AnnotatedType javaType, OperationMapper operationMapper, BuildContext buildContext) {
        return CustomZoneIdType.getScalarType();
    }

    @Override
    protected GraphQLScalarType toGraphQLInputType(String typeName, AnnotatedType javaType, OperationMapper operationMapper, BuildContext buildContext) {
        return toGraphQLType(typeName, javaType, operationMapper, buildContext);
    }

    @Override
    public boolean supports(AnnotatedType type) {
        // Apply this mapper to ZoneId and its subtypes
        return GenericTypeReflector.isSuperType(ZoneId.class, type.getType());
    }
}
```

Then register the mapper:

```java
generator..withTypeMappers(new ZoneIdMapper())
```

You do not need to call `withAdditionalTypes`, that is only intended for registering interface implementations (when not using auto-discovery) and for reusing types from other schemas.

**Comment by kaqqao** [comment]
Also, 0.9.6 is rather old. Many things have been fixed in the meantime, so please update if possible.

**Comment by ati90ati** [comment]
Thank you for your answer!

I've tried to add the type mapper using the version 0.9.6 but I've got a exception:

    java.lang.NullPointerException: null
            at io.leangen.graphql.generator.OperationMapper.toGraphQLType(OperationMapper.java:171)

I've tried to update to version 0.9.9 and in that version the type mapper worked very well but I have some problems with the graphiql page in the documents side.
I've created a new issue for that, maybe you can highlight what I'm doing wrong: https://github.com/leangen/graphql-spqr/issues/229


I don't know why but I need to add the `SCALAR_SUFFIX` for the ZoneId name:

        final Class<ZoneId> type = ZoneId.class;
        return new GraphQLScalarType(type.getSimpleName() + TypeInfoGenerator.SCALAR_SUFFIX,
                type.getSimpleName() + " for datetime", new ZoneIdCoercing());

Otherwise if I don't add the suffix the application failed to start with this error:

    graphql.AssertException: type ZoneIdScalar not found in schema
            at graphql.Assert.assertNotNull(Assert.java:13)
            at graphql.schema.GraphQLTypeResolvingVisitor.visitGraphQLTypeReference(GraphQLTypeResolvingVisitor.java:42)
            at graphql.schema.GraphQLTypeReference.accept(GraphQLTypeReference.java:45)


So, if I add the suffix and change to version 0.9.9 your answer worked like a charm.
Thank you!

**Comment by kaqqao** [comment]
Ah, registering a custom TypeMapper was needlessly difficult in 0.9.6. You had to re-assemble the entire list of mappers by yourself 😩

The reason why you're getting the error if the name doesn't match what the `TypeInfoGenerator` expects is because that is the name used for caching the types (notice you're extending `CachingMapper`).

You can solve that (and simplify the code) by always returning the exact same static instance from the mapper's `toGraphQLType`. If you do that, you do not have the extend the `CachingMapper` but implement `TypeMapper` directly, and the name won't matter any more.

I'll close this issue as it seems addressed. Feel free to reopen if that conclusion is wrong.
We'll deal with the other issue separately.

**Comment by ati90ati** [comment]
I've adapted my code to your suggestion and it works well now. I don't need the `SCALAR_SUFFIX`.

I'll put here the final code parts, maybe if others will have the same problem this will help out them.

**How to register a custom scalar**
The version used is 0.9.9.
I have my scalar implementation:

    public class CustomZoneIdType {
        static GraphQLScalarType getScalarType() {
            final Class<ZoneId> type = ZoneId.class;
    
            return new GraphQLScalarType(type.getSimpleName(), type.getSimpleName() + " for datetime",
                    new ZoneIdCoercing());
        }
    
        private static class ZoneIdCoercing implements Coercing<ZoneId, String> {
            @Override
            public String serialize(final Object input) {
                if (input == null) {
                    return null;
                }
                return input.toString();
            }
    
            @Override
            public ZoneId parseValue(final Object input) {
                if (input == null) {
                    return null;
                }
                if (input instanceof String) {
                    try {
                        return ZoneId.of((String) input);
                    } catch (final Exception e) {
                        throw new CoercingParseValueException("Invalid input " + input + " for parsing ZoneId from object. " +
                                "Message: " + e.getMessage());
                    }
                }
                throw new CoercingParseValueException("Invalid input for parsing ZoneId from object");
            }
    
            @Override
            public ZoneId parseLiteral(final Object input) {
                if (input == null) {
                    return null;
                }
                if (input instanceof StringValue) {
                    try {
                        return ZoneId.of(((StringValue) input).getValue());
                    } catch (final Exception e) {
                        throw new CoercingParseValueException("Invalid input " + input + " for parsing ZoneId from literal. " +
                                "Message: " + e.getMessage());
                    }
                }
                throw new CoercingParseValueException("Invalid input for parsing ZoneId from literal");
            }
        }
    }

Then I've create static instance for the scalar:

    @UtilityClass
    public class CustomScalars {
        @SuppressWarnings(value = "ConstantName")
        public static final GraphQLScalarType GraphQLZoneId = CustomZoneIdType.getScalarType();
    }

I have the type mapper like this:

    public class ZoneIdMapper implements TypeMapper {
        @Override
        public GraphQLOutputType toGraphQLType(
                final AnnotatedType javaType, final OperationMapper operationMapper,
                final Set<Class<? extends TypeMapper>> mappersToSkip, final BuildContext buildContext) {
            return CustomScalars.GraphQLZoneId;
        }
    
        @Override
        public GraphQLInputType toGraphQLInputType(
                final AnnotatedType javaType, final OperationMapper operationMapper,
                final Set<Class<? extends TypeMapper>> mappersToSkip, final BuildContext buildContext) {
            return CustomScalars.GraphQLZoneId;
        }
    
        @Override
        public boolean supports(final AnnotatedType type) {
            // Apply this mapper to ZoneId and its subtypes
            return GenericTypeReflector.isSuperType(ZoneId.class, type.getType());
        }
    }

And finally in the `GraphQLSchemaGenerator` I just added this row:

                .withTypeMappers(new ZoneIdMapper())

It seems that I don't need to register my scalar in the `withAdditionalTypes` because it is working also only with calling the `withTypeMappers` method and registering the type mapper.
Is there a reason @kaqqao to add the mapper and the GraphQLZoneId in the additional types also?

So yes, this is it with custom scalars :smile: 

Thank you very much @kaqqao for helping me!

**Comment by kaqqao** [comment]
Cool, thanks for sharing the solution! Might help others with custom scalars.

> Is there a reason @kaqqao to add the mapper and the GraphQLZoneId in the additional types also?
Nope, no need. You're doing it correctly :)

Btw, I _think_ the coercing functions are guaranteed to never receive `null`.

**Comment by ati90ati** [comment]
I've updated my comment as you suggested without checking null values. Thank you!

**Comment by Matthias-Walter-Innio** [comment]
Thank you for providing this example! 
Just one question:
You write: 
And finally in the GraphQLSchemaGenerator I just added this row:

But I don't use a GraphQLSchemaGenerator so far. So how can I register my TypeMapper?
Thanks for you help!

**Comment by KushagraBindal** [comment]
Good evening Guys,

I know that this ticket is close, so can I put my comments on this ticket. Please confirm and if this is a violation then I will open a new ticket.

In my case I have applied the above logic and my ZoneId is loaded successfully. But in my case my ZoneId output should contains the rules (ZoneRules) as well which is part of ZoneOffset (extending abstract class ZoneId). But while implementing the logic it is returning id only as the outcome. Can someone please help in extracting the ZoneOffset variables i.e. Rules.

https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html
https://docs.oracle.com/javase/8/docs/api/java/time/ZoneOffset.html
https://docs.oracle.com/javase/8/docs/api/java/time/zone/ZoneRules.html

Please suggest.
