### ISSUE TITLE
GraphiQL Docs error after upgrade from 0.9.6 to 0.9.9

### ISSUE THREAD

**Issue by ati90ati** [leangen/graphql-spqr#229]
Hello,
I've a problem in the Docs section with upgrading the `io.leangen.graphql:spqr` from version 0.9.6 to version 0.9.9.

In the GraphiQL interface at the right side where we have the Docs this error appears:

    Error: SortPropertyInput fields must be an object with field names as keys or a function which returns such an object.
        at invariant (http://localhost:8070/graphiql/js/graphiql.js:21601:11)
        at GraphQLInputObjectType._defineFieldMap (http://localhost:8070/graphiql/js/graphiql.js:25080:31)
        at GraphQLInputObjectType.getFields (http://localhost:8070/graphiql/js/graphiql.js:25070:51)
        at http://localhost:8070/graphiql/js/graphiql.js:26410:27
        at typeMapReducer (http://localhost:8070/graphiql/js/graphiql.js:26422:7)
        at http://localhost:8070/graphiql/js/graphiql.js:26420:22
        at Array.forEach (<anonymous>)
        at http://localhost:8070/graphiql/js/graphiql.js:26411:37
        at typeMapReducer (http://localhost:8070/graphiql/js/graphiql.js:26422:7)
        at typeMapReducer (http://localhost:8070/graphiql/js/graphiql.js:26390:12)

When trying to update to version 0.9.7 I've get the same error for 0.9.7 and 0.9.8 also.

In my code I have an interface:

    @GraphQLInterface(name = "SortProperty")
    public interface SortProperty {
    }

And some implementing enums:

    public enum BillSortProperty implements SortProperty {
        CREATION_DATE,
        PAYMENT_DATE
    }

    public enum BookingSortProperty implements SortProperty {
        START_TIME,
        END_TIME
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public class PageableQuery<T extends SortProperty> implements Serializable {
        private static final long serialVersionUID = 670373833817233556L;
        @GraphQLNonNull
        private PageRequest page;
        @Valid
        private List<SortOption<T>> sortOptions;
    
        public PageableQuery(@GraphQLNonNull final PageRequest page) {
            this.page = page;
        }
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public class SortOption<T extends SortProperty> implements Serializable {
        private static final long serialVersionUID = 7820091265202891945L;
        @NonNull
        private SortDirection sortDirection;
        @NonNull
        private T sortProperty;
    }

I've tried to add an `id` method to `SortProperty` but ti does not help:

    @GraphQLInterface(name = "SortProperty")
    public interface SortProperty {
        default String id() {
            return getClass().getSimpleName();
        }
    }

Also it is not working if I remove the `@GraphQLInterface` annotation from the interface.

Could you please highlight the issue what I'm doing wrong?

Regards,
Attila

**Comment by kaqqao** [comment]
Sorry, there's just way too much going on here for me to follow, with Lombok, Jackson, BeanValidation, interfaces, generics and enums 😱

The error basically just says _something_ is wrong with `SortPropertyInput`. How does that type look in 0.9.6?

Can you put a breakpoint and analyze the generated schema? Inspect the `SortPropertyInput` type especially.

Can you show me the top level query/mutation using `SortProperty` as input? Or even better, can you maybe create a simple runnable example demonstrating the issue?

**Comment by kaqqao** [comment]
I'll try to replicate your issue in the mean time.

GraphiQL gives terrible errors that are not at all helpful... If it's gave a better error I'd know where to look without the need to replicate the problem.

I'm guessing that somehow an invalid type was generated, like an object type with no fields or something like that... See if you can investigate in that direction as well.

**Comment by ati90ati** [comment]
Sorry for the lot of annotations. I added those here to reflect what I exactly have in my code.
You've right. I found out that I have a problem in my code where an invalid type was generated.

So the problematic part was:

    public class BillingPeriodTotalsQuery extends PageableQuery {
        private UUID accountId;
        @Builder
        public BillingPeriodTotalsQuery(final PageRequest page, final UUID accountId) {
            super(page);
            this.accountId = accountId;
        }
    }

In this code I've missed the generic parameter for `PageableQuery`. I think because I've missed the generic GraphQL didn't knows what type to generate for `private List<SortOption<T>> sortOptions;`.


How I found it out?

Actually in the logs I've get a warning but I didn't think that because of this the Docs part in GraphiQL are not working:

    Potential type name collision detected: 'PageRequestInput' bound to multiple types: @com.fasterxml.jackson.annotation.JsonInclude(valueFilter=class java.lang.Void, value=NON_NULL, content=ALWAYS, contentFilter=class java.lang.Void), @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown=true, allowGetters=false, allowSetters=false, value=[]) org.mypackage.PageRequest (loaded by sun.misc.Launcher$AppClassLoader@18b4aac2) and org.mypackage.PageRequest (loaded by sun.misc.Launcher$AppClassLoader@18b4aac2). Assign unique names using the appropriate annotations or override the TypeInfoGenerator. For details and solutions see https://github.com/leangen/graphql-spqr/wiki/Errors#non-unique-type-name. If this warning is a false positive, please report it: https://github.com/leangen/graphql-spqr/issues.

It doesn't help my very much because I didn't realize that it has something to do with my SortProperty error.

I started to remove the `SortProperty` interface and changed the `PageableQuery` class declaration in this:

    public class PageableQuery<T extends Enum> implements Serializable { ...

Then I started the application and it failed to start because this error:

    TypeMappingException: The type of member "setSortOptions" belonging to org.mypackage.BillingPeriodTotalsQuery is missing generic type parameters and can not be mapped.

Than I've tried just to comment the code what was described in the error and the application started and the Docs worked well.

After fixing this problem I succeed to upgrade to 0.9.9 and the GraphiQL Docs are working well.

Thank you very much @kaqqao for your support! I really appreciate it :smile:

**Comment by kaqqao** [comment]
Cool, glad to hear you have it figured out!
