### ISSUE TITLE
Querying null dates cause an exception

### ISSUE THREAD

**Issue by Balderscape** [leangen/graphql-spqr#23]
When issuing queries that contain a Date field. If the date is null, then the query will fail with an exception. I have tracked down the problem to io.leangen.graphql.util.Scalars. In particular the temporalScalar serialize function on line 198 assumes that the input is non null which is wrong. This causes the input.toString() to throw a NullPointerException.

This function should be changed to return null if the input is null, otherwise continue as written.

**Comment by kaqqao** [comment]
Merged your PR, thanks!
