### ISSUE TITLE
Consider removing type name collision check

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr#232]
Unfortunately, the type name collision detection is too unreliable to be useful. It produces way too many false-positives without realistic hope for improvement.

**Comment by 4shotespresso** [comment]
I have a class in my application named com.configureone.model.Order and the GraphQL schema is choosing the org.springframework.Sort$Order object instead.  Both packages are included in my withBasePackages on GraphQLSchemaGenerator.  The resulting schema chooses the Spring class over mine.  Any way around this?

**Comment by kaqqao** [comment]
The bottom line is that each type must have a unique name, and these too likely both end up being called `Order` which causes a collision. The easiest way to resolve it is to give the class you have control over an explicit name (other than `Order`) e.g. via `@GraphQLType`. Another way is to customize `TypeInfoGenerator` and change the way it names these 2 types (this lets you change how the Spring type which you can't annotate gets named). Then register your custom implementation via `geberator.withTypeInfoGenerator`.

**Comment by 4shotespresso** [comment]
Thanks for the suggestions, adding @GraphQLType(name = "CoOrder") allows me to have the correct object wired to the GraphQL schema.  In my case, an Order is something purchased through the application, not related to sorting.  I wouldn't be able to convince the business to change this naming, and I'd be concerned about other potential naming conflicts.

**Comment by kaqqao** [comment]
Yes, naming conflicts are notoriously difficult to spot and even harder to fix systematically. I've been trying to find a generic solution for a very long time without much practical success. The issue is that the user is free to map any type as they choose, and things such as annotation can influence how a type gets mapped, so a single Java type can easily end up being mapped as many different GraphQL types, based on annotation at the place where the type is used. The reverse is also true, multiple different Java types commonly map to a single GraphQL type. So reliably detecting a naming conflict is... a nightmare. The current system does its best to detect a _potential_ collision and warn you about it (you've probably seen warning in your own log) but it's never 100% reliable.

Anyway, if I understood you, you've managed to solve the problem you were facing? Can this issue be closed?

**Comment by slavap** [comment]
I'm getting this warning for every getter annotated like this:
i.l.graphql.generator.OperationMapper    : Potential type name collision detected: 'String' bound to multiple types: @io.leangen.graphql.annotations.GraphQLNonNull() java.lang.String (loaded by the bootstrap class loader) and @javax.validation.constraints.Size(groups=[], min=0, message={javax.validation.constraints.Size.message}, max=60, payload=[]) java.lang.String (loaded by the bootstrap class loader). Assign unique names using the appropriate annotations or override the TypeInfoGenerator. For details and solutions see https://github.com/leangen/graphql-spqr/wiki/Errors#non-unique-type-name. If this warning is a false positive, please report it: https://github.com/leangen/graphql-spqr/issues.

```java
import javax.persistence.Column;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

    @Column(name = "LAST_NAME", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getLastName() {
        return this.lastName;
    }
```

That's quite strange, any idea how can it be suppressed?

**Comment by kaqqao** [comment]
The default name collision detection rules have been relaxed to [only consider the annotations coming from the `io.leangen` package](https://github.com/leangen/graphql-spqr/blob/906e816f0fb2cdc46335e6f1048f231be6b1045c/src/main/java/io/leangen/graphql/GraphQLSchemaGenerator.java#L953) (except `@GraphQLNonNull`) when comparing types.
This can be easily overridden/customized via `GraphQLSchemaGenerator#withTypeComparators`. See [`SynonymBaseTypeComparator`](https://github.com/leangen/graphql-spqr/blob/906e816f0fb2cdc46335e6f1048f231be6b1045c/src/main/java/io/leangen/graphql/generator/mapping/IgnoredAnnotationsTypeComparator.java) and [`IgnoredAnnotationsTypeComparator`](https://github.com/leangen/graphql-spqr/blob/906e816f0fb2cdc46335e6f1048f231be6b1045c/src/main/java/io/leangen/graphql/generator/mapping/SynonymBaseTypeComparator.java) for some convenient comparator implementations.
