### ISSUE TITLE
Query failed to validate : query GetUsers($userId: ID!) -> Validation error of type UnknownType: Unknown type ID

### ISSUE THREAD

**Issue by iguissouma** [leangen/graphql-spqr#233]
Hello,

I'm facing the following error when a GraphQL Client  submit a query with a variable as ID!

ValidationError{validationErrorType=UnknownType, queryPath=null, message=Validation error of type UnknownType: Unknown type ID, locations=[SourceLocation{line=1, column=25}], description='Unknown type ID'}

Here my Test Case:

```
data class User(@GraphQLQuery val id: Int, @GraphQLQuery val name: String)
class UserService {
    @GraphQLQuery(name = "users")
    fun getUsersById(@GraphQLArgument(name = "id") @GraphQLId id: Int?): List<User> {
        val user = User(id, "TOTO")
        val user2 = User(id, "TITI")
        return Arrays.asList(user, user2)
    }
}
```

```
class UserServiceTest {

    @Test
    fun getUsersById() {
        val schema = TestSchemaGenerator()
                .withOperationsFromSingleton(UserService())
                .generate()

        val exe = GraphQL.newGraphQL(schema).build()
        val userId = "\$userId"
        val result = exe.execute("""
            query GetUsers($userId: ID!) {
              users(id: $userId) {
                id
                name
              }
            }
        """.trimIndent())
        println("result = ${result}")
        Assertions.assertThat(result.errors).isEmpty()
    }

}
```

How to make GraphQL server accept type ID as input variable?
I'm using the spqr graphql spring boot starter.
Thanks.

**Comment by kaqqao** [comment]
This is yet another effect of the issues described [here](https://github.com/leangen/graphql-spqr#kotlin). `TYPE_USE` annotations, like `@GraphQLId` simply get lost by the Kotlin compiler. The fix that bug is fortunately finally scheduled for Kotlin 1.4.
Until then, I'm afraid I can't do much.
