### ISSUE TITLE
GraphQLUnion + Subscription

### ISSUE THREAD

**Issue by csueiras** [leangen/graphql-spqr#238]
Hi,

I'm working on a GraphQL schema that has a subscription that returns a union, any time a message is returned through my subscription there's an exception thrown somewhere deep in graphql-java:
```
{
  "error": {
    "message": "graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLObjectType"
  }
}
```

My code is basically something like this:

```
@GraphQLUnion(name = "MyUnionType", possibleTypeAutoDiscovery = true)
public interface MyUnionType {} 

@GraphQLType(name="MyType")
public class MyType {
...
}
```

Then in my graphql service class

```
Publisher<MyUnionType> mySubscription() {
  // use reactor flux sink here to send new MyType(...)
}
```

When a message is published from my subscription that exception bubbles up. A thing I've noticed is that if I return a simpler implementation of MyUnion (that has no complex children) then I get no error whatsoever and get the message out just fine. The same complex type is returned from a Query without any issues, the error only occurs inside a subscription.

I suspect something is wrong on my end but I'm not sure where to look at for issues since this appears to be triggered somewhere deep in graphql-java, @kaqqao  any suggestions for debugging this issue perhaps? I can probably put some time into creating a minimal project to reproduce this issue if nothing obvious stands out.

Edit:

I am querying like this from my client side:

```
subscription ListenForUpdates {
  mySubscription {
    __typename
    ... on MyComplexType {   
       contents
    }
    ... on MySimpleType {
       contents
    }
  }
}
```

**Comment by csueiras** [comment]
To add another datum, `MyComplexType` is implementing another interface as well as "implementing" the Union. I wonder if thats the nature of this issue, is that illegal?

**Comment by kaqqao** [comment]
I've just quickly tested the following code (crammed it all into one class):

```java
@GraphQLApi
@Service
public class UnionService {

    @GraphQLUnion(name = "MyUnionType", possibleTypeAutoDiscovery = true)
    public interface MyUnionType {}

    @GraphQLInterface(name = "Cool")
    public interface Cool {
        boolean isCool();
    }

    @GraphQLType(name="One")
    public static class One implements Cool, MyUnionType {

        private final String name;
        private final int count;

        public One(String name, int count) {
            this.name = name;
            this.count = count;
        }

        public String getName() {
            return name;
        }

        public int getCount() {
            return count;
        }

        @Override
        public boolean isCool() {
            return true;
        }
    }

    public static class Two implements MyUnionType {

        private final String color;

        public Two(String color) {
            this.color = color;
        }

        public String getColor() {
            return color;
        }
    }

    @GraphQLSubscription
    public Publisher<MyUnionType> mySubscription() {
        return Flux.just(new One("one", 1), new Two("purple"));
    }
}
```

with queries:

```graphql
subscription testOne {
  mySubscription {
    ... on One {
      name
      count
    }
    ... on Two {
      color
    }
  }
}
 #Wasn't even sure if this style is allowed 😅
subscription testTwo {
  mySubscription {
    ... on Cool {
      cool
    }
  }
}
```
And all worked as expected. I'm on Spring Starter 0.0.4 and the current master of SPQR, so there might be differences there, although I can't remember anything relevant changing...
So it must be something more involving... Either try setting a break point at the place where the exception occurs and inspect what type was received (a non-`GraphQLObject` type was somehow returned for a union it seems), or please try making a sample that replicates the issue...

**Comment by csueiras** [comment]
Hey @kaqqao I'm going to work on putting a small project to reproduce, but so far I see where the exception is happening. Its not in graphql-java, its in SPQR, specifically in the class `io.leangen.graphql.generator.MappedType`, basically `graphQLType` is of type `GraphQLTypeReference`, when `getAsObjectType` gets called then i get the `ClassCastException`.

The code looks like its supposed to allow for `GraphQLTypeReference`? Anyways I'm investigating some more now that I have some more data

**Comment by kaqqao** [comment]
Hm, ok, this is good info already. It has something to do with the order in which the types are discovered, most probably.
If the object type is discovered first, then a reference might be ending up in place of the real type. I'll investigate.

**Comment by csueiras** [comment]
Hey so I was able to reproduce it by simply adding a query that used one of the concrete types for the union as its return type:
```
...
    @GraphQLQuery(name = "ones")
    public List<One> myOnes() {
        return ImmutableList.of(new One("one", 1));
    }
    
    @GraphQLSubscription
    public Publisher<MyUnionType> mySubscription() {
        return Flux.just(new One("one", 1), new Two("purple"));
    }
```

I suspect that connecting what you are saying with this... that the `List<One>` type gets discovered first, its the one that ends up in the `graphQLType` and thats what causes my issue.

**Comment by csueiras** [comment]
Doesn't seem to be about an order of discovery, moved the method below the publisher and same issue (I was hoping that would be a quick workaround for now).

**Comment by csueiras** [comment]
A workaround I found is adding the union type as a return type of a dummy query, like this

```    
    @GraphQLQuery(name = "dummy")
    public MyUnionType dummy() {
        return null;
    }
```

Added that and now it all works
