### ISSUE TITLE
Autocomplete in graphiql not working

### ISSUE THREAD

**Issue by himanshumps** [leangen/graphql-spqr#239]
Hi,

I added spqr in a vertx application using this:

```
GraphQLSchema graphQLSchema = new GraphQLSchemaGenerator()
                .withBasePackages("com.example.gpc") 
                .withOperationsFromSingleton(graphQLService)
                .generate();
System.out.println(new SchemaPrinter(SchemaPrinter.Options.defaultOptions().includeDirectives(true).includeExtendedScalarTypes(true).includeIntrospectionTypes(true).includeScalarTypes(true).includeSchemaDefintion(true)).print(graphQLSchema));
return GraphQL.newGraphQL(graphQLSchema).queryExecutionStrategy(new AsyncExecutionStrategy()).build();
```
Added a service which uses spqr:

```
    @GraphQLQuery(name = "getSingleSPDByLegacy_v1")
    public CreditCard getSingleSPDByLegacy(@GraphQLArgument(name = "id") String legacyProductCode) {
        try {
            // Get the GPID
            String gpid = couchbaseOperation.getDocument(MessageFormat.format("TEST::{0}::V1", legacyProductCode)).content().getObject("pData").getString("gpid");
            // Get the actual document
            JsonDocument jsonDocument = couchbaseOperation.getDocument(MessageFormat.format("CREDITCARD::{0}::V1", gpid));
            CreditCard creditCard = Json.decodeValue(jsonDocument.content().toString(), CreditCard.class);
            return creditCard;
        } catch (CouchbaseException ce) {
            logger.error("{}", "Couchbase Exception", ce);
            return new CreditCard();
        } catch (Exception e) {
            logger.error("{}", "Generic Exception", e);
            return new CreditCard();
        }
    }
```

This is the schema that get generated (pasted from graphiql window)

`{__schema={queryType={name=Query}, mutationType=null, types=[{kind=SCALAR, name=Boolean, description=Built-in Boolean, fields=null, inputFields=null, interfaces=null, enumValues=null, possibleTypes=null}, {kind=OBJECT, name=CodeandDescBlock, description=, fields=[{name=code, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=description, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=CreditCard, description=, fields=[{name=cashAdvIndicator, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=currency, description=null, args=[], type={kind=LIST, name=null, ofType={kind=SCALAR, name=ObjectScalar, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=digitalAssets, description=null, args=[], type={kind=LIST, name=null, ofType={kind=OBJECT, name=CreditCardDigitalAssets, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=identifier, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=issuerCountry, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=keyTx, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=legalEntity, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=lineOfBusiness, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=local, description=null, args=[], type={kind=OBJECT, name=CreditCardLocal, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=names, description=null, args=[], type={kind=LIST, name=null, ofType={kind=OBJECT, name=CreditCardNames, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=paymentRequestType, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=productType, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=supplementary, description=null, args=[], type={kind=SCALAR, name=Boolean, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=supplementaryAttributes, description=null, args=[], type={kind=OBJECT, name=CreditCardSupplementaryAttributes, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=supplementaryProducts, description=null, args=[], type={kind=LIST, name=null, ofType={kind=OBJECT, name=SupplementaryProduct, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=type, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=version, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=CreditCardDigitalAssets, description=, fields=[{name=default, description=null, args=[], type={kind=SCALAR, name=Boolean, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=id, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=type, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=CreditCardLocal, description=, fields=[{name=loyaltyRewardsProgramme, description=null, args=[], type={kind=OBJECT, name=CodeandDescBlock, ofType=null}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=CreditCardNames, description=, fields=[{name=default, description=null, args=[], type={kind=SCALAR, name=Boolean, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=language, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=type, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=value, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=CreditCardSupplementaryAttributes, description=, fields=[{name=legacyContext, description=null, args=[], type={kind=OBJECT, name=CreditCardSupplementaryAttributesLegacyContext, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=lifecycleStage, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=related, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=role, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=CreditCardSupplementaryAttributesLegacyContext, description=, fields=[{name=plasticCode, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=sequenceNumber, description=null, args=[], type={kind=SCALAR, name=Int, ofType=null}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=SCALAR, name=Int, description=Built-in Int, fields=null, inputFields=null, interfaces=null, enumValues=null, possibleTypes=null}, {kind=SCALAR, name=ObjectScalar, description=Built-in scalar for dynamic values, fields=null, inputFields=null, interfaces=null, enumValues=null, possibleTypes=null}, {kind=OBJECT, name=Query, description=Query root, fields=[{name=getSingleSPDByLegacy_v1, description=null, args=[{name=id, description=, type={kind=SCALAR, name=String, ofType=null}, defaultValue=null}], type={kind=OBJECT, name=CreditCard, ofType=null}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=SCALAR, name=String, description=Built-in String, fields=null, inputFields=null, interfaces=null, enumValues=null, possibleTypes=null}, {kind=OBJECT, name=SupplementaryProduct, description=, fields=[{name=identifier, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=lifecycleStage, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=role, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=SCALAR, name=UNREPRESENTABLE, description=Unrepresentable type, fields=null, inputFields=null, interfaces=null, enumValues=null, possibleTypes=null}, {kind=OBJECT, name=__Directive, description=null, fields=[{name=args, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__InputValue, ofType=null}}}}, isDeprecated=false, deprecationReason=null}, {name=description, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=locations, description=null, args=[], type={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=ENUM, name=__DirectiveLocation, ofType=null}}}, isDeprecated=false, deprecationReason=null}, {name=name, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=onField, description=null, args=[], type={kind=SCALAR, name=Boolean, ofType=null}, isDeprecated=true, deprecationReason=Use `locations`.}, {name=onFragment, description=null, args=[], type={kind=SCALAR, name=Boolean, ofType=null}, isDeprecated=true, deprecationReason=Use `locations`.}, {name=onOperation, description=null, args=[], type={kind=SCALAR, name=Boolean, ofType=null}, isDeprecated=true, deprecationReason=Use `locations`.}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=ENUM, name=__DirectiveLocation, description=An enum describing valid locations where a directive can be placed, fields=null, inputFields=null, interfaces=null, enumValues=[{name=ARGUMENT_DEFINITION, description=Indicates the directive is valid on a field argument SDL definition., isDeprecated=false, deprecationReason=null}, {name=ENUM, description=Indicates the directive is valid on an enum SDL definition., isDeprecated=false, deprecationReason=null}, {name=ENUM_VALUE, description=Indicates the directive is valid on an enum value SDL definition., isDeprecated=false, deprecationReason=null}, {name=FIELD, description=Indicates the directive is valid on fields., isDeprecated=false, deprecationReason=null}, {name=FIELD_DEFINITION, description=Indicates the directive is valid on a field SDL definition., isDeprecated=false, deprecationReason=null}, {name=FRAGMENT_DEFINITION, description=Indicates the directive is valid on fragment definitions., isDeprecated=false, deprecationReason=null}, {name=FRAGMENT_SPREAD, description=Indicates the directive is valid on fragment spreads., isDeprecated=false, deprecationReason=null}, {name=INLINE_FRAGMENT, description=Indicates the directive is valid on inline fragments., isDeprecated=false, deprecationReason=null}, {name=INPUT_FIELD_DEFINITION, description=Indicates the directive is valid on an input object field SDL definition., isDeprecated=false, deprecationReason=null}, {name=INPUT_OBJECT, description=Indicates the directive is valid on an input object SDL definition., isDeprecated=false, deprecationReason=null}, {name=INTERFACE, description=Indicates the directive is valid on an interface SDL definition., isDeprecated=false, deprecationReason=null}, {name=MUTATION, description=Indicates the directive is valid on mutations., isDeprecated=false, deprecationReason=null}, {name=OBJECT, description=Indicates the directive is valid on an object SDL definition., isDeprecated=false, deprecationReason=null}, {name=QUERY, description=Indicates the directive is valid on queries., isDeprecated=false, deprecationReason=null}, {name=SCALAR, description=Indicates the directive is valid on a scalar SDL definition., isDeprecated=false, deprecationReason=null}, {name=SCHEMA, description=Indicates the directive is valid on a schema SDL definition., isDeprecated=false, deprecationReason=null}, {name=UNION, description=Indicates the directive is valid on an union SDL definition., isDeprecated=false, deprecationReason=null}], possibleTypes=null}, {kind=OBJECT, name=__EnumValue, description=null, fields=[{name=deprecationReason, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=description, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=isDeprecated, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=SCALAR, name=Boolean, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=name, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=SCALAR, name=String, ofType=null}}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=__Field, description=null, fields=[{name=args, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__InputValue, ofType=null}}}}, isDeprecated=false, deprecationReason=null}, {name=deprecationReason, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=description, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=isDeprecated, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=SCALAR, name=Boolean, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=name, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=SCALAR, name=String, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=type, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__Type, ofType=null}}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=__InputValue, description=null, fields=[{name=defaultValue, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=description, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=name, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=SCALAR, name=String, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=type, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__Type, ofType=null}}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=__Schema, description=A GraphQL Introspection defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, the entry points for query, mutation, and subscription operations., fields=[{name=directives, description='A list of all directives supported by this server., args=[], type={kind=NON_NULL, name=null, ofType={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__Directive, ofType=null}}}}, isDeprecated=false, deprecationReason=null}, {name=mutationType, description=If this server supports mutation, the type that mutation operations will be rooted at., args=[], type={kind=OBJECT, name=__Type, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=queryType, description=The type that query operations will be rooted at., args=[], type={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__Type, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=subscriptionType, description='If this server support subscription, the type that subscription operations will be rooted at., args=[], type={kind=OBJECT, name=__Type, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=types, description=A list of all types supported by this server., args=[], type={kind=NON_NULL, name=null, ofType={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__Type, ofType=null}}}}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=OBJECT, name=__Type, description=null, fields=[{name=description, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=enumValues, description=null, args=[{name=includeDeprecated, description=null, type={kind=SCALAR, name=Boolean, ofType=null}, defaultValue=false}], type={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__EnumValue, ofType=null}}}, isDeprecated=false, deprecationReason=null}, {name=fields, description=null, args=[{name=includeDeprecated, description=null, type={kind=SCALAR, name=Boolean, ofType=null}, defaultValue=false}], type={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__Field, ofType=null}}}, isDeprecated=false, deprecationReason=null}, {name=inputFields, description=null, args=[], type={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__InputValue, ofType=null}}}, isDeprecated=false, deprecationReason=null}, {name=interfaces, description=null, args=[], type={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__Type, ofType=null}}}, isDeprecated=false, deprecationReason=null}, {name=kind, description=null, args=[], type={kind=NON_NULL, name=null, ofType={kind=ENUM, name=__TypeKind, ofType=null}}, isDeprecated=false, deprecationReason=null}, {name=name, description=null, args=[], type={kind=SCALAR, name=String, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=ofType, description=null, args=[], type={kind=OBJECT, name=__Type, ofType=null}, isDeprecated=false, deprecationReason=null}, {name=possibleTypes, description=null, args=[], type={kind=LIST, name=null, ofType={kind=NON_NULL, name=null, ofType={kind=OBJECT, name=__Type, ofType=null}}}, isDeprecated=false, deprecationReason=null}], inputFields=null, interfaces=[], enumValues=null, possibleTypes=null}, {kind=ENUM, name=__TypeKind, description=An enum describing what kind of type a given __Type is, fields=null, inputFields=null, interfaces=null, enumValues=[{name=ENUM, description=Indicates this type is an enum. `enumValues` is a valid field., isDeprecated=false, deprecationReason=null}, {name=INPUT_OBJECT, description=Indicates this type is an input object. `inputFields` is a valid field., isDeprecated=false, deprecationReason=null}, {name=INTERFACE, description=Indicates this type is an interface. `fields` and `possibleTypes` are valid fields., isDeprecated=false, deprecationReason=null}, {name=LIST, description=Indicates this type is a list. `ofType` is a valid field., isDeprecated=false, deprecationReason=null}, {name=NON_NULL, description=Indicates this type is a non-null. `ofType` is a valid field., isDeprecated=false, deprecationReason=null}, {name=OBJECT, description=Indicates this type is an object. `fields` and `interfaces` are valid fields., isDeprecated=false, deprecationReason=null}, {name=SCALAR, description=Indicates this type is a scalar., isDeprecated=false, deprecationReason=null}, {name=UNION, description=Indicates this type is a union. `possibleTypes` is a valid field., isDeprecated=false, deprecationReason=null}], possibleTypes=null}], directives=[{name=include, description=Directs the executor to include this field or fragment only when the `if` argument is true, locations=[FIELD, FRAGMENT_SPREAD, INLINE_FRAGMENT], args=[{name=if, description=Included when true., type={kind=NON_NULL, name=null, ofType={kind=SCALAR, name=Boolean, ofType=null}}, defaultValue=null}]}, {name=skip, description=Directs the executor to skip this field or fragment when the `if`'argument is true., locations=[FIELD, FRAGMENT_SPREAD, INLINE_FRAGMENT], args=[{name=if, description=Skipped when true., type={kind=NON_NULL, name=null, ofType={kind=SCALAR, name=Boolean, ofType=null}}, defaultValue=null}]}, {name=defer, description=This directive allows results to be deferred during execution, locations=[FIELD], args=[]}]}}`

**When I use Ctrl+Space or see the Docs section in graphiql window, I see that autocomplete is not giving any suggestions. All other shortcuts are working fine.**

![graphiql_error](https://user-images.githubusercontent.com/22702284/55061990-0a089b80-509b-11e9-8dbc-e3f98ad2c22f.png)

![graphiql_error_1](https://user-images.githubusercontent.com/22702284/55062393-ee51c500-509b-11e9-8ce7-c23e83eaf848.png)

These are the files that I am using to launch graphiql (Latest version used from https://github.com/graphql/graphiql)

[graphiql.zip](https://github.com/leangen/graphql-spqr/files/3012267/graphiql.zip)

**Comment by himanshumps** [comment]
I think I know why the issue is coming for me... Will keep you posted

**Comment by himanshumps** [comment]
It was a mistae from my end. I was not sending the data in json format and was expecting graphiql to work. This issue can be closed.

**Comment by kaqqao** [comment]
Haha, ok, glad you've got it figured out 😁

In general, if GraphiQL isn't auto completing, there's something wrong with the response it received from the backend. And GraphiQL has rather particular expectations...
