### ISSUE TITLE
query with different name than actual field name

### ISSUE THREAD

**Issue by payal257** [leangen/graphql-spqr#240]
I have a query like this

```
query {
  api {
     getInfo(id: "2") {
       id
       fullName
     }
  }
}
```

But in POJO class I have this:

```
class POJO{


@GraphQLQuery(name = "fullName")
private int somefield;
public getSomeField(){
return somefield;
}

....
// some other code

}
```

How to make this work, where the GraphQlQuery name is different than the actual field name?

**Comment by kaqqao** [comment]
Just move `@GraphQLQuery(name = "fullName")` from the private field to the getter.
SPQR 0.9.9 doesn't look at private fields. The next release (should happen very very soon) will support that.

**Comment by payal257** [comment]
Thanks its working as expected.
