### ISSUE TITLE
Inherited properties not include

### ISSUE THREAD

**Issue by safaksahin** [leangen/graphql-spqr#248]
Hi,
When i run my spring boot application, inside auto generated graphql schema’s, web services’ output objects’ inherited attributes are missing but with @GraphQLArgument annotated input objects’ whole attributes are there.

**Comment by kaqqao** [comment]
If the parent class is in a different package, its properties won't be scanned by default. You must explicitly set the base packages for the application.
If you're using SPQR Starter, add e.g. `graphql.spqr.base-packages=your.base.package, another.base.package` to your `application.properties` (or YAML).
If using SPQR directly, call `generator.withBasePackages("base.package")`.

**Comment by safaksahin** [comment]
Thanks so much @kaqqao . I added packages to application.properties file this solves it.

**Comment by nimi-kaushal** [comment]
I'm having issue of custom descriptions for nested fields are not showing even though descriptions are added as @GraphQLQuery descriptions.
