### ISSUE TITLE
Validation error of type SubSelectionRequired: Sub selection required for type Timestamp of field

### ISSUE THREAD

**Issue by JieunSon96** [leangen/graphql-spqr#251]
I use GraphQL-SPQR Library The problem is "Validation error of type SubSelectionRequired: Sub selection required for type Timestamp" Maybe there is expression in query for timestamp or format in Entity

`{"query":
"{findUserPointByUserId(userId:73){rowNum userAccountPointUserId totalPoint pointTypeDescription point userAccountCreatedDate} findUserAccountImgByUserId(userId:73){imageId,userId,presentImgNum}}"

}`

Error
`{
    "errors": [
        {
            "message": "Validation error of type SubSelectionRequired: Sub selection required for type Timestamp of field userAccountCreatedDate",
            "locations": [
                {
                    "line": 1,
                    "column": 103
                }
            ]
        }
    ]
}`

Entity

`public class ViewUserAccountPoint {
    @Id
    @Basic
    @GraphQLQuery(name = "rowNum")
    @Column(name = "row_num", nullable = true)
    private Long rowNum;

    @Basic
    @Column(name = "user_account_point_userid", nullable = true)
    @GraphQLQuery(name = "userAccountPointUserId")
    private Integer userAccountPointUserId;

    @Basic
    @Column(name = "subject_id", nullable = true)
    @GraphQLQuery(name = "subjectId")
    private Integer subjectId;

    @Basic
    @Column(name = "point", nullable = true)
    @GraphQLQuery(name = "point")
    private Integer point;

    @Basic
    @Column(name = "user_account_point_typeid", nullable = true)
    @GraphQLQuery(name = "userAccountPointTypeId")
    private Integer userAccountPointTypeId;

    @Basic
    @Column(name = "date_created", nullable = true)
    @GraphQLQuery(name = "userAccountCreatedDate")
    private Timestamp userAccountCreatedDate;`
I use @GraphQLQuery is there annotation for timestamp format??

Service
`public List<ViewUserAccountPoint> findUserPointByUserId(@GraphQLArgument(name = "userId") Integer userId){
        return viewUserAccountPointRepository.findByUserAccountPointUserIdOrderByUserAccountCreatedDateDesc(userId);
    }`

I search through all query timestamp format However, i couldn't find
hope to hear the solution. thank you

**Comment by codelizrd** [comment]
The timestamp object is treated as an object/entity and it does not have any (exposed) members; that's why. 

You either need to expose members within the Timestamp object, or create and register a custom TypeMapper that convert between your Timestamp types and a scalar like an integer (so in your schema the ViewUserAccountPoint entity has an userAccountCreatedDate which is an integer).

**Comment by kaqqao** [comment]
@codelizrd is right. If `Timestamp` gets mapped incorrectly, you must register a custom `TypeMapper`. Look at `ScalarMapper` for inspiration.

But, is `Timestamp` a standard type? You didn't list your imports so I can't tell which package it's coming from?
If it's standard, I'll gladly add support for it out of the box.

**Comment by kaqqao** [comment]
Not that I look, if your `Timestamp` is `java.sql.Timestamp` it is already supported out of the box.
Are you on the latest version?

**Comment by kaqqao** [comment]
Answer [your StackOverflow question](https://stackoverflow.com/questions/55944508/validation-error-of-type-subselectionrequired-sub-selection-required-for-type-t/55987831#55987831) as well.

Quoting:

> For one reason or another, `Timestamp` got mapped incorrectly. It ended up being an object and not a scalar. As mentioned in the issue you opened, it's unclear where is `Timestamp` in your code coming from.

> `java.sql.Timestamp` is supported out of the box in recent versions of GraphQL SPQR, so you might be on an older version.

> If that's not the case, it would mean `Timestamp` is some other than `java.sql.Timestamp`, and you'd need to register a custom mapper for it.

```java
public class TimestampMapper implements TypeMapper {

    // Define the scalar as needed, see io.leangen.graphql.util.Scalars for inspiration
    private static final GraphQLScalarType TIMESTAMP = ...;

    @Override
    public GraphQLOutputType toGraphQLType(AnnotatedType javaType, OperationMapper operationMapper, Set<Class<? extends TypeMapper>> mappersToSkip, BuildContext buildContext) {
        return TIMESTAMP; //it's important to always return the same instance
    }

    @Override
    public GraphQLInputType toGraphQLInputType(AnnotatedType javaType, OperationMapper operationMapper, Set<Class<? extends TypeMapper>> mappersToSkip, BuildContext buildContext) {
        return TIMESTAMP; //same as above
    }

    @Override
    public boolean supports(AnnotatedType type) {
        return ClassUtils.isSuperClass(Timestamp.class, type);
    }
}
```
> Then register your mapper:

```java
generator.withTypeMappers(new TimestampMapper())
```

**Comment by kaqqao** [comment]
I'll close this one since there's no feedback and it seems sufficiently addressed.
If you have further questions, feel free to reopen.
