### ISSUE TITLE
upgrade to graphql-java v12

### ISSUE THREAD

**Issue by wasche** [leangen/graphql-spqr#252]
Numerous breaking changes from 11->12, including fields now being sorted, so fieldOrder can no longer be supported.

**Comment by kaqqao** [comment]
Thanks. I'll look into this ASAP.
graphql-java version upgrade is scheduled for the release after the next.

**Comment by wasche** [comment]
I'm posting this because I need it for a project I'm working on as we're trying to upgrade to v12 and also use spqr. Once I have everything upgraded I can do more testing around these changes and if I find any issues I'll update the PR. I'm sure my changes aren't perfect, as my familiarity with these libraries is fairly new, but all tests pass and things appear to work as far as I can tell.

**Comment by juliansxw** [comment]
Do we have any workaround for field sorting after upgrading to > graphql-java:12? Basically, field sorting is a good feature to have a well-organized schema definition.

**Comment by kaqqao** [comment]
@juliansxw graphql-java v13 added the possibility back, so the next SPQR release will re-introduce it as well. The release is due this week!
