### ISSUE TITLE
Generate GraphQL type names for generic Java types correctly

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr#255]
A type like `One<Two<Three>>` will end up mapped `One_Two` instead of `One_Two_Three`. This can easily lead to name collisions.

**Comment by edeesis** [comment]
This was closed in https://github.com/leangen/graphql-spqr/commit/7484847e0d8b8a329af2df89a793ff42f1402da0#diff-2f500203f43540e9a4e1d070856a9934 for those that are looking for it - released in v0.10.0
