### ISSUE TITLE
Could not initialize proxy with Spring and Hibernate

### ISSUE THREAD

**Issue by drenda** [leangen/graphql-spqr#263]
I'm using Spring Boot 2.1 and Hibernate. I'm trying your library and it's really cool.
I'm wondering how to deal with lazy initialization exception that could arise when the client create a query on nested objects.
In my model many times collections or related objects are set as Lazy, so they are not retrieved during the query.

For example I've a Printer where the store field is a lazy object:

```
public class Printer extends AbstractEntity {

    @NotBlank
    @Column(nullable = false)
    private String name;

    // Ip address or hostname
    @NotBlank
    @Column(nullable = false)
    private String remoteAddress;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    // @JsonSerialize(using = PrinterModelSerializer.class)
    private PrinterModel model;

    //The zoneId name, i.e. Europe/Rome
    private String zoneId;

    @NotNull
    @Column(nullable = false, columnDefinition = "BIT DEFAULT 0")
    private boolean ssl = false;

    //Printer's serial number, expecially useful with fiscal printer
    @Size(max = 30)
    private String serialNumber;

    // The store where the device is connected
    @NotNull
    @OnDelete(action = OnDeleteAction.CASCADE)
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "store_id", updatable = false)
    private Store store;
```

I created a query to load printers:

```
@Component
@Log4j2
public class PrinterQuery {

    @Autowired
    private PrinterRepository printerRepository;

    @GraphQLQuery(name = "findAllPrinters")
    public List<Printer> findAll() {
        log.debug(SecurityContextHolder.getContext().getAuthentication());
        return printerRepository.findAll();
    }
}
```
but when I try to run a query like this:

```
{
  findAllPrinters {
    model
    name
    store {
      name
    }
  }
}
```

I've this exception:

```
{
  "errors": [
    {
      "message": "Exception while fetching data (/findAllPrinters[0]/store/name) : could not initialize proxy [myproject.model.stores.Store#1] - no Session",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "findAllPrinters",
        0,
        "store",
        "name"
      ]
    }
  ],
  "data": {
    "findAllPrinters": [
      {
        "model": "EPSON_FP81II",
        "name": "Epson ",
        "store": {
          "name": null
        }
      }
    ]
  }
}
```

It's really clear the problem. I'm just wondering how to solve it; I've two ideas in mind but I'm not sure if they are correct:

1. tell graphql-spqr how to get the store (I'm not sure if I can a fetcher or something like that)

2. simply use a query that already make needed joins return printerRepository.findAllJoinStore(); In this case the client could make a deeper query and attempt to access an object that is not in the JOIN chain I did. Is this a good way to follow?

**Comment by codelizrd** [comment]
Your session connection is closed before SPQR was able to serialise all the results.

Look into OpenSessionInViewFilter; this filter will keep the session open until SPQR has finished.

**Comment by drenda** [comment]
Thanks for your suggestion. Keeping the session open seems to be not recommended. Would you suggest other ways to do that other than the ones I pointed out?

**Comment by szantogab** [comment]
You can use data loaders for that purpose. Have a look at this: https://github.com/leangen/graphql-spqr/issues/42

**Comment by kaqqao** [comment]
As @szantogab said, you can use [DataLoader](https://github.com/graphql-java/java-dataloader) for this, but prefetching is likely a simpler approach and will get you what you need. Here's an [excellent blog post](https://www.graphql-java.com/blog/deep-dive-data-fetcher-results/) describing it.
To get a hold of `DataFetchingEnvironment` in SPQR, you can inject `@GraphQLEnvironment ResolutionEnvironment` and get it from there.

**Comment by drenda** [comment]
Thanks very much. Very helpful comments.

**Comment by kaqqao** [comment]
Has the question been sufficiently addressed? Can I close the issue?

**Comment by drenda** [comment]
Sure, thanks!

**Comment by kaqqao** [comment]
Great, glad you got it sorted out :)
