### ISSUE TITLE
NoSuchMethodError on query with Publisher failing with error

### ISSUE THREAD

**Issue by Speyns** [leangen/graphql-spqr#264]
Expecting query for following `@GraphQLQuery`  to return a `ExecutionResult` containing an error.
Actual the query throws a NoSuchMethodError.

The `@GraphQLQuery` declaration:
```
public class QueryService {
	@GraphQLQuery
	public Publisher<String> error() {
		return Flowable.error(new RuntimeException());
	}
}
```

The GraphQL query:
```
QueryService service = new QueryService();
GraphQLSchema schema = new GraphQLSchemaGenerator()
	.withBasePackages(QueryService.class.getPackage().getName())
	.withOperationsFromSingleton(service)
	.generate();
GraphQL graphQL = GraphQL.newGraphQL(schema).build();
graphQL.execute("query{error}"); // ==> throws NoSuchMethodError
```

Version: `spqr` 0.9.9 with `graphql-java` 12.0.

JUnit 5 TestCase to reproduce the error:
[SpqrIssue.java.txt](https://github.com/leangen/graphql-spqr/files/3184695/SpqrIssue.java.txt)

**Comment by Speyns** [comment]
JUnit 5 TestCase extended:
[SpqrIssue.java.withMutationSubscription.txt](https://github.com/leangen/graphql-spqr/files/3184748/SpqrIssue.java.withMutationSubscription.txt)

GraphQL mutation on `@GraphQLMutation` throws `NoSuchMethodError` too.
GraphQL subscription on `@GraphQLSubscription` works as I expecting.

**Comment by kaqqao** [comment]
graphql-java v12 is not supported. Do not expect you can simply upgrade a core dependency to a new major release and have everything magically working.

**Comment by kaqqao** [comment]
Follow [this issue](https://github.com/leangen/graphql-spqr/issues/252) for updates.
