### ISSUE TITLE
MicroProfile `@Deprecated` annotation's reason text is ignored

### ISSUE THREAD

**Issue by andymc12** [leangen/graphql-spqr#267]
In the MicroProfile proto branch, I have a test that uses `@Deprecation("Deprecated mutation, please use \"createWidget\" instead.")` on a mutation method, and `@Deprecation("Deprecated, use length, height, and depth instead.")` on an entity field.  When I test with the generated schema, I don't see either of those deprecation reasons in the schema output.

You can see the test code here:
https://github.com/andymc12/open-liberty/blob/9626eaeeb686760fa45f20deeb21efb2205ce1fc/dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/deprecationApp/src/mpGraphQL10/deprecation/DeprecationTestServlet.java#L83

Thanks!

**Comment by kaqqao** [comment]
MicroProfile support moved into [a separate project](https://github.com/leangen/graphql-spqr-modules/tree/master/graphql-spqr-module-microprofile) (and module).
