### ISSUE TITLE
MicroProfile @FieldsOrder not working

### ISSUE THREAD

**Issue by jefrajames** [leangen/graphql-spqr#270]
It seems that the MicroProfile GraphQL @FieldsOrder annotation is not working. When introspecting the schema, fields are always presented in alphabetical order.

For instance, with the following code: 
```
@Type(value = "Team",  description = "A team made of super heros")
@FieldsOrder({"name", "members"})
public class Team {


	String name;
	List<SuperHero> members;
	...
```
The result of the the following request:
```
{
  __type(name: "Team") {
    name
    description
    fields {
      name
    }
  }
}
```
is
```
{
  "data": {
    "__type": {
      "name": "Team",
      "description": "A team made of super heros",
      "fields": [
        {
          "name": "members"
        },
        {
          "name": "name"
        }
      ]
    }
  }
}
```

**Comment by kaqqao** [comment]
Not sure why it's it's not working in the current Microprofile branch, but as of graphql-java v12 it's no longer possible to arbitrarily order the fields. It enforces alphabetical order so I had to remove that feature in the last SPQR release...

**Comment by jefrajames** [comment]
Does the @FieldsOrder annotation still makes sense if it's no longer implemented by graphql-java? Same observation for @InputFieldsOrder.

**Comment by kaqqao** [comment]
MicroProfile support moved into [a separate project](https://github.com/leangen/graphql-spqr-modules/tree/master/graphql-spqr-module-microprofile) (and module).
