### ISSUE TITLE
GraphQLQuery on everything required?

### ISSUE THREAD

**Issue by edeesis** [leangen/graphql-spqr#271]
Hello!

I'm in the process of converting a pretty large scale GraphQL project over to graphql-spqr in the effort to upgrade to graphql-java 11.

I noticed from reading the source code that the only way to register fields to SPQR is to annotate the field directly. This means that I have to annotate every getter of a service method's return type no?

```
class ReturnType(item: Item) {

	@get:GraphQLQuery
	val id: String
	  get() = item.id
	@get:GraphQLQuery
	val parentId: String?
	  get() = item.parentId
	@get:GraphQLQuery
	val companyId: Long
	  get() = item.companyId
	@get:GraphQLQuery
	val createdDate: Date
	  get() = item.createdDate

}
```

**Comment by kaqqao** [comment]
So the short answer is: no, annotations are pretty much never strictly required.

What gets exposed is controlled by the given `ResolverBuilder`. The three provided implementations use different rules, where `AnnotatedResolverBuilder` will only expose what's explicitly annotated, `BeanResolverBuilder` will expose all getter methods (with or without annotations) and `PublicResolverBuilder` will expose all public methods. In SPQR 0.10.0 `PublicResolverBuilder` is the root extended by the other implementations that apply different filtering rules. All three can be further customized by adding additional filters. You can also provide your own implementation. Remember that you can also use multiple builders at the same time.

Now, `ResolverBuilder`s can be registered at 2 levels separately, the top level (only includes directly registered beans) and deeper levels (parameters and return types discovered on the registered beans). The logic is that at the top level you normally have tighter control, so explicit annotations are preferred, while at the deeper levels you run into 3rd party types, framework classes and what not. By default, only `AnnotatedResolverBuilder` is used at the top level (so only the explicitly annotated elements get exposed) and both `AnnotatedResolverBuilder` and `BeanResolverBuilder` are registered at deeper levels (so all annotated plus all public getters get exposed). This is commonly the correct thing to do, but depending on your setup, you might want to change the configuration. Use `GraphQLSchemaGenerator#withResolverBuilders` to control the top level and `GraphQLSchemaGenerator#withNestedResolverBuilders` to control the deeper levels.

Back to the original question, when you say _fields_ do you literally mean class fields? If so, `PublicResolverBuilder` will happily expose all public fields that are either on the registered bean type directly or within the `basePackages` (controlled via `generator.withBasePackages). If your fields have getters, they'll normally get exposed anyway. I unfortunately have no clue what the code you posted means 😶 SPQR is built with Java in mind. There's nothing preventing anyone from using it for other JVM languages (and I see people doing so successfully) but I won't be able to provide as much support, I'm afraid, as I simply don't know the idiosyncrasies of Scala, Kotlin etc.

Hope that helps. Cheers!

**Comment by edeesis** [comment]
Thanks Bojan for the response!

FYI that code I posted is Kotlin, and the @get:GraphQLQuery is saying to add the `@GraphQLQuery` to the underlying getter of the property that's being annotated. It's equivalent to:

```
public class ReturnType {

	private Item item;

	public ReturnType(Item item) {
		this.item = item;
	}

	@GraphQLQuery
	public String getId() {
		return item.getId();
	}

	@GraphQLQuery
	public String getParentId() {
		return item.getParentId();
	}

	@GraphQLQuery
	public Long getCompanyId() {
		return item.getCompanyId();
	}

	@GraphQLQuery
	public Date getCreatedDate() {
		return item.getCreatedDate();
	}

}
```

But to the actual answer to your question, can you explain the difference between a NestedBuilderResolver and a regular ResolverBuilder?

**Comment by edeesis** [comment]
And if I’m reading what you’re saying correctly - objects that are crawled for their fields (not top level objects), do not need the annotations to access the getters. That also explains some other behavior I saw recently. Thanks!

**Comment by edeesis** [comment]
I'm going to close this. My original question has been answered, and I think I understand the distinction between the two types of ResolverBuilders.

**Comment by kaqqao** [comment]
Nested resolver builders and resolver builders are the same thing (any `ResolverBuilder` instance can be used as both), they're just used at different levels. Nested are for levels that get discovered automatically, the regular are for the explicitly registered (i.e. top level) beans only.

Anyway, glad you've got it figured out.
