### ISSUE TITLE
MapToListTypeAdapter Not Registered by Default

### ISSUE THREAD

**Issue by edeesis** [leangen/graphql-spqr#272]
I think I understand why MapToListTypeAdapter isn't registered by default - because it's a generic type and the generics needs to be specified.

I think this kind of defeats the purpose of using graphql-spqr to generate your schema. If you can figure out the how to unwrap the generics of a List (or any other Collection), why can't you also do it with a Map?

**Comment by kaqqao** [comment]
It already does what you describe. You don't need to actually specify the generics yourself. See the tests using that adapter for examples.

The reason why it's not registered by default is that most people don't want that behavior, but want the maps to be scalars.
