### ISSUE TITLE
OperationNameGenerator no longer available

### ISSUE THREAD

**Issue by piotr-swierczynski** [leangen/graphql-spqr#274]
Hi! I tried to migrate from spqr 0.9.9 to 0.10.0 and unfortunately the newest version lacks OperationNameGenerator. How to overcome this issue, because previously I used an extension of AnnotatedOperationNameGenerator to make my methods names (Query and Mutations) valid in terms of my business needs. How to override the default behavior of 0.10.0 spqr to achieve something like this:
`@GraphQLQuery
public Long getMySuperLong() {
      return //some king of business logic
}`
displayed in schema as _**getMySuperLong**_ query?

**Comment by kaqqao** [comment]
It got renamed to `OperationInfoGenerator` and is now used to also produce descriptions and deprecation reasons for fields (operations), not only names.
You should be able to easily convert your implementation.

**Comment by kaqqao** [comment]
Actually, if all you want is to preserve the `get` prefix, you can use the built-in `MemberOperationInfoGenerator`:

```java
new AnnotatedResolverBuilder()
    .withOperationInfoGenerator(new MemberOperationInfoGenerator())
```

**Comment by piotr-swierczynski** [comment]
Thank you very much! It works as you said! ;) Unfortunately MemberOperationInfoGenerator is not the case here, but I've extended AnnotatedOperationInfoGenerator and it runs like a charm ;) Thanks for quick answer and this amazing customizable framework!
