### ISSUE TITLE
Use final MicroProfile groupId instead of sandbox

### ISSUE THREAD

**Issue by jeanouii** [leangen/graphql-spqr#285]
Currently, the project is using a sandbox groupId for the api coordinates.

When getting in the project for the first time, it sounds straightforward to checkout the Eclipse MicroProfile API and build it for use.

The project should use the final maven coordinates so it's easier for a user to get into.

**Comment by kaqqao** [comment]
MicroProfile support moved into [a separate project](https://github.com/leangen/graphql-spqr-modules/tree/master/graphql-spqr-module-microprofile) (and module).
