### ISSUE TITLE
test

### ISSUE THREAD

**Issue by yunzhishang** [leangen/graphql-spqr#3]
my fault.

**Comment by yunzhishang** [comment]
17:05:02.485 [main] INFO  c.o.m.g.e.e.GraphQLQueryExecutor - Executing request. Operation name: null. Request: query DroidFieldInFragment {
    hero {
        name
        ...DroidFields
    }
}

fragment DroidFields on Droid {
    primaryFunction
} 
17:05:02.644 [main] INFO  c.o.m.g.t.GenericStarWarsSchemaParserTest - Complexity: 3.0. Result: {
  "hero" : {
    "name" : null,
    "primaryFunction" : "Astromech"
  }
}

Can not get the name

**Comment by kaqqao** [comment]
Can I perhaps see your code anywhere? Just being curious as to how you are using the lib.
What exactly was the problem?
