### ISSUE TITLE
Add subscription support

### ISSUE THREAD

**Issue by fbrunosm** [leangen/graphql-spqr#30]
Is there any provision for adding subscript support to SPQR?

**Comment by kaqqao** [comment]
Not immediately, as graphql-java itself still doesn't support this feature. But, we are looking into it in graphql-java project, and once subscriptions are added there, I'll make sure SPQR supports them too.

**Comment by kaqqao** [comment]
graphql-java 6 adds subscription support, so SPQR now has it too in `master`, committed as a part of #22 .

**Comment by kaqqao** [comment]
v0.9.5 ships with the support for subscriptions via the new `@GraphQLSubscription` annotation. See [here](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/SubscriptionTest.java) for a simple usage example.

**Comment by xereda** [comment]
@murilokprado

**Comment by kaqqao** [comment]
See [the Spring Starter sample](https://github.com/leangen/graphql-spqr-samples/blob/master/spring-boot-starter-sample/src/main/java/io/leangen/graphql/samples/service/TaskService.java#L61) for a more realistic example using Reactor.
