### ISSUE TITLE
Apollo websocket authentication

### ISSUE THREAD

**Issue by danilolima** [leangen/graphql-spqr#301]
I can't authenticate over websocket using Apollo aproach:

```
const wsLink = new WebSocketLink({
uri: 'ws://localhost:9090/graphql',
  options: {
    reconnect: true,
    connectionParams: {
        authToken: user.authToken,
    },
});
```

The response is "HTTP Authentication failed; no valid credentials available"

How I can manage the connection params 'authToken' in Spring?

**Comment by kaqqao** [comment]
Don't [duplicate](https://github.com/leangen/graphql-spqr-spring-boot-starter/issues/49) issues.
