### ISSUE TITLE
Question: how to add additional types based on java class

### ISSUE THREAD

**Issue by pepijno** [leangen/graphql-spqr#303]
Hi,

I have a simple question. I hava a java class which is not part of any resolver and thus it is not converted to a graphql type in the schema. For an exotic use case I do however wish to generate a graphql type based on this class. I know the `GraphQLSchemaGenerator` has a method `withAdditionalTypes` which expects a `Collection<GraphQLType>` as input which means that I need to create the GraphQLType means. Is there any way to create the GraphQLType based on the java class?

**Comment by kaqqao** [comment]
I presume you want to register more types that implement an exposed interface. In that case, you can do something like:

```java
generator.withImplementationDiscoveryStrategy(new DefaultImplementationDiscoveryStrategy()
                        .withAdditionalImplementations(SubTypeOne.class, SubTypeTwo.class))
```

where `SubTypeOne` and `SubTypeTwo` are the implementations that wouldn't normally be exposed.

**Comment by kaqqao** [comment]
See #208
I'll close this one as there's no response... If your use-case falls outside the described scenario, feel free to reopen.

**Comment by Climooo** [comment]
Hi, 
I have the same problem as in the original post, but the given solution does not work for me.
Using "withImplementationDiscoveryStrategy" is not called at all in my case, as it seems to be used for Interface/Union only (I guess).
My case is that I have an enumeration, which is exposed only in GraphQL errors (in an "extension", with a "code" key). I'd like to expose that enumeration in my schema, as it is used by my apollo client. 
Is that possible or am I totally wrong ?
