### ISSUE TITLE
Validation failing for boolean field if values not passed

### ISSUE THREAD

**Issue by Abubkar** [leangen/graphql-spqr#304]
Validation failing for boolean field if values not passed.
Message 
Filed booleanFiledName of variable has coerced Null value foe NonNull type Boolean.

**Comment by kaqqao** [comment]
A `boolean` value can indeed never be null, so it's non-nullable in the schema. Use `Boolean` instead, or provide a default value as appropriate.

**Comment by kaqqao** [comment]
Closing this one as it has been answered and there was no subsequent activity for a long time. Reopen if needed.
