### ISSUE TITLE
Add support for java.util.Optional parameters

### ISSUE THREAD

**Issue by JonathanIlk** [leangen/graphql-spqr#307]
Add support for @GraphQLQuery Methods that have Optional parameters.

When a query has an optional Parameter, then the parameter value should be an empty Optional when no value is provided by the user and a filled optional when a value is supplied.
Furthermore the parameter should automatically be nullable in the query.

**Comment by JonathanIlk** [comment]
## EXAMPLE

```
    @GraphQLQuery
    public Iterable<Object> findObjects(Optional<QueryConfig> queryConfig) {
```
When I call this method in graphQL like this:

```
findObjects {
 ...
}
```

then queryConfig = null.


The following code in the **InputValueDeserializer** seems to be problematic:

```
    @Override
    public Object getArgumentValue(ArgumentInjectorParams params) {
        if (params.getInput() == null) {
            if (params.isPresent()) { // = false!
                return EMPTY_VALUES.getOrDefault(ClassUtils.getRawType(params.getType().getType()), null);
            }
            return null;
        }
        return params.getResolutionEnvironment().valueMapper.fromInput(params.getInput(), params.getType());
    }
```
For my optional parameter params.isPresent() is false, thus the null value is given to my GraphQLQuery Method.

However, when I call the Method like this:


findObjects(queryConfig: null) {
 ...
}

then the isPresent check = true, which means the queryConfig = Optional.empty().

**It would be nice if Optional Parameters are never null, but instead only Empty Optionals!**

**Comment by kaqqao** [comment]
The current behavior is intentional, it enables you to distinguish between the cases when no value is provided vs when `null` value is provided. This disambiguation is very important for mutations that are expected to update the values based on user input. Additionally, this behavior is consistent with how Jackson/Gson deserialize optionals in objects.
See #197 for details.
