### ISSUE TITLE
Namespace collision on Inner Classes

### ISSUE THREAD

**Issue by jlkoszarek** [leangen/graphql-spqr#310]
If you have two classes with the same name for an inner class, only the the first Inner's attributes are visible in GQL. For example let's say you have two java classes Outer1 & Outer2, both Inner classes (one has a ID & one a Name:

```java
class Outer1 {
  class Inner {  public String getId() { return "Id1"; }  }
  public Inner getInner() { return new Inner();  }
}

class Outer2 {
  class Inner {  public String getName() { return "Name1"; }  }
  public Inner getInner() { return new Inner(); }
}
```

I believe that because SPQR is only using 'Inner' class name for GQL instead of 'Outer1.Inner' and 'Outer2.Inner', that a proper GQL query like Outer1.Inner.id works, but a Outer2.Inner.name doesn't, because it can't find the name attribute. 

Here is the error message I get back from SPQR GQL:

`{data: null,…}
data: null
errors: [{message: "Validation error of type FieldUndefined: Field 'name' in type 'Inner' is undefined",…}]
0: {message: "Validation error of type FieldUndefined: Field 'name' in type 'Inner' is undefined",…}
description: "Field 'name' in type 'Inner' is undefined"
errorType: "ValidationError"
extensions: null
locations: [{line: 5, column: 7}]
message: "Validation error of type FieldUndefined: Field 'name' in type 'Inner' is undefined"
path: null
validationErrorType: "FieldUndefined"`

Thx - For a great package and support!

**Comment by kaqqao** [comment]
This is true. Generally, ensuring the name uniqueness is on the user... Still, when a something looks like a collision, SPQR prints a warning during schema generation? Do you get this warning?

For inner types specifically, `Outer.Inner` pattern sounds like a non-surprising attempt at disambiguation, you I agree it should be added.

**Comment by TuomasKiviaho** [comment]
I am encountering the same issue when a 3rd party REST API contained a lot of classes named in a pattern akin to `FoobarRequest.Response` as roots. I managed to work around the issue by overriding `TypeInfoGenerator` `generateTypeName` and using `getClass().getName().substr(getPackage().getName().length())` while removing the $ separators for now.

BTW. Would dot even be allowed in the type name? (https://github.com/graphql/graphql-spec/issues/163).

***

A backwards compatible approach for customizing the names would be allow annotations of `io.leangen.graphql.annotations.types` to be declared also at package level (like JAXB `XmlJavaTypeAdapter`). This ways I could fix these names at `package-info.java` which would be less intrusive than annotating the classes themselves.

**Comment by TuomasKiviaho** [comment]
I tested the package level approach by patching the `DefaultTypeInfoGenerator` and introducing `GraphQLType` with `Class<?> type() default Void.class;`. All thanks to the `GenericTypeReflector` I managed to squeeze the change to a one-liner.

*** 
    private String generateSimpleName(AnnotatedType type, MessageBundle messageBundle) {
        Optional<String>[] names = new Optional[]{
                Optional.ofNullable(type.getAnnotation(GraphQLUnion.class))
                        .map(GraphQLUnion::name),
                Optional.ofNullable(type.getAnnotation(GraphQLInterface.class))
                        .map(GraphQLInterface::name),
                Optional.ofNullable(type.getAnnotation(GraphQLType.class))
                        .map(GraphQLType::name), 
                Optional.of(type).map(AnnotatedType::getType).map(GenericTypeReflector::erase)
                        .flatMap(rawType -> Arrays.stream(rawType.getPackage().getAnnotationsByType(GraphQLType.class))
                            .filter(annotation -> {
                                return annotation.type().equals(rawType);
                            }).findAny().map(GraphQLType::name))
        };
        return messageBundle.interpolate(getFirstNonEmptyOrDefault(names, () -> getSimpleName(ClassUtils.getRawType(type.getType()))));
    }

**Comment by kaqqao** [comment]
@jlkoszarek I've added new options to `DefaultTypeInfoGenerator` to enable easier generation of hierarchical names for nested types.

```java
//Generate a hierarchical name for *all* nested types
new DefaultTypeInfoGenerator().withHierarchicalNames()
```

or

```java
//Generate a hierarchical name for nested types, but *skip static types* (i.e. treat static types as top-level)
new DefaultTypeInfoGenerator().withHierarchicalNames(true)
```

These options are off by default, for backwards compatibility, but it's easy enough to enable. I hope that solves your issue.

@TuomasKiviaho I'll tackle your suggestions in a separate issue. But one question, in your example you still need to be able to modify the package, so you can't do this for 3rd party packages, right? Yet, you said that's exactly what you used it for... so I think I misunderstood something?

**Comment by TuomasKiviaho** [comment]
>  I'll tackle your suggestions in a separate issue. But one question, in your example you still need to be able to modify the package, so you can't do this for 3rd party packages, right?

Not without repackaging with maven-shader etc. or using a less intrusive approach such as OSGi fragments. Package info usually isn't used that much so declaring annotations there rather than on the classes themselves helps a lot when doing version bumps on the 3rd party libs
