### ISSUE TITLE
Complexity feature not work with multiple query in single request

### ISSUE THREAD

**Issue by mkswapnil** [leangen/graphql-spqr#313]
Current ComplexityAnalyzer work only with first query and calculate complexity of first query and validate against max complexity.
problem with design of method collectFields() in ComplexityAnalyzer class.
Does any one same issue ?

**Comment by ttyniwa** [comment]
Yes, and I fixed it.
I'll send PR later.

**Comment by kaqqao** [comment]
I was thinking of ditching the custom complexity analyzer completely and moving to [the one provided by graphql-java](https://github.com/graphql-java/graphql-java/blob/v13.0/src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java#L90).
It is not as precise in that it doesn't really deal with type-conditional queries. E.g.

```graphql
{
  pet {
    ... on Cat {
      catStuff
    }
    ... on Dog {
      dogStuff
    }
  }
}
```
will take into account the score for both `catStuff` and `dogStuff` and not only the most expensive one, like the current algorithm. It also has something [strange going on with the introspection query](https://spectrum.chat/graphql-java/general/how-is-the-complexity-of-the-complete-introspection-query-only-46~58f2dbd3-74ea-4541-a44b-e26d9ed89680). But, it is much simpler, and hopefully faster...

@mkswapnil @ttyniwa Would this be troublesome for you? Or is the simpler algo good enough?

**Comment by ttyniwa** [comment]
I'm developing schema with big interfaces which has 20-30 fields.
I'm planning to limit query by complexities, but not yet.
So, I can't answer this would be troublesome now.

**Comment by kaqqao** [comment]
I decided to keep the current algorithm more or less the same (as I find the default one too imprecise), but switch the implementation to the new APIs offered by graphql-java that are far more powerful and simpler to use that what was available when I made the original.

**Comment by kaqqao** [comment]
I fixed the immediate issue, but unfortunately due to [a bug](https://github.com/graphql-java/graphql-java/issues/1695) in graphql-java, I had to keep using the existing implementation for now. Once graphql-java fixed the issue, I'll replace the implementation.
