### ISSUE TITLE
how add metric? 

### ISSUE THREAD

**Issue by apan98** [leangen/graphql-spqr#317]
How add metrics for prometheus?

**Comment by kaqqao** [comment]
I have no idea what you're asking. You'll have to be a lot more specific if you want help. What kind of metrics, produces in what way, at what level, in what shape and sent how?

**Comment by apan98** [comment]
I`m use the libs: 
```
import io.micrometer.core.instrument.Metrics;
import io.micrometer.core.instrument.Timer;
```

```java
    @GraphQLQuery(name = "getCurrentUser", description = "get current user")
    public CurrentUserGraphModel getCurrentUser() {
            Timer.Sample timerSample = Timer.start(Metrics.globalRegistry); // start metric 

            UserModel userModel = userService.getCurrentUser();
            CurrentUserGraphModel user =  currentUserGraphModelFactory.build(userModel);

            timerSample.stop(Timer .builder("getCurrentUser").register(Metrics.globalRegistry));// end metric
           return user;
    }
```
block "start metric" and block "end metric" used in all graphQL query methods. With Spring possible use filters, and then what? Tried through Spring AOP, but it  not work, spqr verify on proxy class.

I don't want to copy & paste, the blocks. How add the metrics for all method which are marked `@GraphQLQuery`, without copy & paste?

**Comment by kaqqao** [comment]
You can use all Spring features normally (and if there's a feature for what you need, I recommend going that way). SPQR doesn't prevent the usage of proxies, it only forces you to register the bean types explicitly e.g.

```java
generator.withOperationsFromSingleton(beanInstance, BeanType.class)
```
instead of just

```java
generator.withOperationsFromSingleton(beanInstance)
```

It gets a bit trickier with generic types, but the logic is the same. You just need to use `TypeToken` on `TypeFactory` to capture the generic type of the bean.
If you're using SPQR Spring Boot Starter, all this happens automatically.

You can also use graphql-java's `Instrumentation` for this purpose.

```java
public static class TimerInstrumentation implements Instrumentation {

        @Override
        //Executed just before resolving a field
        public InstrumentationContext<Object> beginFieldFetch(InstrumentationFieldFetchParameters parameters) {
            Timer.Sample timerSample = Timer.start(Metrics.globalRegistry); // start metric
            return new InstrumentationContext<Object>() {

                @Override
                public void onDispatched(CompletableFuture<Object> result) {
                    //you can also call timerSample.stop here if you don't use async resolvers
                }

                @Override
                public void onCompleted(Object result, Throwable t) {
                    timerSample.stop(Timer .builder("getCurrentUser").register(Metrics.globalRegistry));// end metric
                }
            };
        }
    }
```
Then register it when creating the `GraphQL` object:

```java
GraphQL runtime = GraphQL.newGraphQL(schema)
        .instrumentation(new TimerInstrumentation())
        .build();
```

You can also use SPQR's own interceptors like this:

```java
private static class TimerInterceptor implements ResolverInterceptor {

    @Override
    public Object aroundInvoke(InvocationContext context, Continuation continuation) throws Exception {
        Timer.Sample timerSample = Timer.start(Metrics.globalRegistry); // start metric 
        Object result = continuation.proceed(context); //execute the resolver. maybe add try/catch?
        timerSample.stop(Timer .builder("getCurrentUser").register(Metrics.globalRegistry));// end metric
       return result;
    }
}
```

and then register this interceptor:

```java
generator.withResolverInterceptors(new TimerInterceptor())
```

**Comment by kaqqao** [comment]
I fixed my example to apply to annotated resolvers only, not _all resolvers_.

**Comment by kaqqao** [comment]
Judging by the reactions, it seems like this helped you. I'll close the issue now, but if there's anything else, please feel free to reopen.
