### ISSUE TITLE
UUID id is quoted after update to 0.10.0

### ISSUE THREAD

**Issue by JohannesFluegel** [leangen/graphql-spqr#319]
Given
```
@GraphQLType
public class MyEntity {
  @GraphQLId
  private UUID id;
```
In 0.9.9 a query returns the id 
```
"id": "d5478358-5ecd-4ba5-af9f-b8175473f925"
```
But in 0.10.0 it is additionally quoted:
```
"id": "\"d5478358-5ecd-4ba5-af9f-b8175473f925\""
```

**Comment by jwlsh** [comment]
You may be able to work around this by changing the setters & getters for the ID fields to the following:

        @GraphQLId
	public String getId() {
		return id.toString();
	}
	@GraphQLInputField
	public void setId(UUID id) {
		this.id = id;
	}

**Comment by activey** [comment]
Come on, is this serious?

**Comment by kaqqao** [comment]
@activey A PR fixing this would have been much more useful.
