### ISSUE TITLE
SPQR not picking its annotations from within the jar

### ISSUE THREAD

**Issue by pulgupta** [leangen/graphql-spqr#323]
Hi All,

We have a common jar in which we keep all our entity models.
Within the same model classes we have added SPQR annotations(Example: @GraphQLType) to specify GraphQL schema details. The issue is that when the schema is getting generated it is scanning the classes but it is not processing the annotations.

Any idea what we are missing here?

**Comment by kaqqao** [comment]
Yes. It is 100% a class loading issue. You likely have SPQR jar in 2 different places and the annotation classes get loaded twice by 2 different class loaders.
If you have an EAR, you probably have it once in the EAR itself and once in the contained web app. Even if it's not an EAR, it's a similar issue. This has been asked numerous times.

You can place a breakpoint somewhere where it looks for the annotations (e.g. [here](https://github.com/leangen/graphql-spqr/blob/634dde38fa4c015f03c4cfb74e14a32bbcc03d47/src/main/java/io/leangen/graphql/metadata/strategy/type/DefaultTypeInfoGenerator.java#L154)) and see for yourself if the annotation on the type and the annotation class it looks for have different class loaders.

**Comment by kaqqao** [comment]
There was also a similar issue [here](https://github.com/leangen/graphql-spqr/issues/282#issuecomment-518235224).

**Comment by pulgupta** [comment]
Thanks, @kaqqao You are right. I had a jar which also had SPQR inside it. Thanks for helping me out. I will close this issue. We are using SPQR with Micronaut and till now we are super satisfied by SPQR features.
