### ISSUE TITLE
Support Interface for Input Types

### ISSUE THREAD

**Issue by janithkv** [leangen/graphql-spqr#325]
GraphQL spec supports interfaces for input types.
https://graphql.github.io/graphql-spec/June2018/#sec-Input-Object-Extensions

Looks like this is not supported in spqr. Is this something you have in pipeline, also would you have any recommendations on how to overcome this limitation in the current library ?

**Comment by kaqqao** [comment]
You're misunderstanding the spec. It speaks about the `extends` keyword which simply appends more fields to an existing type. You're achieving the same in Java by inheriting fields from a parent type. It has nothing to do with interfaces as inputs. Even if the spec did allow this, it wouldn't be up to SPQR to support it. SPQR merely generates a schema. It is graphql-java that actually implements the spec.
