### ISSUE TITLE
can u release new lib on Maven Central

### ISSUE THREAD

**Issue by Maclaon** [leangen/graphql-spqr#327]
can u release new lib  on [Maven Central](https://search.maven.org/search?q=g:io.leangen.graphql%20AND%20a:spqr) for issue of [Namespace collision on Inner Classes](https://github.com/leangen/graphql-spqr/issues/310) ,because i can not find `new DefaultTypeInfoGenerator().withHierarchicalNames(true)` in `<version>0.10.0</version>`

**Comment by kaqqao** [comment]
v0.10.1 is out, might take a bit to sync to Maven Central
