### ISSUE TITLE
GraphQL Playground not autocompleting

### ISSUE THREAD

**Issue by danrix89** [leangen/graphql-spqr#329]
I noticed that once I added the following "bean" to my application class, I'm no longer seeing docs or schemas in GraphQL Playground (`localhost:8080/gui`) and playground is saying "Server cannot be reached".

> NOTE: I'm using Kotlin (it shouldn't make a difference though)

```kotlin
    @Bean
    fun graphQL(schema: GraphQLSchema): GraphQL {
        return GraphQL.newGraphQL(schema)
                .instrumentation(ComplexityAnalysisInstrumentation(JavaScriptEvaluator(), 10)) // arbitrary number
                .queryExecutionStrategy(AsyncExecutionStrategy(CustomExceptionHandler()))
                .mutationExecutionStrategy(AsyncSerialExecutionStrategy(CustomExceptionHandler()))
                .build()
    }
```
I ran this through the debugger and the `schema` that is supplied has all the queries/mutations that I've annotated with `@GraphQLQuery` and such, so I know the schema is correct, but it's not getting picked up by GraphQL Playground.

I also tried to look at how the spqr `GuiController` is being initialized to see if my websocket endpoint isn't correct, but that checks out.

I'm assuming that by me supplying my own `GraphQL` instead of using the default one that is generated by the spqr, the schema isn't getting pushed to GraphQL Playground.

Any help on this would be greatly appreciated :)

**Comment by danrix89** [comment]
So I narrowed it down to the line that I'm adding the complexity instrumentation. So the following works:

```kotlin
    @Bean
    fun graphQL(schema: GraphQLSchema): GraphQL {
        return GraphQL.newGraphQL(schema)
//                .instrumentation(ComplexityAnalysisInstrumentation(complexityExpressionEvaluator(), 5))
                .queryExecutionStrategy(AsyncExecutionStrategy(CustomExceptionHandler()))
                .mutationExecutionStrategy(AsyncSerialExecutionStrategy(CustomExceptionHandler()))
                .build()
    }
```

Does adding complexity affect the schema somehow, causing GraphQL Playground to not show the docs/schema?

**Comment by kaqqao** [comment]
Yes, of course. Complexity limit applies to _all_ queries, introspection query included. A full introspection query scores a little over 100 in complexity, so setting a limit below that will cause introspection to be rejected.

Also, please note that this project of the core library. Please open Spring Starter issues in that project instead.

**Comment by kaqqao** [comment]
Btw, if my response did not address your issue, feel free to reopen this.
