### ISSUE TITLE
Returning Either<T, A>

### ISSUE THREAD

**Issue by pabloparada** [leangen/graphql-spqr#33]
Hi,

I'm using varv.io library and I would like to return a Either<Throwable, T> from query methods. What should I write or plug-in to enable this?

Thank you.

**Comment by kaqqao** [comment]
I'm on vacation and away from a computer for 2 weeks, so can give a very detailed answer, but it should be a straightforward task once you know how the underlying mechanism works.

So, the interfaces you care about here are `TypeMapper`  (drives the way a Java type is mapped to a GraphQL type), `InputConverter` which drives how inputs received from the client are converted into the appropriate type and `OutputConverter` driving the way a resulting Java object is converted into a value that is to be serialized and returned to the client.

What I suggest you do is implement a `TypeMapper` that `supports` `Either` type (e.g. its `supports` method returns `true` only for `Either`) and maps it into a GraphQL Union type (as it's the perfect use-case) of the left and the right type of `Either`. The associated `TypeResolver` would make decisions based on whether the `Either` instance is a left or a right.
This means you can't use `Either` as an input as unions are not valid inputs but that sounds right anyway as it likely the correct thing to do in your case. Your `TypeMapper` should throw an exception inside `toGraphQLInputType`.
Finally, just register the custom mapper with the generator, e.g. `generator.withTypeMapper(..).withDefaultMappers()`.

If you don't want to map it to a union, but some other custom object, you'll also need to implement `OutputConverter` to turn instances of `Either` into that structure. And if you want to allow using `Either` as an input, you'll need `InputConverter` as well to turn that structure back into an `Either`.

Tell me how far you get and I'll help you out if you get stuck.

**Comment by pabloparada** [comment]
Thanks @kaqqao. I'll try it as soon as possible.

**Comment by kaqqao** [comment]
Aaargh, I accidentally deleted my answer 😣

**Comment by pabloparada** [comment]
I'm implemeting the solution right now. That's fine.

**Comment by pabloparada** [comment]
Hi,

Im stuck with non-unique name error. I'm posting typemapper code so you can see.

public class EitherTypeMapper implements TypeMapper {
    @Override
    public GraphQLOutputType toGraphQLType(AnnotatedType javaType, Set<Type> abstractTypes, OperationMapper operationMapper, BuildContext buildContext) {
        final Tuple2<AnnotatedType, AnnotatedType> types = getElementTypes(javaType);

        final List<GraphQLOutputType> outputTypes = Arrays.asList(operationMapper.toGraphQLType(types._1, abstractTypes, buildContext),
                                                                  operationMapper.toGraphQLType(types._2, abstractTypes, buildContext));

        final GraphQLOutputType outputType = new GraphQLUnionType(getName(outputTypes), "", outputTypes, buildContext.typeResolver);

        return outputType;
    }

    @Override
    public GraphQLInputType toGraphQLInputType(AnnotatedType javaType, Set<Type> abstractTypes, OperationMapper operationMapper, BuildContext buildContext) {
        throw new GraphQLException("Unable to build Either type from input parameters");
    }

    @Override
    public boolean supports(AnnotatedType type) {
        return GenericTypeReflector.isSuperType(Either.class, type.getType());
    }

    private Tuple2<AnnotatedType, AnnotatedType> getElementTypes(AnnotatedType javaType) {
        final TypeVariable<Class<Either>>[] typeParameters = Either.class.getTypeParameters();

        final AnnotatedType left = GenericTypeReflector.getTypeParameter(javaType, typeParameters[0]);
        final AnnotatedType right = GenericTypeReflector.getTypeParameter(javaType, typeParameters[1]);

        return Tuple.of(left, right);
    }

    private String getName(final List<GraphQLOutputType> outputTypes) {
        return "Either" + outputTypes.stream()
                                      .map(GraphQLOutputType::getName)
                                      .reduce("", (acc, next) -> acc + "Or" + next);
    }
}
`

Exception says 

`graphql.AssertException: All types within a GraphQL schema must have unique names. No two provided types may have the same name.
No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types)`

**Comment by kaqqao** [comment]
Ah, yes. You sadly must keep track of the types you have already mapped and
return cached values. The cache is already available in `BuildContext`
(fields `knownTypes` and `knownInputTypes`, I think). There's a helper
class `CachingTypeMapper` which you try using, or see how it uses the cache.
I may have got some class/field names wrong because, crazily enough, I
don't have the code anywhere accessible and can't even get to GitHub
(writing this through email).

**Comment by kaqqao** [comment]
@pabloparada Have you managed to solve this or do you need additional help/clarification?
Can I close the issue?

**Comment by pabloparada** [comment]
@kaqqao I did solve it. Thank you.
