### ISSUE TITLE
Optional with @GraphQLArgument.defaultValue throws CoercingSerializeException

### ISSUE THREAD

**Issue by Ernio3** [leangen/graphql-spqr#331]
So according to update 0.9.9 Optionals are supported - **and they are**, but combined with defaultValue they throw schema errors during introspection (feature itself works, but introspection doesn't).

If we were to mark any argument with both, like below:
```
@GraphQLArgument(name = "var", defaultValue = "1") Optional<Integer> var
```
We will get:
```
`graphql.schema.CoercingSerializeException: Expected type 'Int' but was 'Optional'.`
```

Can someone confirm this issue? Introspection call can be easily tested with playground GUI which does it to get Schema.

This bug effectively makes development HARD, as I am unable to introspect Schema.

**Comment by kaqqao** [comment]
No longer sure about 0.9.9 but this works as expected in 0.10.0. If you're stuck on 0.9.9 because of the Spring Starter, I'm aiming to upgrade it and release the next version in the following couple of days.

**Comment by kaqqao** [comment]
Sorry for the lack of activity, both projects were on a hiatus. I'm cleaning up the backlog and trying to get things back on track. I'll close this as it's about an earlier version. I'll revive the Spring Starter project too as soon as I can.
