### ISSUE TITLE
How to disable javax.validation checks?

### ISSUE THREAD

**Issue by austinarbor** [leangen/graphql-spqr#334]
Right now `javax.validation` annotations are being enforced on the schema for mutations, so if something is `@NotNull`, it must be included in the mutation.  How can I turn this feature off?  I am using these annotations for validation on the persistence layer, however, when sending mutations from GraphQL some of the data can be missing  because it either gets generated in the backend (such as a UUID) or in the case of a partial update, only modified data is being sent. I do not have `@Validated` on the class containing the graphql queries/mutations...

**Comment by austinarbor** [comment]
For now, I am "hacking" the`NonNullMapper` before it gets initialized...

```java
try {
  Field f = NonNullMapper.class.getDeclaredField("COMMON_NON_NULL_ANNOTATIONS");
  f.setAccessible(true);
  Field modifiersField = Field.class.getDeclaredField("modifiers");
  modifiersField.setAccessible(true);
  modifiersField.setInt(f, f.getModifiers() & ~Modifier.FINAL);
   f.set(null, new String[]{});
 } catch (Exception e) {
   log.error("Exception getting field", e);
}
```

**Comment by retrodaredevil** [comment]
It looks live you've figured out all the NonNull validation stuff happens in the `NonNullMapper` class.

This is included by default as a type mapper. To remove it, you can do something like this:

```java
GraphQLSchema schema = new GraphQLSchemaGenerator()
        ...
        .withTypeMappers((config, defaults) -> { defaults.removeIf(typeMapper -> typeMapper instanceof NonNullMapper); return defaults; })
        ...
        .generate();

```

I haven't tested that, but it should work.

I think the more long term solution would be to have a way to more easily edit the non null annotations, maybe with a way similar to how `withValueMapperFactor()` works to edit the configuration of the default `ValueMapperFactory`.

**Comment by austinarbor** [comment]
@retrodaredevil thanks for the suggestions, however, your solution isn't totally working for me, I think the issue is: https://github.com/leangen/graphql-spqr/blob/master/src/main/java/io/leangen/graphql/GraphQLSchemaGenerator.java#L902 , so we also need to remove from the schema transformers.  The problem with this though is there are a lot of calls to the private method `shouldWrap(GraphQLType type, TypedElement typedElement)` inside of `NonNullMapper` which reference the list of non null annotations to check. If this method can be made protected, that would make your overriding proposal easier.

So my final working solution with your guidance:
```java
gen.withTypeMappers((config, defaults) -> defaults.replace(NonNullMapper.class, nnm -> new CustomNonNullMapper()));
gen.withSchemaTransformers((config, defaults) -> defaults.replace(NonNullMapper.class, nnm -> new CustomNonNullMapper()));
```
With `CustomNonNullMapper` being a copy+paste of `NonNullMapper`, except 
```java
this.nonNullAnnotations = Set.of(io.leangen.graphql.annotations.GraphQLNonNull.class);
```

**Comment by retrodaredevil** [comment]
I'm glad you got it working. I didn't realize you also had to change the schema transformers. I only pasted in my solution and noticed most of the "not null"s disappeared.

**Comment by InnuceEAN** [comment]
Can we maybe get a configuration option for COMMON_NON_NULL_ANNOTATIONS?

**Comment by austinarbor** [comment]
> Can we maybe get a configuration option for COMMON_NON_NULL_ANNOTATIONS?
I agree, should be easy enough to just have a constructor accept a list of annotations etc and then you can pass the instance into the config.

**Comment by kaqqao** [comment]
I'll split the nonnull mapper into 2, one dealing with validation annotations and the other with the rest, so that they can be disabled separately.

**Comment by kaqqao** [comment]
Changes from #472 make it so that validation annotations only affect mapping if no group is specified or a group is explicitly enabled.

**Comment by kaqqao** [comment]
`@Validated` doesn't really work for schema mapping. Imagine this situation:

```java
public class BookService {

    //Not @Validated
    @GraphQLQuery
    public List<Book> books() {...}
    
    @Validated
    @GraphQLMutation
    public Book insertBook(Book book) {...}
}

public class Book {
    @NotBlank //Does this affect the schema?
    public String title;
}
```

Should `Book.title` be nullable or not, since the validation rules are different per context (and this can be made so much worse by adding validation groups)? It can't be both at the same time without creating 2 different `Book` types, which would lead to horrible mapping complexity (speaking from experience, this feature existed in SPQR). For this reason, I believe #472 goes as far as it is reasonable.

I'll close this issue now, but if anyone has other suggestions around validation rules and schema mapping, feel free to reopen or start a new one.
