### ISSUE TITLE
How to mark boolean field as not required in schema

### ISSUE THREAD

**Issue by lirugo** [leangen/graphql-spqr#335]
How to mark boolean field as not required in schema?

In java we create a class

```
@Entity
@Table(name="usr")
@Getter @Setter
public class User implements UserDetails {
    @Id @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Column(unique = true)
    @NotBlank(message = "Email is required")
    private String email;

    @Column(name = "email_confirmed", columnDefinition = "boolean default false", nullable = true)
    @GraphQLIgnore
    private boolean emailConfirmed;
}
```

And we have a auto generated grapql schema
```
type User {
  id: Int
  email: String
  emailConfirmed: Boolean!
}
```

So for mark field as nonNull we have annotation @GraphQLNonNull
But boolean fields is always is required "Boolean!"
How we can create in schema emailConfirmed: Boolean

Thanks

**Comment by kaqqao** [comment]
You can add `@GraphQLInputField(defaultValue = "false")`, so it has a default value, or make it a `Boolean`.
I'm looking into changing this behavior a little so that object fields are not automatically non-null, but top-level arguments are.

**Comment by lirugo** [comment]
Thanks i can set a default with annotation `@GraphQLInputField(default Value = "false")`

But i not fully understend how can i make it a `Boolean`
By default it is `Boolean!` and i cant find a way how i can mark it to `Boolean`
its possible?
Thanks again

**Comment by kaqqao** [comment]
Oh, sorry for the confusion. I meant in Java, make it `Boolean` as opposed to `boolean`. The auto-non-null logic applies to primitives only. But adding the default is likely less invasive anyway.

**Comment by lirugo** [comment]
Great
its work:))
Thank you
