### ISSUE TITLE
Incompatibility with graphql-java 14.0

### ISSUE THREAD

**Issue by psyklopz** [leangen/graphql-spqr#337]
The constructor for Generator/TypeCache expects all objects of GraphQLType to have a getName() method.  Which in previous versions (13 and before) of graphql-java this was true.  In version 14, only the subclass GraphQLNamedType supports the getName() method.  This is causing me dependency injection issues, now that another component is forcing gradle to update graphql-java to version 14.

https://github.com/leangen/graphql-spqr/blob/df15e5b702fa010b802ca35c5fddde84299c2505/src/main/java/io/leangen/graphql/generator/TypeCache.java#L19

See the change in version 14.
https://github.com/graphql-java/graphql-java/blob/578985f4ed81d154f1f83bbef6903aa88f3f1a59/src/main/java/graphql/schema/GraphQLType.java

Is it possible to support graphql-java version 14?  With a little direction, I would be willing to get a PR together that addresses this issue.

**Comment by kaqqao** [comment]
Unfortunately, graphql-java v14 has a ton of breaking changes... so quite a few places needed work. The new API requires so much explicit casting everywhere it's painful to use 😖
Anyway, I have already prepared for this ahead of the v14 release, and pushed the code just now.

As a general rule, though: never ever expect you can just upgrade graphql-java and have things working with SPQR. All graphql-java releases have breaking changes, and even if everything _seems_ to work, there's no guarantees.

Just out of curiosity, what is forcing you to update to v14?

**Comment by biancaL** [comment]
> Unfortunately, graphql-java v14 has a ton of breaking changes... so quite a few places needed work. The new API requires so much explicit casting everywhere it's painful to use 
> Anyway, I have already prepared for this ahead of the v14 release, and pushed the code just now.
> 
> As a general rule, though: never ever expect you can just upgrade graphql-java and have things working with SPQR. All graphql-java releases have breaking changes, and even if everything _seems_ to work, there's no guarantees.
> 
> Just out of curiosity, what is forcing you to update to v14?


I have updated to the latest version of spqr (0.10.1) and the issue does not seem to fixed.

 java.lang.NoSuchMethodError: graphql.schema.GraphQLType.getName()Ljava/lang/String;
	at io.leangen.graphql.generator.TypeCache.<init>(TypeCache.java:19)
	at io.leangen.graphql.generator.BuildContext.<init>(BuildContext.java:106)
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:992)


I need the 14 version of graphql-java for apollo-federation. 

Are there any plans on fixing this?

**Comment by EXPEvgowdaks** [comment]
I guess, changes went into 0.10.2-SNAPSHOT, when would be the release of `0.10.2`?

**Comment by kristofarkas** [comment]
Is there a plan to release 0.10.2 with graphql-java v14 support?
