### ISSUE TITLE
how remove stacktrace for any exception? 

### ISSUE THREAD

**Issue by apan98** [leangen/graphql-spqr#339]
how remove stacktrace in response for anything  exception?

**Comment by kaqqao** [comment]
How are you getting stack traces in the response in the first place? SPQR itself does not deal with transport, encoding, or anything else, so I have no idea what you send, where and why.

Do you call `ExecutionResult#toSpecification`?

**Comment by kaqqao** [comment]
Closing this as there has been no response for almost a year. Feel free to reopen if still relevant.
