### ISSUE TITLE
Returning CompletableFuture<T>

### ISSUE THREAD

**Issue by pabloparada** [leangen/graphql-spqr#34]
How can I return a CompletableFuture<T>? Is graphql-spqr capable of chaining futures in async manner?

Thank you.

**Comment by kaqqao** [comment]
Right now, it's unfortunately not possible as spqr doesn't yet support
graphql-java 4+. On the positive, adding support shouldn't be too difficult
and I plan to work on this once I'm back from vacation, which is in 2 weeks.

**Comment by pabloparada** [comment]
Thank you @kaqqao.
