### ISSUE TITLE
How to add additional query to class without putting query in class

### ISSUE THREAD

**Issue by retrodaredevil** [leangen/graphql-spqr#351]
I'm trying to figure out the best way to add an additional query to a class. Let's say I have this interface:

```
interface StatusPacket {
    // other methods

    int getTemperature(); // in celsius
}
```
Now it has the "temperature" value that can be queried, but I also want to add a "temperatureFahrenheit" value that can be queried.

It would be very simple to add a default method and have it query that, but I want to define this method somewhere else. So let's say I have this method:
```
static float getTemperatureFahrenheit(StatusPacket statusPacket) {
    return statusPacket.getTemperature() * 1.8 + 32;
}
```
How would I add that method to the query so I can also query "temperatureFahrenheit"? Preferably by passing a value to my `GraphQLSchemaGenerator` and not touching the `StatusPacket` class.

Is this a way to do this without creating my own `ResolverBuilder`?

**Comment by kaqqao** [comment]
Take a look at the `@GraphQLContext` annotation. It lets you do exactly that.
Any registered bean can add a nested query using something like:

```java
@GraphQLQuery
public float getTemperatureFahrenheit(@GraphQLContext StatusPacket statusPacket) {
    return statusPacket.getTemperature() * 1.8 + 32;
}
```

**Comment by retrodaredevil** [comment]
Thanks. I don't know how I missed that.
