### ISSUE TITLE
Possibility of default GraphQL error handling (GraphQLEndpoint)

### ISSUE THREAD

**Issue by mschoeffel** [leangen/graphql-spqr#354]
**Problem:**
When using this project to generate the GraphQL endpoints automatically, there is no possibility to get access to the `GraphQLEndpoint`.
But if you want to implement custom error handling you need to have access to it.
See the official documentation regarding custom error handling: https://www.howtographql.com/graphql-java/7-error-handling/

**Question:**
Is there any way I could get access to the `GraphQLEndpoint` or any other possibility to implement custom error handling or register a custom error handler and still use this awesome project? 

I don't want to get the `locations` and `path` get returned inside the `errors` Array if an exception is thrown and change the `message` to a more meaningful one than "Exception while fetching data...". 

I haven't found any example or documentation regarding this problem.

**Further Information:** 
I used the plain examples from your repo and tried to implement custom error handling following the GraphQL documentation: 
Examples: https://github.com/leangen/graphql-spqr-samples
Documentation: https://www.howtographql.com/graphql-java/7-error-handling/

Thanks a lot in advance!
Best regards,
MSchoeffel

**Comment by kaqqao** [comment]
First and foremost, the tutorial HowToGraphQL is horrendously outdated, please never ever use it in its current state.
Secondly, `GraphQLEndpoint` comes from `graphql-java-servlet`, that this project has nothing to do with. It very likely entirely possible to use them together just fine, but I have not done it myself in years and have no clue what customizations do they offer. I'd whole heartedly recommend using [SPQR Spring Starter](https://github.com/leangen/graphql-spqr-spring-boot-starter), as it offers deep integration with SPQR out of the box.

As for error handling, you have many options, depending on what you're looking for. You can for example register a custom `ResolverInterceptor` that would catch exceptions and wrap them into a `DataFetcherResult`. See [this test](https://github.com/leangen/graphql-spqr/blob/graphql-spqr-v0.11.1/src/test/java/io/leangen/graphql/InterceptorTest.java) for an example of using interceptors.

You can also just use graphql-java APIs directly, and register a custom `DataFetcherExceptionHandler`.
```java
GraphQL executor = GraphQL.newGraphQL(schema)
                .defaultDataFetcherExceptionHandler(new CustomDataFetcherExceptionHandler())
                .build();
```

Finally, if you're using SPQR Spring Starter, you can also customize how operations are executed and what is returned by providing a custom `GraphQLServletExecutor` that transforms the response before returning it. Just wire your custom impl as a bean.
