### ISSUE TITLE
How to use a ResolverInterceptor on a non-@GraphQLQuery method?

### ISSUE THREAD

**Issue by C2D03041** [leangen/graphql-spqr#357]
Hello,

Apologies up front, Java is not my best language, so I may just be missing some obvious detail. I am trying to use a ResolverInterceptor on a non-`@GraphQLQuery` method. I wish to modularize a large method into multiple sub-functions, and those pieces will have different authorization requirements. Here is a simplified but complete version of my use case:

```java
@Service
@GraphQLApi
public class TestService {

	@GraphQLQuery
	public String getTest() {
		String privateReturn = privateGetTest();
		System.out.println("Private return: "+privateReturn); // this never runs
		return privateReturn;
	}

	@AuthGuard(requireLogin = true)
	private String privateGetTest() {
		return "hello";
	}
}
```
```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.FIELD})
public @interface AuthGuard {
	boolean requireLogin() default true;
}
```
```java
@Service
public class AuthInterceptor implements ResolverInterceptor {
	@Autowired
	private AuthenticationService authenticationService;

	@Override
	public Object aroundInvoke(InvocationContext invocationContext, Continuation continuation) throws Exception {
		System.out.println("Got Executable: " + invocationContext.getResolver().getExecutable());
		System.out.println("Got Delegate: " + invocationContext.getResolver().getExecutable().getDelegate());
		System.out.println("Operation name: " + invocationContext.getResolver().getOperationName());
		System.out.println("Operation name2: " + invocationContext.getOperation().getName());
		AuthGuard auth = invocationContext.getResolver().getExecutable().getDelegate().getAnnotation(AuthGuard.class);
		// I expect "auth" to be not null
		return "this should override the return from privateGetTest";
	}
}
```

And hitting the `test` graphql resolver returns "this should override the return from privateGetTest", with this console output:

```
Got Executable: public java.lang.String com.blah.TestService.getTest()
Got Delegate: public java.lang.String com.blah.TestService.getTest()
Operation name: test
Operation name2: test
Got Guard: null
```

Expected console output:

```
Got Executable: public java.lang.String com.blah.TestService.getTest()
Got Delegate: public java.lang.String com.blah.TestService.getTest()
Operation name: test
Operation name2: privateGetTest
Got Guard: (some non null)
Private return: this should override the return from privateGetTest
```

I want access to the annotation object because I'm using the flags on the object to determine what authorization to perform (simple login check, specific permissions, filtering the result, etc).  I was parroting [the process from the unit tests for fetching the annotation object](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/InterceptorTest.java#L100):

```java
Auth auth = context.getResolver().getExecutable().getDelegate().getAnnotation(Auth.class);
```

 I could work around this using multiple annotations, but I'd prefer not to. I don't want to complicate my GraphQL Schema with multiple `@GraphQLQuery` endpoints as it doesn't make sense for clients to understand this internal detail.

But I see from running that my above code that all arrows seem to point to the main resolver entry function instead of the function that is annotated, which makes me think  that this form of modularization with ResolverInterceptors is not a supported use case. I also don't see a test for this use case.

If this is indeed not a supported use case, please advise on what routes I should consider alternatively. I originally implemented this with spring-security's method level security, but that solution was a bit over-engineered for my needs. I just need a little bit of arbitrary code before and after a method execution, with access to modify the method result, and I believed that ResolverInterceptors fit that description well.

**Comment by kaqqao** [comment]
SPQR has no control over nor insight into the methods invoked internally... Nothing except Java runtime itself has that info, so nothing can intercept such an invocation. Only some deeper magic like a byte code instrumentation could weave custom logic around methods like that... and that's really out of SPQR's scope...
So unfortunately you're stuck with protecting the exposed method only. Or perhaps investigating into ByteBuddy, Javassist or alike... but I honestly would stay away from dark magic especially for security related code.
