### ISSUE TITLE
Kotlin remark in the README file

### ISSUE THREAD

**Issue by Czocher** [leangen/graphql-spqr#358]
Hello,
I had a look at the Kotlin issue mentioned in the README file and from what I noticed basic support for type annotations [was merged](https://youtrack.jetbrains.com/issue/KT-35843) in Kotlin version 1.3.70. I believe that should actually be enough to support most (if not all) use cases required by this library.
Maybe a README update is required after a proper retest if this claim is in fact correct? I understand that Kotlin is a non-goal of this project. The README update would just make this project look less scary for people who actually use Kotlin.

**Comment by pep1** [comment]
In case somebody like me ends up in here trying to get `TYPE_USE` annotations handling working in Kotlin.

The basic support for type annotation as pointed out by @Czocher seems to work nicely when activated with the arg `-Xemit-jvm-type-annotations` during compilation :tada: , e.g. in Maven with:
```
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>1.3.72</version>
                <configuration>
                    <jvmTarget>${java.version}</jvmTarget>
                    <javaParameters>true</javaParameters>
                    <args>
                        ...
                        <arg>-Xemit-jvm-type-annotations</arg><!-- this line here -->
                    </args>
                    ...
                </configuration>
            </plugin>
```

In my case this fixed an issue where I couldn't get '@GraphQLId` and its processing in `IdAdapter` working. With that compiler arg it works as expected with something like:
```
  var id: @GraphQLId(relayId = true) Int? = null,
```
I am guessing this would fix issue with other annotations as well, not tested yet though.

Further details regarding the Kotlin feature here https://youtrack.jetbrains.com/issue/KT-13228 and here https://youtrack.jetbrains.com/issue/KT-35843

Hope that helps

**Comment by kaqqao** [comment]
Reworded the Kotlin info in README
