### ISSUE TITLE
Question: Generate GraphQL schema with just Types?

### ISSUE THREAD

**Issue by mrFatDZ** [leangen/graphql-spqr#364]
Hello,

Is it possible to generate a simple schema based on a Java POJO without including any queries/mutations via GraphQLSchemaGenerator?

I tried the following:

```java
@GraphQLType
public class TestPojo
{

    private String test;

    public String getTest()
    {
        return test;
    }
}
```

and Schema generation code snippet:
```java
return new GraphQLSchemaGenerator()
                .withBasePackages( "com.xyz" )
                .withOperationsFromTypes( TestPojo.class )
                .generate();
````

Is there any way to accomplish something like this? 
When I create a simple TestQuery class and include the TestPojo object as a return type which is annotated with ```@GraphQLQuery```, I get the TestPojo type along with the query as expected. 
I simply would like to build a schema where there are no queries but only types. Is this possible?

Thanks!

**Comment by ItayBleicherSela** [comment]
Hi dude i have the same problem, did you manage it out ?

**Comment by kaqqao** [comment]
No, I'm afraid not... SPQR needs an entry point to start discovering types from. These are the top level beans/types that you register with the schema generator.
I'll take a look if I can add something. But I'm curious, what's the use-case? Since this will not produce an actually executable schema, which is the main purpose of SPQR. I'm guessing you'd use the produced schema as an input for some other tool, or maybe for some sort of stitching?

**Comment by kaqqao** [comment]
Btw, according to the spec (at least currently, will likely be relaxed), the schema _must_ contain the query type. So at least _some_ dummy must be added anyway.

**Comment by kaqqao** [comment]
One thing that comes to mind: you could abuse implementation auto-discovery mechanism to pretend all your classes you want to add are implementation of some empty (marker) interface. That way you only need to make a single dummy top-level (query) field to satisfy the validator, and not a field per type.

E.g.

```java
GraphQLSchema schema = new GraphQLSchemaGenerator()
                .withOperationsFromSingleton(new Dummy())
                .withImplementationDiscoveryStrategy(new TypeFinder(TestPojo.class, OtherPojo.class))
                .generate();

...

//You don't need to change this when adding more types to the schema
public class Dummy {

        @GraphQLQuery
        public Union dummy() {
            return null;
        }

        //Dummy type that will act as a union of all types you actually want to register
        @GraphQLUnion(name = "DummyUnion", possibleTypeAutoDiscovery = true)
        public interface Union {}
    }

    public class TypeFinder extends DefaultImplementationDiscoveryStrategy {

        private final List<AnnotatedType> typesToAdd;

        private TypeFinder(Class... classesToAdd) {
            this.typesToAdd = Arrays.stream(classesToAdd)
                    .map(GenericTypeReflector::annotate)
                    .collect(Collectors.toList());
        }

        @Override
        public List<AnnotatedType> findImplementations(AnnotatedType type, boolean autoDiscover, String[] scanPackages, BuildContext buildContext) {
            //Pretend all classes you added participate in the Dummy union
            if (type.getType().equals(Dummy.Union.class)) {
                return typesToAdd;
            }
            return super.findImplementations(type, autoDiscover, scanPackages, buildContext);
        }
    }

    public static class TestPojo {

        private String test;

        public String getTest()
        {
            return test;
        }
    }
```

**Comment by mrFatDZ** [comment]
We have a legacy JMS Java API that we want to expose existing POJOs from as GraphQL types to our new frontend. Our frontend application connects to the same legacy application via parallel WS and we pipe the messages to the same JMS broker. We wanted our application to download the schema files containing GQL Types from JMS POJOs and uses them at the application layer. This way we can control both APIs from the same source.

I know this isn't the most ideal design but it "gets us by" until we migrate everything over to GQL Queries/Mutations.

**Comment by kaqqao** [comment]
I see.
I think the approach above gets you almost as close as possible to a types-only schema without violating the spec. I _could_ theoretically make a method that removes the need for an explicit dummy, but it's very dubious if it makes sense in the lib. That said, I'll close this issue, but feel free to reopen if you'd like it addressed differently.
