### ISSUE TITLE
[Question] How to handle FieldUndefined exception?

### ISSUE THREAD

**Issue by for3v3rInFriendZone** [leangen/graphql-spqr#365]
I've managed to create a custom exception handler for any `RuntimeException` by extending `DataFetcherExceptionHandler`.

What I don't understand if there is a way to handle `FieldUndefined` exception, in the same way as `RuntimeExceptions`?
It seems like this kind of exception ignores my custom `DataFetcherExceptionHandler` implementation.

The reason why I'm asking is because I only need `message` and custom property `errorType` in my response, if something went wrong.
But when this `FieldUndefined` exception happens, it falls back to the default error response structure, which I don't want.

**Comment by kaqqao** [comment]
True. `DataFetcherExceptionHandler` will only handle the exceptions thrown within the data fetcher, as the name suggests. Validation errors occur before any data fetching happens.
I _think_ the ways for dealing with those are more limited. One would be to register a custom instrumentation and implement `beginValidation`. In the returned instrumentation context `onCompleted` can be used to transform the errors.
Alternatively, the whole execution result can be transformed prior to returning by implementing `instrumentExecutionResult`.

Either way, this is dealing with graphql-java API directly.

**Comment by for3v3rInFriendZone** [comment]
Thanks Bojan, I appreciate. :)
