### ISSUE TITLE
How come that from 0.97 to 0.10 we have breaking changes??

### ISSUE THREAD

**Issue by PedroD** [leangen/graphql-spqr#369]
Eg.: `GraphQLErrorAdapter.getErrorType()` returns `ErrorType` in 0.97 and `ErrorClassification` in 0.10.

Another eg.: `Scalars.temporalScalar` changed signature.

How come we have these major breaking changes in a minor version jump?

**Comment by kaqqao** [comment]
I... have no clue where `GraphQLErrorAdapter` is coming from, but it's not coming from SPQR 😶

While SPQR's API is generally quite stable, as long as the version is 0.x changes can be introduced as needed to keep up with graphql-java etc. Versions starting with 0 are commonly understood to mean _work in progress_, but in SPQR's case it is mostly for the lack of official documentation. It is important to note that only the SPIs directly expected by the `GraphQLSchemaGenerator` are generally considered as _the public API_. Not _all_ accessible methods can be considered _public API_ warranting a version bump on change. But of course, compatibility is maintained as best possible.

You can see the list of changes considered breaking in [the change log](https://github.com/leangen/graphql-spqr/blob/master/CHANGELOG.md) for each release.
