### ISSUE TITLE
Question regarding mapped variables

### ISSUE THREAD

**Issue by brettcooper** [leangen/graphql-spqr#37]
GraphQL takes in a Map<String, Object> mappedVariables as part of the execute() request.  When processing GraphQL JSON (content type: application/json), we are parsing out the variables as strings from the JSON itself.  

This has worked fine for String, Enum types, but last week we ran into an issue when trying to process ZonedDateTime strings.  I ended up realizing that I had to convert the ZonedDateTime string into an actual ZonedDateTime object in order for the query to work with GraphQL.  

Is there an easier way to handle this besides having to manually find and parse out ZonedDateTime variables from the query and replacing the value in the Map<String, Object> mappedVariables with an actual ZonedDateTime?

Here's an example GraphQL JSON query (Note: starts_at and ends_at are ZonedDateTime!):

```
[
  {
    "query": "mutation updateCoupon($application_id: String!, $id: String!, $status: CouponRuleStatusInput!, $name: String!, $allocation_method: AllocationMethodInput!, $amount: BigDecimal!, $custom_word: String!, $discount_type: String!, $ends_at: ZonedDateTime!, $entitled_collection_ids: [String]!, $entitled_product_ids: [String]!, $entitled_variant_ids: [String]!, $format: String!, $merge_field: String!, $starts_at: ZonedDateTime!, $suffix: String!, $valid_days: String!, $validity_type: ValidityTypeInput!) { coupon_rule(coupon_rule: {application_id: $application_id, id: $id, name: $name, status: $status, allocation_method: $allocation_method, amount: $amount, custom_word: $custom_word, discount_type: $discount_type, ends_at: $ends_at, entitled_collection_ids: $entitled_collection_ids, entitled_product_ids: $entitled_product_ids, entitled_variant_ids: $entitled_variant_ids, format: $format, merge_field: $merge_field, starts_at: $starts_at, suffix: $suffix, valid_days: $valid_days, validity_type: $validity_type}) { id name status allocation_method amount custom_word discount_type ends_at entitled_collection_ids entitled_product_ids entitled_variant_ids format merge_field starts_at suffix valid_days validity_type __typename }}",
    "variables": {
      "application_id": "15e58062-54d0-4614-8498-485ac7a4933b",
      "id": "e3f69a41-6439-4522-9f18-a5083ad5b174",
      "name": "50% off",
      "status": "ACTIVE",
      "allocation_method": "ACROSS",
      "amount": 3,
      "custom_word": "asdasd",
      "discount_type": "Percent Off",
      "ends_at": "2017-11-13T17:00:00.000Z",
      "entitled_collection_ids": [],
      "entitled_product_ids": [
        
      ],
      "entitled_variant_ids": [
        
      ],
      "format": "merge_field-custom_word",
      "merge_field": "firstName",
      "starts_at": "2017-10-04T16:00:00.000Z",
      "suffix": "33",
      "valid_days": "Sunday",
      "validity_type": "BETWEEN_SPECIFIC_DATES",
      "__typename": "CouponRule",
      "random_characters": "AUTOGENERATED",
      "prefix_1": "firstName",
      "prefix_2": "asdasd"
    },
    "operationName": "updateCoupon"
  }
]
```

Here's the code we are using to parse out the ZonedDateTime String and manually convert it to an actual ZonedDateTime:

```
private ExecutionResult getExecutionResultFromJson(String applicationId, JsonNode firstNode) {
        String query = firstNode.get("query").asText();
        String operationName =
                firstNode.has("operationName") ? firstNode.get("operationName").asText("") : "";
        JsonNode variables = firstNode.has("variables") ? firstNode.get("variables") : null;
        Map<String, Object> mappedVariables =
                (variables != null) ? MAPPER.convertValue(variables, HashMap.class) : Collections.EMPTY_MAP;

        // Grab the GraphQL variables from the query
        String graphQLVariables = org.apache.commons.lang3.StringUtils.substringBetween(query, "(", ")");

        if (!StringUtils.isNullOrEmpty(graphQLVariables)) {
            // Split based on comma, then colon and remove $ and ! characters from the variables
            Map<String, String> variablesByNameAndType = COMMA.splitAsStream(graphQLVariables)
                    .collect(Collectors.toMap(e -> COLON.split(e)[0].replace("$", "").trim(),
                                              e -> COLON.split(e)[1].replace("!", "").trim()));

            // Get all ZonedDateTime variables
            List<String> zonedDateTimeKeys = variablesByNameAndType.entrySet().stream()
                    .filter(map -> "ZonedDateTime".equalsIgnoreCase(map.getValue()))
                    .map(Entry::getKey)
                    .collect(Collectors.toList());

            // If present, convert any keys of type ZonedDateTime from a String to a ZonedDateTime to work with GraphQL
            if (!CollectionUtils.isNullOrEmpty(zonedDateTimeKeys)) {
                for (String zonedDateTimeKey : zonedDateTimeKeys) {
                    Object zonedDateTimeString = mappedVariables.get(zonedDateTimeKey);

                    // Replace ZonedDateTime String with actual ZonedDateTime
                    if (zonedDateTimeString != null) {
                        mappedVariables.remove(zonedDateTimeKey);
                        mappedVariables.put(zonedDateTimeKey, ZonedDateTime.parse(zonedDateTimeString.toString()));
                    }
                }
            }
        }

        String applicationIdKey = "application_id";

        if (mappedVariables.containsKey(applicationIdKey)) {
            mappedVariables.remove(applicationIdKey);
        }

        mappedVariables.put(applicationIdKey, applicationId);

        LOG.debug("Running GraphQL query: '{}', Operation name: '{}', Variables: '{}'", query, operationName,
                  variables);

        // Execute GraphQL query or mutation
        return graphQLExecutor.execute(query, operationName, mappedVariables);
    }
```

Thanks for your help!

**Comment by brettcooper** [comment]
GraphQL takes in Map<String, Object> mappedVariables as part of the execute() request.  When processing GraphQL JSON (content type: application/json), we are parsing out the variables as strings from the JSON itself.  

This has worked fine for String, Enum types, but last week we ran into an issue when trying to process ZonedDateTime strings.  I ended up realizing that I had to convert the ZonedDateTime string into an actual ZonedDateTime object in order for the query to work with GraphQL.  

Is there an easier way to handle this besides having to manually find and parse out ZonedDateTime variables from the query and replacing the value in the Map<String, Object> mappedVariables with an actual ZonedDateTime?

Here's an example GraphQL JSON query:

`[
  {
    "query": "mutation updateCoupon($application_id: String!, $id: String!, $status: CouponRuleStatusInput!, $name: String!, $allocation_method: AllocationMethodInput!, $amount: BigDecimal!, $custom_word: String!, $discount_type: String!, **$ends_at: ZonedDateTime!**, $entitled_collection_ids: [String]!, $entitled_product_ids: [String]!, $entitled_variant_ids: [String]!, $format: String!, $merge_field: String!, **$starts_at: ZonedDateTime!**, $suffix: String!, $valid_days: String!, $validity_type: ValidityTypeInput!) { coupon_rule(coupon_rule: {application_id: $application_id, id: $id, name: $name, status: $status, allocation_method: $allocation_method, amount: $amount, custom_word: $custom_word, discount_type: $discount_type, ends_at: $ends_at, entitled_collection_ids: $entitled_collection_ids, entitled_product_ids: $entitled_product_ids, entitled_variant_ids: $entitled_variant_ids, format: $format, merge_field: $merge_field, starts_at: $starts_at, suffix: $suffix, valid_days: $valid_days, validity_type: $validity_type}) { id name status allocation_method amount custom_word discount_type ends_at entitled_collection_ids entitled_product_ids entitled_variant_ids format merge_field starts_at suffix valid_days validity_type __typename }}",
    "variables": {
      "application_id": "15e58062-54d0-4614-8498-485ac7a4933b",
      "id": "e3f69a41-6439-4522-9f18-a5083ad5b174",
      "name": "50% off",
      "status": "ACTIVE",
      "allocation_method": "ACROSS",
      "amount": 3,
      "custom_word": "asdasd",
      "discount_type": "Percent Off",
      "ends_at": "2017-11-13T17:00:00.000Z",
      "entitled_collection_ids": [],
      "entitled_product_ids": [
        
      ],
      "entitled_variant_ids": [
        
      ],
      "format": "merge_field-custom_word",
      "merge_field": "firstName",
      "starts_at": "2017-10-04T16:00:00.000Z",
      "suffix": "33",
      "valid_days": "Sunday",
      "validity_type": "BETWEEN_SPECIFIC_DATES",
      "__typename": "CouponRule",
      "random_characters": "AUTOGENERATED",
      "prefix_1": "firstName",
      "prefix_2": "asdasd"
    },
    "operationName": "updateCoupon"
  }
]`

**Comment by kaqqao** [comment]
Right now, variables are not dealt with properly, so you have to deserialize them properly yourself. I think the fix for this is already in master but not released. I will check this out again to make sure it's fixed.

**Comment by brettcooper** [comment]
@kaqqao Thanks for the info! If you could, let me know if the fix is released or not and I can give it a try.

**Comment by kaqqao** [comment]
0.9.4 has just been released. Please test if it fixes your issue.
I think this is the same as #19, and if that's the case, v0.9.4 contains the fix.

**Comment by brettcooper** [comment]
I have updated graphql-spqr to 0.9.4 and removed my code to manually parse them out and it is working now!  Thank you!
