### ISSUE TITLE
Original Field Name

### ISSUE THREAD

**Issue by senolatac** [leangen/graphql-spqr#381]
I can reach to alias name easily but how can I reach to original fieldName?

 ```
    @GraphQLQuery(name = "fieldAliasNameX", description = "A food's name")
    private String fieldOriginalName; 

   ....

   @GraphQLQuery(name = "foods") // READ ALL
    @Override
    public List<Food> getFoods(@GraphQLEnvironment ResolutionEnvironment env) {
        DataFetchingFieldSelectionSet selectionSet = env.dataFetchingEnvironment.getSelectionSet();
        List<SelectedField> fields = selectionSet.getFields();
        for (SelectedField f: fields)
        {
            System.out.println(f.getName());
        }
        return foodRepository.findAll();
    }
```

In this example, Output looks like alias name: fieldAliasNameX, but I need original name like "fieldOriginalName". Is there a way to do it?

**Comment by kaqqao** [comment]
I think you're mixing up the terminology here. In this case `nameX` is the real name of the GraphQL field, not an alias.
You'd have an alias if e.g. a user would send a query like:

```graphql
{
  foods {
    aliasName: nameX
  }
}
```

Than the field `nameX` would be aliased as `aliasName`. And this information you could get from the `DataFetchingEnvironment`.

It seems what you want really is the name of the underlying Java element (method). You can also get that, yes.

```java
String methodName = ((Method) env.resolver.getTypedElement().getElement()).getName();
```

But such logic in resolvers is a bad smell, in general. You'd likely be better off using an interceptor, or persisting the name in the GraphQL schema itself via e.g. a directive, depending on what you're trying to achieve.

**Comment by senolatac** [comment]
@kaqqao thanks for your answer. But I don't need method name. I need fieldName.

My java model looks like:

```
class Food {
    @GraphQLQuery(name = "aliasNameX", description = "A food's name")
    private String originalFieldNameX;
  ...
}
```

As a result, I want to reach "originalFieldNameX" not "aliasNameX".

Example Request:
```
{
  foods {
    aliasName
  }
}
```

Current Output:

`env.dataFetchingEnvironment.getSelectionSet().getFields(); -> aliasNameX...`

Expected Output:

`originalFieldNameY...`

**Comment by kaqqao** [comment]
What you're calling `aliasNameX` is the real and only field name in the GraphQl schema. Not an alias. Users provide aliases, not you. So `env.dataFetchingEnvironment.getSelectionSet()` will only ever give you `aliasNameX` or the user-provided alias.
`originalFieldNameY` does not exist in the GraphQL schema. It is the name of the underlying Java element (Java field), which GraphQL knows nothing about.
To reach that, you have to do what I said above:

```java
String javaFieldName = ((Field) env.resolver.getTypedElement().getElement()).getName();
```

**Comment by senolatac** [comment]
but it gives exception like `java.lang.ClassCastException: class java.lang.reflect.Method cannot be cast to class java.lang.reflect.Field (java.lang.reflect.Method and java.lang.reflect.Field are in module java.base of loader 'bootstrap')`

**Comment by kaqqao** [comment]
Cast to `Member` (or `Field`) instead of `Method`.

**Comment by kaqqao** [comment]
Ah. I see. This is because the field is private, so it's actually the getter method that gets exposed. Either make the field public, or cast to `Method` and use `ClassUtils.findFieldByGetter`.

**Comment by senolatac** [comment]
@kaqqao but in here, I need multiple-field names, your suggestion looks like methodName.

```
  @GraphQLQuery(name = "foods") // READ ALL
   @Override
   public List<Food> getFoods(@GraphQLEnvironment ResolutionEnvironment env) {
       DataFetchingFieldSelectionSet selectionSet = env.dataFetchingEnvironment.getSelectionSet();
       List<SelectedField> fields = selectionSet.getFields();
       for (SelectedField f: fields)
       {
           System.out.println(f.getName());
       }
       return foodRepository.findAll();
   }
```
In here, expected output should be originalField1, originalField2 ...

**Comment by kaqqao** [comment]
Oof, I see... You want the underlying field names, but from a level above. Still possible, but ugly :(

```java
for (SelectedField selectedField : env.dataFetchingEnvironment.getSelectionSet().getImmediateFields()) {
    Optional<Operation> operation = Directives.getMappedOperation(selectedField.getFieldDefinition());
    String javaName = operation.map(op -> ((Member) op.getTypedElement().getElement()).getName()).orElse(null);
}
```

Be very careful though. If there's more than one Java element exposed per GraphQL field, `getTypedElement().getElement()` will explode. So to be sure you'd have to call `getTypedElement().getElements()` instead and decide what to do. `ClassUtils#getPropertyMembers` might also be useful, or the `ClassUtils.findXXX` family of methods.

**Comment by kaqqao** [comment]
`dataFetchingEnvironment.getSelectionSet().getImmediateFields()` is from the latest graphql-java. In earlier version, you'd use a different method... can't remember the names now, but you basically have to get a hold of the `GraphQLFieldDefinition` for each selected sub-subfield, and call `Directives.getMappedOperation` on it.

**Comment by senolatac** [comment]
thank you @kaqqao .

**Comment by kaqqao** [comment]
No worries. Did you manage to do what you were after?

**Comment by senolatac** [comment]
yes @kaqqao managed. https://github.com/senolatac/springboot-graphql-mongo
