### ISSUE TITLE
Make it easy to customize how Executables are created

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr#383]
Currently, `ResolverBuilder`s directly decide how to produce `Executable`s (wrappers around method invocation/field access). It would be better to extract this logic into a separate class to make it easier to replace.
This is a tiny first step towards enabling non-reflection based resolvers to be used.

**Comment by KMUS** [comment]
> This is a tiny first step towards enabling non-reflection based resolvers to be used.

Does it mean we can go native with SPQR someday?

**Comment by kaqqao** [comment]
That's the idea, but who knows 😅
