### ISSUE TITLE
JPA Indirect Lists are not Instantiated

### ISSUE THREAD

**Issue by alissongodoi** [leangen/graphql-spqr#4]
Dear,

   this is a wonderful library. However, I am using my Entities from EclipseLink (JPA) to be retrieved automatically and the @OneToMany and @ManyToMany are LAZY loaded. 

For some reason, the GraphQL library is retrieving an array list of 0 records instead of instantiating them before loading. 

I tried to debug and the getters/setters from my Entity are being executed accordingly (like, customer.getPhoneList()) which returns an IndirectList from EclipseLink.

Is there a way that I could tell the Resolver to instantiate the list before returning it as an ArrayList in the OperationExecute method? Maybe I am missing some point in the TypeResolvers and probably could try to teach a TypeResolver to instantiate the list before returning as an array.

**Comment by alissongodoi** [comment]
It looks like I found the bug. 

It is related to EclipseLink IndirectList not supporting stream method. 
That's the bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=433075

**Comment by kaqqao** [comment]
Wow, didn't know about it. Good job finding it. Can you maybe workaround it by repacking the buggy list into a different one in your getter?

**Comment by alissongodoi** [comment]
@kaqqao I updated EclipseLink to version 2.6.0 and it works perfectly.
