### ISSUE TITLE
@GraphQLContext doesn't support graphql.GraphQLContext

### ISSUE THREAD

**Issue by GoodforGod** [leangen/graphql-spqr#405]
Expected behavior of [@GraphQLContext](https://github.com/leangen/graphql-spqr/blob/master/src/main/java/io/leangen/graphql/annotations/GraphQLContext.java) annotation is to retrieve data from context, however it only support retrieval Only Maps or via reflection through getters from any class [check RootContextInjector](https://github.com/leangen/graphql-spqr/blob/master/src/main/java/io/leangen/graphql/generator/mapping/common/RootContextInjector.java)

However there is "native" GraphQLContext entity that is supposed to represent such context and it is not supported it SPQR.

I think that this will be logical to add support in [RootContextInjector]((https://github.com/leangen/graphql-spqr/blob/master/src/main/java/io/leangen/graphql/generator/mapping/common/RootContextInjector.java)) for [graphql.GraphQLContext](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQLContext.java)

**Comment by GoodforGod** [comment]
I can implement this feature and propose PR for such feature

**Comment by kaqqao** [comment]
You're right, this is indeed missing. I'd be happy to merge a PR adding that.
Btw, the annotation applicable here is `@GraphQLRootContext`, not `@GraphQLContext`. This is an unfortunate quirk of history (GraphQL used to treat contexts differently in its early days) that I'll probably have to do something about.

**Comment by GoodforGod** [comment]
Yea I meant **@GraphQLRootContext**, just miss type on my side
I created a [PR with such feature](https://github.com/leangen/graphql-spqr/pull/406), looking for your review, thanks!
