### ISSUE TITLE
Support for discriminatory updates?

### ISSUE THREAD

**Issue by x80486** [leangen/graphql-spqr#407]
I'm currently using `GraphQL SPQR` with the Spring Boot starter. I'm trying to find a way to support partial updates using the same (domain model) class, but I can't find a way to make it work.

Basically, what I'm trying to do is to have a class that's used for updates to a given model:

```java
public class UpdateCommand {
   private String status;

   private String version;

   // ...
}
```

So far, if I would like to use the same class for partial updates, I can't tell which value between `status` and/or `version` is meant to be updated because `null` doesn't really help there. I can't assume that the presence of `null` is just the fact that the field in question is going to be reset (as in unset) to back to `null` or just not updated.

> I'm aware that this is an issue with Java and in some measure, this doesn't apply here 😏

**Comment by kaqqao** [comment]
As you yourself noted, this is a general impedance mismatch with Java. One thing you can do is make the fields `Optional`. If I remember correctly, in that case you'd get an empty optional when an explicit `null` is passed and `null` when nothing was passed. I know this sounds backwards, but that's how all JSON libraries in Java (or at least the ones by default supported SPQR) work.
It is not exactly pretty having `Optional`s all over, but I see now other way to generically solve this.

**Comment by x80486** [comment]
There is a somehow [interesting](https://github.com/graphql-java-kickstart/graphql-java-tools/issues/141) implementation in the `graphql-java-kickstart/graphql-java-tools` repository. I wouldn't like to have class members declared as `Optional`, but if that works, I'll give it whirl for the time being 🙌🏻

It's interesting that this is not a hot subject in GraphQL (and typed languages) 🤔

Feel free to close this one if there is really nothing you could do in `SPQR` to address that.

**Comment by kaqqao** [comment]
There's a few things to unpack here. Seems like you're trying to implement [anemic mutations](https://productionreadygraphql.com/blog/2018-02-18-graphql-mutation-design-anemic-mutations) which are generally an anti-pattern in GraphQL. But you might have no other choice. Or maybe I'm just wrong and that's not what you're doing at all 😅

There's an alternative approach in SPQR that might be useful to you. If you deconstruct the input, e.g. instead of
```java
@GraphQLQuery
public Book update(Book input) {...}
```
you have
```java
@GraphQLQuery
public Book update(String title, Author author) {...}
```
and tell SPQR to generate Relay-compliant mutations:
```java
generator.withRelayCompliantMutations()
```
SPQR will generate a specific input type for each mutation that doesn't already take a single object.

**Comment by x80486** [comment]
I'm currently dealing with an old (really old) system where everything is quite loose (in terms of validations) and updates happen in a single workflow, hence the need for a big-bloated object with optional members. On the other hand, while you can work with aggregates on the border, it's not really useful since they tend to have more fields/members than those models (you name it: DTOs, etc.) you use for input data. In that sense, I don't find `Undefined` as a pretty bad design, because it's something that's used on the border, and propagated into proper domain models later.

I'm just introducing a way to have an API, and probably modernize the user interface at some point.

I'll definitely check that approach with `generator.withRelayCompliantMutations()` also 👍🏻

**Comment by stevedefazio** [comment]
It sounds like when creating this library a judgment call had to be made, to handle NULLS one way or the other. But what if we give the ability to make that determination to the user?

What if when we annotate our service method, there's a switch we can provide, to treat nulls as explicit, or to ignore them. Then, I could simply provide two methods to accommodate both behaviors. Something like

```
@GraphQLMutation(name="createTrade", partialUpdate=false)
	public Trade createTrade(@GraphQLArgument(name = "trade") Trade trade) {
		return tradeDao.save(trade);
	}

@GraphQLMutation(name="createTrade", partialUpdate=true)
	public Trade updateTrade(@GraphQLArgument(name = "trade") Trade trade) {
		return tradeDao.save(trade);
	}
```

In the first example, any fields not included into the query will be treated as explicit NULL, and in the second case, they will be omitted. Unless I'm missing something this seems clean and simple (and I reallllllllllly don't wanna have to make all my fields Optional)
