### ISSUE TITLE
Support graphql-java 17 version

### ISSUE THREAD

**Issue by temaslikov** [leangen/graphql-spqr#410]
Hi,

The latest version of `graphql-spqr` uses `graphql-java 16.2`. However,  in August `graphql-java` upgraded major version to 17. As I know, major graphql-java releases are not backwards compatible and we can\`t up version, even if it compiles successfully. Are there any plans to upgrade major version `graphql-java`?

Thank you in advance

**Comment by ryantw** [comment]
Wondering the same, I am getting the error that graphql.execution.batched.Batched can't be resolved.

**Comment by f1ztech** [comment]
+1 large performance improvements announced in graphql-java 17
