### ISSUE TITLE
How to validate ArgumentInjector to avoid SQLi

### ISSUE THREAD

**Issue by lisandrolan** [leangen/graphql-spqr#413]
Hi, 
I have ArgumentInjectors to add sort features to the graphql query and I need to validate the properties before executing the query to identify and prevent SQL injections. 

Do you know how to do that?

Thanks in advance
@vjroby

**Comment by kaqqao** [comment]
Hey, I know this is an old issue, but have you figured out what you needed?
Could you perform whatever validation was needed in the injector itself? If not, what were you missing?
Also, why even validate such things in the GraphQL API layer at all? Sounds like a job for the layer below, where SQL queries are being built/executed.

**Comment by kaqqao** [comment]
Please reopen is you still need help.
