### ISSUE TITLE
Question: how to perform complex database query fetching?

### ISSUE THREAD

**Issue by Serg-de-Adelantado** [leangen/graphql-spqr#42]
Hi!
Right now I have a working REST API, described by bunch of DTOs for all occasions. GraphQL seems like an ideal tool to get rid of that zoo. So I am trying to describe a simple schema to test the SPQR library:
```graphql
type Product {
    id: ID!
    title: String
    offsers: [Offer]
}

type Offer {
    id: ID!
    product: Product
}
```
It's easy to move this schema to SPQR-powered POJOs and provide services with injected jOOQ-powered repositories, just like I have for now with REST controllers. But there is a problem: how to map GraphQL queries to SQL? Let's say I have a simple service class(I've moved repository code into service for shorthand):
```kotlin
class ProductsService(private val jooq: DSLContext) {
    @GraphQLQuery(name = "product")
    fun findOne(@GraphQLArgument(name = "id") id: Long): Product {
        return jooq
                .selectFrom(PRODUCTS)
                .where(PRODUCTS.ID.eq(id))
                .fetchOne(mapper()) ?: throw RecordNotFoundException("product", id)
    }
}
```
So the question is, how to know that I should provide a `JOIN` to `offers` table here, if query will look like:
```graphql
product(id: 1) {
    id,
    offers
}
```
which would be requested as:
```kotlin
jooq.select().from(PRODUCTS).join(OFFERS).on(PRODUCTS.ID.eq(OFFERS.PRODUCT_ID)).fetch { ... }
```

**Comment by C4Grey** [comment]
Well, it seems like I've found a solution, SPQR allows to inject `@GraphQLEnvironment environment: ResolutionEnvironment` into query method where a tree of `selectionSet`s may be found. So this is a point where I can build a mapper to SQL query.
I am not sure it's a right solution in terms of graphql-java with all those async batching, `DataLoader`s and caching routines, so will not close the issue for now, since I am hope @kaqqao or anyone else from repo contributors may enlighten me in this question.

**Comment by p-maks** [comment]
You could potentially use another query to resolve you offers based on Product in @GraphQLContext see https://github.com/leangen/graphql-spqr-samples/blob/master/src/main/java/io/leangen/spqr/samples/demo/query/annotated/SocialNetworkQuery.java example.

**Comment by kaqqao** [comment]
Yup, the `selectionSet` is made available (by graphql-java via `DataFetchingEnvironment`) exactly to support optimal/eager fetching (e.g. SQL JOINs), and SPQR enables you to get a hold of it via the `ResolutionEnvironment`.
It is also true what @p-maks said. Depending on your exact circumstances, it may not even be too expensive to fetch this in multiple goes, i.e. fetch only the `Product` in the `product` resolver and then, when the `offers` field is being resolved, fetch the `Offer`s based on the `Product` instance injected via `@GraphQLContext `.

**Comment by Serg-de-Adelantado** [comment]
@p-maks, @kaqqao thank you for your answers

**Comment by kaqqao** [comment]
No worries :)
Just for the sake of completeness, I'll add that you can use an external method taking a `@GraphQLContext` annotated object to override any field resolution logic. By default, non-top-level fields will be resolved as a simple property of their enclosing object, e.g. `offers` in your example will normally be resolved by calling `getOffers` on a `Product`. You can make use of this by eagerly fetching `offers` when requested, or you can use an external method instead to resolve the `offers` field (e.g. to make another query to the DB).

**Comment by Serg-de-Adelantado** [comment]
Seems like a useful feature, thanks again
