### ISSUE TITLE
Can't fetch schema

### ISSUE THREAD

**Issue by dimitrikvirik** [leangen/graphql-spqr#426]
Hello. I am using latest version spqr on kotlin and when I try to fetch using postman, it not work.  I use sample code from here https://codersee.com/graphql-spqr-with-spring-boot-and-kotlin/ and change spring boot version on 2.7.2 and kotlin version on 1.7.10. Also i need to add this dependency
 implementation("com.graphql-java:graphql-java:16.2")

It's possible to fetch schema? or it need to do other way

**Comment by kaqqao** [comment]
How could I possibly know what the problem is if you never even say what is the error you're getting?
