### ISSUE TITLE
Override GraphQLArgument object type to provide more details to clients

### ISSUE THREAD

**Issue by chrishunter-agspace** [leangen/graphql-spqr#43]
I'm probably doing this completely wrong, but I have a simple GraphQLQuery where the method signature is essentially

```
@GraphQLQuery(name = url)
public List<Entity> searchAll(@GraphQLArgument(name="filter") Entity filter) {
return search(filter)
}
```

That wraps up a matcher search so that some of our clients that want a general purpose search can pass an id into the filter or another attribute and get back a filtered list. The problem becomes that in an attempt to extend this to be able to take nulls, the method signature has to move to being a Map so that we can distinguish when a value is null because it wasn't set, or null because the client want to search on null (such as figuring out which customers don't have a telephone number set). 
So my first issue I ran into is that you can't have a Map<String, Object> as the GraphQLArgument as I get an error saying 
```
[
"Validation error of type WrongType: argument value ObjectValue{objectFields=[ObjectField{name='id', value=IntValue{value=1}}]} has wrong type"
]
```

where it doesn't like converting from an Int to an Object . 
That's not the best, but I can set the argument to be an object and then cast it to a map so that it can still be searched like so:

```
@GraphQLQuery(name = url)
public List<Entity> searchAll(@GraphQLArgument(name = "filter", ) Object filter) {
Map<String, Object> where = ((LinkedHashMap) filter);
return search(where)
}
```

My issue then becomes GraphiQL which loses information about the argument and can only refer to it as "ObjectScalar". Is there a way to override how it is reported back to GraphiQL, such as setting a type in the argument so that it can be mapped to the relevant entity in GraphiQL allowing clients to know that the argument should really be in the layout of the Entity?

**Comment by kaqqao** [comment]
If I get you right, your main issue is how to know whether an argument value was provided or not?
In this case, maybe the simplest approach is to check the raw input directly, such as:

```java
@GraphQLQuery(name = "searchAll")
        public List<Entity> searchAll(@GraphQLArgument(name="filter") Entity filter, @GraphQLEnvironment ResolutionEnvironment env) {
            Map<String, Object> raw = env.dataFetchingEnvironment.getArgument("filter");
            if (raw.containsKey("title")) {
                 ... //the "title" attribute was indeed provided
            }
            return search(...);
        }
```

If, on the other hand, you really wanted to map in the `filter` argument as an `Entity` but inject it as a `Map<String, Object>`, you could achieve it in multiple ways. Here's a reusable one:

1. Make a simple custom annotation, such as:
    ```java
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.PARAMETER)
    public @interface MapAs {
        Class value();
    }
    ```
2. Annotate the relevant parameter with it:
    ```java
        @GraphQLQuery(name = "searchAll")
        public List<Entity> searchAll(@GraphQLArgument(name="filter") @MapAs(Entity.class) Map<String, Object> filter) {
            return ...;
        }
    ```
3. Make a simple type mapper that reacts to this annotation:

    ```java
    public class TypeOverridingMapper implements TypeMapper {

        @Override
        public GraphQLOutputType toGraphQLType(AnnotatedType javaType, Set<Type> abstractTypes, OperationMapper operationMapper, BuildContext buildContext) {
            //You might as well just throw an exception here as it doesn't make much sense to override the _output_ type
            return operationMapper.toGraphQLType(getOverrideType(javaType), abstractTypes, buildContext);
        }

        @Override
        public GraphQLInputType toGraphQLInputType(AnnotatedType javaType, Set<Type> abstractTypes, OperationMapper operationMapper, BuildContext buildContext) {
            //Use the type from MapAs instead of the real type
            return operationMapper.toGraphQLInputType(getOverrideType(javaType), abstractTypes, buildContext);
        }

        @Override
        public boolean supports(AnnotatedType type) {
            return type.isAnnotationPresent(MapAs.class); //react only when MapAs is found
        }

        private AnnotatedType getOverrideType(AnnotatedType type) {
            //Throw away the MapAs annotation to prevent infinite recusrion, but keep the others
            Annotation[] annotations = Arrays.stream(type.getAnnotations()).filter(a -> a.annotationType() != MapAs.class).toArray(Annotation[]::new);
            return GenericTypeReflector.annotate(type.getAnnotation(MapAs.class).value(), annotations);
        }
    }
    ```
4. Register the custom mapper and treat Maps as scalars
    ```java
            schemaGenerator
                .withTypeMappers(new TypeOverridingMapper()) //add your custom mapper
                .withDefaultMappers() //keep the others
                .withScalarMappingStrategy(new MapScalarStrategy()) //treat Maps as scalars, to avoid SPQR transforming them to lists. This will soon be the default.
                ...
                .generate();
    ```

**Comment by chrishunter-agspace** [comment]
#notworthy

https://media.giphy.com/media/iiS84hOJXh1Pq/giphy.gif

**Comment by kaqqao** [comment]
Hehehe :)
I hope that means I helped you :) Can I close the issue?

**Comment by chrishunter-agspace** [comment]
I'm actually working though this at the moment, you can close it and I'll open another one if necessary. Thanks again.

**Comment by chrishunter-agspace** [comment]
So FYI - I cannot get the Map<String, Object> to work correctly. I can only get the error:
```
[
  "Validation error of type WrongType: argument value ObjectValue{objectFields=[ObjectField{name='subEntity', value=ObjectValue{objectFields=[ObjectField{name='deleted', value=BooleanValue{value=false}}]}}]} has wrong type"
]
```
Which is essentially the same error as before. I think the Hibernate -> GraphQL gets confused at times with the one to many, or could be the Lists. I see that EntityInput missed these relationships compared to the Entity response. I'm working around that by just continuing the `Object` casting to Map, but the `@As` fixes my documentation issue. Thanks.

**Comment by kaqqao** [comment]
Since it's a validation error, it means you're sending an argument of a shape that does not conform to the schema. Analyze the schema carefully and see what it expects, and how the input types got mapped.

It is normal for the same class to be differently mapped as input than as output, because not all fields have a way to be deserialized. By default, SPQR will let Jackson (or Gson) discover the deserializable fields and only map those on input types. You can control this process in many ways:

* you can flat out write a new `TypeMapper` to fully control how a class gets mapped to a `GraphQLType`
* You can customize the `InputFieldDiscoveryStrategy` that the built-in mappers rely on. It is used to decide what fields are to be mapped on input types.
* If you customize it in a way that Jackson/Gson can no longer simply deserialize the input, you will also need to provide a custom `ArgumentInjector` that knows how to create an instance from the input the client provided

**Comment by chrishunter-agspace** [comment]
Yeah, so the entityInput does not conform to the entity. If I have a relationship between two entities, then the subEntity does not appear in the entity, so it fails validation. For example I'm getting:

```
class Entity () {
...
    @OneToMany(mappedBy = "entity")
    private List<SubEntity> subEntities;
...
}
```

Can be then observed in GraphiQL as:
```
Entity:
id: Int
subEntities: [SubEntity]

EntityInput:
id: Int
```
So it is correct that I can't do this if I validate. I guess the main point is that I don't want to validate, just document it since the map is passed into a CriteriaQuery, so fail if it doesn't match the entity structure. I'll run though the suggestions you have given to see what I can do about it

**Comment by chrishunter-agspace** [comment]
Sorry, to keep responding to this. I think the solution is cleaning this up with DTO's, which is really the root cause of my issues :)

I was slightly abusing how everything was working, which became apparent quite a while ago.

**Comment by kaqqao** [comment]
I don't mind extending the discussion. Better clear it up than have you confused :)

Unless there's a setter for `subEntities` exposed (i.e. `setSubEntities`), or you configure your Jackson to use reflection (I think there's such a setting) or have a `@JsonCreator` constructor, the default `InputFieldDiscoveryStrategy` will ignore that field when mapping `EntityInput`. Since `InputFieldDiscoveryStrategy` only delegates to Jackson, it's better to reconfigure Jackson than mess with the strategy itself.

As a general rule, I wholeheartedly recommend exposing service classes that work with DTOs, instead of DAO/repository classes working with domain objects/persistent entities directly, so yeah, that's probably a good idea in your case too in any case.
