### ISSUE TITLE
Upgrade to graphql-java v19

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr#433]
This issue will represent a task list for making SPQR compatible with graphql-java v19. Note that this only takes of care of basic compatibility, not of all deprecated APIs etc. Those will have to be dealt with later, as due to the vulnerabilities, upgrading graphql-java is seen as urgent.

* [x]  Replace batching strategy with DataLoader #432
* [x]  Replace all removed/renamed method calls
* [x]  Remove custom `TypeResolutionEnvironment`
* [x]  Define all applied directives

**Comment by fedor-bobin-db** [comment]
Hi. 
When new release is planning?
