### ISSUE TITLE
Java 8 support dropped from 0.12.1 to 0.12.2

### ISSUE THREAD

**Issue by Julius-Rapp** [leangen/graphql-spqr#457]
After upgrading to **0.12.2**, we cannot compile our **Java 8** application. The error message reads as follows.
```
java: cannot access io.leangen.graphql.annotations.GraphQLArgument
  bad class file: /home/directory/.m2/repository/io/leangen/graphql/spqr/0.12.2/spqr-0.12.2.jar!/io/leangen/graphql/annotations/GraphQLArgument.class
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

This is presumably caused by 5cb679d753b1670fcd02c54c5e75e264315c11bd. I believe that the upgrade to Java 11 was accidental.

**Comment by kaqqao** [comment]
graphql-java switched to Java 11 recently, so it only made sense for SPQR to follow, seeing how graphql-java is an essential dependency.
I could revert the version bump and compile SPQR with Java 8, but wouldn't you still be in the same trouble since you'd be getting graphql-java compiled with 11 anyway?

**Comment by Julius-Rapp** [comment]
[SPQR 0.12.2 depends on graphql-java 20.2](https://github.com/leangen/graphql-spqr/blob/c54742c2ba235b6205f0e7bfc3b6ca0e915110e1/pom.xml#L81-L85), which still supports Java 8. The first version of graphql-java that requires Java 11 will be graphql-java 21. For now, it would be great if SPQR based on graphql-java 20.2 still supported Java 8.

I verified that [very few changes](https://github.com/Julius-Rapp/graphql-spqr/commit/0e4d74b79bbe663c1d531b45fecc4cb45c68e73f) are required on top of [spqr-v0.12.2](https://github.com/leangen/graphql-spqr/tree/graphql-spqr-v0.12.2) in order to be compiled with Java 8 and be usable for our Java 8 app.

**Comment by kaqqao** [comment]
Ok, fair enough, SPQR should always support exactly what graphql-java does, so I'll keep it on Java 8 for the time being.
