### ISSUE TITLE
Remove hardcode realization of Executable from ResolverBuilder

### ISSUE THREAD

**Issue by oleg-savko** [leangen/graphql-spqr#46]
Please provide possibility to inject own Executable realization in ResolverBuilder (PublicBeanResolver, AnnotatedResolverBuilder and so on..).

PublicResolverBuilder.class
`querySourceBean == null ? new MethodInvoker(method, beanType) : new SingletonMethodInvoker(querySourceBean, method, beanType)`

Inject custom MethodInvoker realization would be great for provide authentication and security for example.

**Comment by kaqqao** [comment]
Not a bad idea. I'll give it a think.
But since I know you're using Spring, you can use Spring Security annotations just fine with SPQR.

**Comment by oleg-savko** [comment]
Im not use Spring Security, and any way as I now, there is some common problems when used proxy over SPQR, which sometimes not very comfortable.
With possibility to inject own realization, would be native support to provide security without any proxy.

**Comment by oleg-savko** [comment]
Also for this purpose very need possibility to access execution context in invoker by which make decision invoke method or not (pass ResolutionEnvironment for example). 
Its will be really great opportunity.

**Comment by kaqqao** [comment]
I believe this requirement is now satisfied by the newly-introduced `ResolverInterceptor` feature.
See #180 for details. Here's [a related test](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/InterceptorTest.java#L34) exemplifying its use for authentication.
