### ISSUE TITLE
Not all jackson modules working in JacksonValueMapperFactory

### ISSUE THREAD

**Issue by oleg-savko** [leangen/graphql-spqr#47]
Default implementation configurate objectMapper as following:

`objectMapper
                    .findAndRegisterModules()
                    .setAnnotationIntrospector(new AnnotationIntrospector(collectSubtypes(abstractTypes, basePackage, metaDataGen)))`

what AnnotationIntrospector actually do? 
I see that for example jackson KotlinModule not proper work when it used. 
(need manually provide `@JacksonCreator` and `@JacksonProperty` with kotlin module its not need by default)

**Comment by kaqqao** [comment]
`AnnotationIntrospector` looks for SPQR specific annotations like `@GraphQLQuery` so that Jackson would respect the naming.
You're more than welcome to provide your own `Configurer` to the `JacksonValueMapperFactory` to configure Jackson any way you like.

**Comment by oleg-savko** [comment]
Thanks for response!

**Comment by kaqqao** [comment]
I have no means to test this with Kotlin, but I changed the configuration so that the custom `AnnotationIntrospector` is only prepended instead of overriding the current one, so it should work.

Please test it with your setup and reopen if something is still wrong.
