### ISSUE TITLE
Can't access my superclass fields

### ISSUE THREAD

**Issue by Dave2605** [leangen/graphql-spqr#49]
Hello,

I have parent class A and child class B. 
I have GraphQLQuery that returns List\<B>\, but I don't have access to A class fields.

I've tried to implement **InterfaceMappingStrategy** from here https://github.com/leangen/graphql-spqr/issues/21, but schema generation fails on **ObjectsImplementInterfaces** rule checking with **ObjectDoesNotImplementItsInterfaces** error.

What I am doing wrong ?
Is there any opportunity to access A class fields without redefining them in class B ?  

Thanks a lot)

**Comment by kaqqao** [comment]
Sorry, but you really haven't given me much to work with... Without a sample, it's hard to know what you're doing. Either case, it doesn't sound like you need to change the `InterfaceMappingStrategy`.

Here's a quick example of what you described that is working as expected:

```java
public class Test {

    @Test
    public void testSimpleInheritance() {
        GraphQLSchema schema = new TestSchemaGenerator()
                .withValueMapperFactory(valueMapperFactory)
                .withOperationsFromSingleton(new Service())
                .generate();

        List<GraphQLFieldDefinition> childFields = ((GraphQLObjectType) 
        schema.getType("Child")).getFieldDefinitions();

        assertEquals(2, childFields.size());
        assertTrue(childFields.stream().anyMatch(f -> f.getName().equals("parentField")));

        GraphQL exe = GraphQLRuntime.newGraphQL(schema).build();
        ExecutionResult result = exe.execute("{children{ parentField, childField}}");
        assertTrue(result.getErrors().isEmpty());
    }

    public static class Parent {

        private String parentField;

        public Parent(String parentField) {
            this.parentField = parentField;
        }

        public String getParentField() {
            return parentField;
        }
    }

    public static class Child extends Parent {
        private String childField;

        public Child(String parentField, String childField) {
            super(parentField);
            this.childField = childField;
        }

        public String getChildField() {
            return childField;
        }
    }

    public static class Service {

        @GraphQLQuery
        public List<Child> children() {
            return Collections.singletonList(new Child("parent", "child"));
        }
    }
```

Did you mean something different? If so, please provide an example that gives you issues.

**Comment by kaqqao** [comment]
This seems to be a common stumbling block... I must document this behavior very explicitly.

**Comment by Dave2605** [comment]
Great! Thank you, it works)
