### ISSUE TITLE
Fields order

### ISSUE THREAD

**Issue by vojtechhabarta** [leangen/graphql-spqr#50]
I am building GraphQL API and I really like code-first style so thank you for this tool.

While code-first style is more convenient and eliminates duplication the generated schema and introspection query (used by Graph*i*QL) doesn't look as good as handwritten. So I would like to improve it.

First think is order of fields. Currently introspection query returns fields in no particular order. I think they should be at least sorted alphabetically but even better would be possibility to specify their order. Since order in source code is not much useful here (fields can come from different classes) I would add some annotation which could be used to list names of fields in required order, something simitar to [`@XmlType.propOrder`](https://docs.oracle.com/javase/8/docs/api/javax/xml/bind/annotation/XmlType.html#propOrder--).

In [`680f20d`](https://github.com/vojtechhabarta/graphql-spqr/commit/680f20ded3e4ef133836f96f58905f2691ee4154) commit I added `@GraphQLType.propOrder` but it could be for example `@GraphQLType.fieldOrder` or separate annotation. It should also be added to `@GraphQLInterface`.

Does this feature make sense for you and should I finish it and create PR? If yes, how exactly the annotation should look like?

**Comment by kaqqao** [comment]
Sorry for the slow response, I wanted to think this through before responding.
First of all, thanks for your interest in contributing to SPQR! Mighty nice of you!

Regarding the feature, as you noted, it would have an effect on the introspection results only, as the regular responses fully depend on the query itself. Seeing that the introspection is more meant to be machine-friendly than human-friendly, and the field ordering shouldn't really influence anything, I'm having doubts about the utility of the feature...
Relying on the field order is not a good idea in any case... so the effect would be only cosmetic, at least in my understanding.

What is your exact use-case for this? Maybe you are seeing something I'm not.

**Comment by vojtechhabarta** [comment]
Thanks for your response.

I totally agree that order of fields doesn't have any effect on functionality.
But at the same time introspection result is meant for humans because it is presented in "Documentation Explorer" in Graph*i*QL on the right side. And for me this is primary source of documentation for users.

See what I meant in following picture:

![introspection-fields](https://raw.githubusercontent.com/vojtechhabarta/graphql-spqr/pictures/img/introspection-fields.png)

This is what I want to improve so that it doesn't look as machine-only-friendly 😉 
BTW Graph*i*QL also supports markdown in descriptions (in Java it can be specified like this: `@GraphQLType(name = "User", description = "Description of ``User`` type with _markdown_ **formatting**")`) so I would like to leverage all these features to create nice user documentation.

Does it make sense now?

**Comment by kaqqao** [comment]
I think you're right... This does end up being the documentation for the human as well. As such if should be nice.
So, yes, if you're interested in developing this feature please go forward.
As for the attribute name, I'd go for `fieldOrder` to be consistent with the GraphQL terminology.

**Comment by kaqqao** [comment]
I've just discovered Jackson has a similar feature: [@JsonPropertyOrder](https://fasterxml.github.io/jackson-annotations/javadoc/2.3.0/com/fasterxml/jackson/annotation/JsonPropertyOrder.html).

**Comment by vojtechhabarta** [comment]
Thanks for merging my PR.
