### ISSUE TITLE
Error with two classes with the same name in different packages

### ISSUE THREAD

**Issue by iserraller** [leangen/graphql-spqr#51]
If a schema contains two classes with identical names but in different packages the second class to be processed by OperationMapper.toGraphQLOperation(Operation operation, BuildContext buildContext) will not be mapped (I think) or be mapped to the methods of the first class if field names match (yeah, unfortunate I know). So if any fields match names it will result in an error at execution time like this:

ERROR io.leangen.graphql.execution.OperationExecutor - Operation resolution exception
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at io.leangen.graphql.metadata.execution.MethodInvoker.execute(MethodInvoker.java:36) ~[BigBirdPlexus/:?]
	at io.leangen.graphql.metadata.Resolver.resolve(Resolver.java:89) ~[Maven-io-leangen-graphql_spqr-0.9.3.jar:?]
	at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:93) ~[Maven-io-leangen-graphql_spqr-0.9.3.jar:?]
	at io.leangen.graphql.execution.OperationExecutor.execute(OperationExecutor.java:59) ~[Maven-io-leangen-graphql_spqr-0.9.3.jar:?]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:99) [graphql-java-3.0.0.jar:?]

Looking at the source code I see two points which appear to contribute to this problem:
- BuildContext knownTypes is a Set<String> storing class simple names, since the package qualification is not included this set will not treat two classes from different packages as different entities. Checks for the presence of classes in CachingMapper and other mappers therefore return true when they should return false.
- TypeRepository has covariantOutputTypes and knownObjecTypes are maps which also use unqualified type names as keys (sometimes the class name compounded with the field name) and therefore will also treat two different classes from different packages with the same name as the same class.

I don't know if there's a way to work around this right now. I tried to use a MappedType, but that works only for leaf classes which can be converted directly to serializable results. I couldn't get it to work for classes which contain other selectable fields. Any tips would be appreciated.

**Comment by kaqqao** [comment]
If possible, simply add `@GraphQLType(name = "UniqueName")` to one or both of the types (or `@GraphQLInterface(name = "Unique Name")` if it should be an interface). If not possible, simply register a custom `TypeInfoGenerator` via `generator.withMetaDataGenerator(new CustomTypeInfoGenerator)` and implement it to generate unique names for your types.

The current behavior is by design. SPQR has no reasonable way to generate unique names under all circumstances as different generic types and even annotations could influence how the types are mapped (and the same class could end up being mapped as several different types depending on its generics and/or annotations). Yet, it's a very easy problem to solve for the end user.

**Comment by kaqqao** [comment]
Now that you got me thinking... I likely should make it so that the duplicated names for different types instead get turned into sequential names like `Type2`, `Type3` etc and log a warning with an explanation and workarounds.

**Comment by iserraller** [comment]
Thank you very much for the useful and quick answer! Sorry for the late reply, the holidays got in the middle.

The use of a custom `TypeInfoGenerator` registered using the `generator.withMetaDataGenerator(TypeInfoGenerator)` method worked perfectly. That was the option chosen as it wasn't possible to add annotations to the types.

Your idea for issuing a warning and doing a fair attempt at compatibility sounds great. Even just the warning would be very helpful as we didn't really know what was going on when investigating this issue, we just got the exception above.

Another complementary suggestion would be to document that class name clashes will not be disambiguated and documenting the use of the TypeInfoGenerator to solve this issue. It took a significant amount of effort to identify the problem in the first place and to search for workarounds and that could have been cut down significantly with better docs.

**Comment by kaqqao** [comment]
Reopening as it needs to be addressed further. Some default type disambiguation must be put in place.

**Comment by kaqqao** [comment]
Because custom mappers are allowed to do funky things, it is impossible to reliably detect name collisions in 100% of the cases (false positives are possible). As a result, SPQR will not throw an exception on a potential collision, but it _will_ log a warning, so the user is aware of what is going on.

**Comment by dsun092** [comment]
@iserraller Hi would you be able to share an example of how to implement a custom TypeInfoGenerator? I have the same issues where I have multiple enums of the same Name and spqr is only generating a schema for one of them.

**Comment by iserraller** [comment]
@dsun092 Very sorry for the late reply, you probably have solved this by now, but here's the TypeInfoGenerator we wrote to solve this problem:
```
public class DisambiguatingTypeInfoGenerator extends DefaultTypeInfoGenerator implements TypeInfoGenerator {

    static final Set<Class<?>> DUPLICATES = new HashSet<>(Collections.singleton(SchemaElement.class));

    @Override
    public String generateTypeName(AnnotatedType type) {
        String typeName = super.generateTypeName(type);
        if (DUPLICATES.contains(type.getType())) {
            // append Class object hashcode after type name
            typeName = typeName + "_" + type.getType().hashCode();
        }
        return typeName;
    }
}
```

**Comment by Neigh-infallible** [comment]
Look into this https://stackdev.space/questions/creating-a-technique-that-can-effectively-handle-multiple-types-of-objects response
