### ISSUE TITLE
Relay - adding fields to Connection and Edge types

### ISSUE THREAD

**Issue by vojtechhabarta** [leangen/graphql-spqr#55]
I have a question regarding Relay protocol. I would like to add some fields (for example `totalCount`) to some _Connection Types_. Something similar to GitHub's API at https://developer.github.com/v4/explorer/.

I found that this is explicitly allowed by _Relay Cursor Connections Specification_ ([2.1](https://facebook.github.io/relay/graphql/connections.htm#sec-Connection-Types.Fields) and [3.1](https://facebook.github.io/relay/graphql/connections.htm#sec-Edge-Types.Fields)).

I implemented `io.leangen.graphql.execution.relay.Page<N>` interface and added `public long getTotalCount()` method but it didn't show up in introspection query result.

Is it currently possible to somehow add fields to Connection and Edge types? Or could this be added to graphql-spqr?

**Comment by kaqqao** [comment]
Right now I think you'd have to implement your own version of [`PageMapper`](https://github.com/leangen/graphql-spqr/blob/210b3df47319d8c5d4dd9c57bd2f81ed53e510ad/src/main/java/io/leangen/graphql/generator/mapping/common/PageMapper.java) and provide a non-empty list of fields in lines [32](https://github.com/leangen/graphql-spqr/blob/210b3df47319d8c5d4dd9c57bd2f81ed53e510ad/src/main/java/io/leangen/graphql/generator/mapping/common/PageMapper.java#L32) and [33](https://github.com/leangen/graphql-spqr/blob/210b3df47319d8c5d4dd9c57bd2f81ed53e510ad/src/main/java/io/leangen/graphql/generator/mapping/common/PageMapper.java#L33).

Relay intergation seem rarely used, so the features around it are a bit unpolished. It's a good idea to add auto discovery of extra fields on the `Page` subtype provided.

**Comment by kaqqao** [comment]
I'll look into adding this in the following days unless you end up implementing it earlier :)

**Comment by vojtechhabarta** [comment]
I don't know how to implement this "properly" so I would rather leave it to you.

It should probably somehow reuse `ObjectTypeMapper.getFields()`, what about field ordering? I would prefer standard fields first but not sure. Should it also support resolver methods (annotated using `@GraphQLQuery`) from different classes? (I would guess no.)

**Comment by kaqqao** [comment]
I have the first draft implemented, but it gets tricky with naming. If both `Page<Item>` and `ExtendedPage<Item>` exist, both can not be named `ItemConnection`. So a name disambiguation originally described in #51 needs to be implemented first. This will mean that one will end up being called `Item2Connection` or something like that, which will make it invalid in Relay's opinion, although still usable as a general paging system... Not sure if there's a better approach.
Opinions?

**Comment by vojtechhabarta** [comment]
I would expect that `ItemConnection` should contain fields from both (`Page<Item>` and `ExtendedPage<Item>`) to work properly as Relay connection type. But this probably assumes that only `ExtendedPage<Item>` is used in Java classes. I am not sure what to do if `Page<Item>` is also used somewhere (probably only by mistake).

**Comment by kaqqao** [comment]
Yup, exactly - the problem arises only if both variations (or more??) are present. The first one encountered would become `ItemConnection` while the others would end up getting an "invalid" name... So maybe an exception is a better option... Can't wrap my mind around this...

**Comment by kaqqao** [comment]
0.9.6 is out the door and this is now supported.
To extend the connection type only, return an `ExtendedPage<Item>` fro a query. To extend the edges as well, return `ExtendedConnection<ExtendedEdge<Item>>`.
There's new utility methods in `PageFactory` to support creation of these, but they are for convenience only.
There's usage examples for extending the page (i.e. the connection type only) [here](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/RelayTest.java#L234) and for edge extension [here](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/RelayTest.java#L245).

**Comment by vojtechhabarta** [comment]
I tried to extend page and it works well. Thank you.
