### ISSUE TITLE
Question about Subscription response

### ISSUE THREAD

**Issue by oleg-savko** [leangen/graphql-spqr#56]
Hi can anyone explain me following situation. 

I hava a simple subscription which work:
```kotlin 
class TimerGraph {

  @GraphQLSubscription
  fun timer(): Publisher<Tick> {
    return Flux.generate(
        Consumer<SynchronousSink<LocalDateTime>> { sink ->
          sink.next(LocalDateTime.now())
        })
        .map { Tick(it) }
        .delayElements(Duration.ofSeconds(1))
  }

}

data class Tick(val x: LocalDateTime)
```

When I make following request:
```graphql
subscription timer {
    timer {
      x
    }
}
```
I get response:
```json
{
  "data": {
    "x": "2018-01-05T15:11:32.538"
  },
  "errors": [],
  "extensions": null
}
```
But I think that response should be: 
```json
{
  "data": {
     "Timer": {
         "x": "2018-01-05T15:11:32.538"
     }
  },
  "errors": [],
  "extensions": null
}
```
The response is unwrapped by something, and frontend library throw a lot of warnings about this, and its really disappointed.
Any suggestion why its happens and how prevent this?
Do not exclude that maybe its graphql-java issue.

**Comment by kaqqao** [comment]
This is true. The behavior is coming from graphql-java. I asked the guys there about it, and the current understanding is that this is according to the spec, but none of us is really sure.
I you find a good example or the exact part of the spec this is violating, it would be a good idea to open an issue on graphql-java.

**Comment by oleg-savko** [comment]
Thanks for u clarification!

**Comment by kaqqao** [comment]
I got the news that this is getting fixed.

**Comment by kaqqao** [comment]
graohql-java v7 fixed this issue. I'll upgrade the dependency and release new SPRQ in the following few days (I just have to finalize a big refactoring task I was working on for quite a while now).

**Comment by kaqqao** [comment]
Upgraded to graphql-java v7, which takes care of this one.
