### ISSUE TITLE
Support @GraphQLIgnore on fields and methods

### ISSUE THREAD

**Issue by kaqqao** [leangen/graphql-spqr#59]
The usage of `@GraphQLIgnore` seems to be causing a lot of confusion, so it should probably be expanded to cover the cases the users expect.

`@GraphQLIgnore` should be allowed on fields and methods to indicate to the resolver builder that the annotated member is to be skipped.

**Comment by kaqqao** [comment]
`@GraphQLIgnore` can also be used as a meta-annotation

**Comment by jestan** [comment]
@kaqqao will this be included in 0.9.6 any time soon ?
BTW thanks a lot for a great library, I have tried other graphql java libraries and  compared to other c[ode-first java libraries ](https://github.com/graphql-java/awesome-graphql-java#code-first) graphql-spqr nicely  integrates with spring/jersey

**Comment by kaqqao** [comment]
Yes! 0.9.6 should be out today or tomorrow at latest and it will fix this among a few other outstanding issues.

And thanks a lot for the kind words! Much appreciated :)
One of the design goals was for it to work seamlessly with injection frameworks.

**Comment by jestan** [comment]
:thumbsup:
