### ISSUE TITLE
Inheritance & GraphQLInterface

### ISSUE THREAD

**Issue by piotr-swierczynski** [leangen/graphql-spqr#65]
Hey, I've got problem with creating some abstraction over my code and schema. What I want to achieve is, that in GraphQL Schema, "MyList" implements Interface, and I could see fields from PageableAndSortableList class only in Schema "Interface".

```java
@GraphQLType(name = "MyList")
public class MyGraphQLList<T> extends PageableAndSortableList {

    private List<T> pageList;
    private Order order;
    private int limit;
    private String cursor;

    @GraphQLNonNull
    public String getCursor() {
        return cursor;
    }

}
```

```java
@GraphQLInterface(name = "Interface")
public abstract class PageableAndSortableList {

    protected Long total;

    protected Integer count;

    protected String next;

}
```

Having something like this with proper getters and setters ofc, I receive the following error on spring boot app start:

Caused by: graphql.schema.validation.InvalidSchemaException: invalid schema:
object type 'MyList_Contact' does not implement interface 'Interface' because field 'count' is missing
object type 'MyList_Contact' does not implement interface 'Interface' because field 'next' is missing
object type 'MyList_Contact' does not implement interface 'Interface' because field 'total' is missing
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:241) ~[graphql-java-7.0.jar:na]
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:231) ~[graphql-java-7.0.jar:na]
	at io.leangen.graphql.GraphQLSchemaGenerator.generate(GraphQLSchemaGenerator.java:824) ~[spqr-0.9.6.jar:na]
	at com.example.demo.graphql.GraphQLController.<init>(GraphQLController.java:43) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_121]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 20 common frames omitted

Could you help me with some solution.

**Comment by kaqqao** [comment]
I've just tested this, and as long as you have the getters on the abstract class, it works as expected:

```java
@GraphQLInterface(name = "Interface")
    public static abstract class PageableAndSortableList {

        private Long total;
        private Integer count;
        private String next;

        public Long getTotal() {
            return total;
        }

        public void setTotal(Long total) {
            this.total = total;
        }

        public Integer getCount() {
            return count;
        }

        public void setCount(Integer count) {
            this.count = count;
        }

        public String getNext() {
            return next;
        }

        public void setNext(String next) {
            this.next = next;
        }
    }
```

The reason why it may be failing for you is that the abstract class and the implementation class are not in the same package and you didn't set the global `basePackages`.
If there is a finite set of _base packages_ where all the stuff in your app that you want exposed resides, you can simply use `GraphQLSchemaGenerator#withBasePackages` to configure the packages. E.g. `generator.withBasePackages("com.your.company")`. If possible, this is the recommended approach.

One reason why this is important is that nested classes are normally scanned for getters to expose as GraphQL fields even when they're not annotated with `@GraphQLQuery`. But there is no way to know if some of the inherited getters are framework methods or default Java stuff that should't be exposed. So, what `BeanResolverBuilder` does by default is filter the methods my package. If you don't set any base packages, it only considers the package of the scanned class as acceptable (`MyGraphQLList` in your case). And if some super classes/interfaces are from a different package, their methods will be filtered out. This is likely what happened, so `MyGraphQLList` ended up without the `total`, `count` and `next` fields, and is thus not a valid implementation if its interface.

You can also set a separate `ResolverBuilder` per type, if you can't or don't want to set the base packages globally. E.g.

```java
generator.withNestedResolverBuildersForType(new TypeToken<MyGraphQLList<String>>(){}.getType(), new BeanResolverBuilder("some.package"))
```

This way it will only use `some.packge` as the criteria when mapping `MyGraphQLList<String>` and not other types.

Unfortunately, the code will not work in your case because of a bug in the `hashCode` implementation in a library SPQR uses under the hood. I'll have that fixed asap.

**Comment by piotr-swierczynski** [comment]
Thanks for quick reply. Indeed, the problem was with different packages. Thank you. I really admire the work you've done to create this library. Are you considering creating a peace of documentation?

**Comment by kevinzheng** [comment]
Do make the base abstract class "public", I got this problem.

**Comment by kaqqao** [comment]
@kevinzheng SPQR never touches private classes, so yes, all exposed classes must be public.

**Comment by sarbhsinghal** [comment]
I am getting the same problem, although i have tried all the solutions mentioned above, still not resolved the issue.

@GraphQLInterface(name = "node")
public abstract class Node {

	protected String id;
	protected String productModelIdentifier;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProductModelIdentifier() {
		return productModelIdentifier;
	}

	public void setProductModelIdentifier(String productModelIdentifier) {
		this.productModelIdentifier = productModelIdentifier;
	}

}


@GraphQLType(name="student")
public class Student extends Node{

	private User userDetails;
	private EntityMetadata metaData;

	public User getUserDetails() {
		return userDetails;
	}


	public void setUserDetails(User userDetails) {
		this.userDetails = userDetails;
	}

	public EntityMetadata getMetaData() {
		return metaData;
	}

	public void setMetaData(EntityMetadata metaData) {
		this.metaData = metaData;
	}
}


The error which I am getting is 
object type 'student' does not implement interface 'node' because field 'id' is missing
object type 'student' does not implement interface 'node' because field 'productModelIdentifier' is missing


Please help me out to resolve the issue.

Also please mention how I can implement multiple Interfaces to a class because here we are annoting @GraphqlInterface to a class and we can't extend multiple classes.

**Comment by AmirHosein-Farhadi** [comment]
Hey Guys
I had the same error
in my case, my Abstract class was implementing Serializable
I removed the implementation and it worked fine

**Comment by AmirHosein-Farhadi** [comment]
@kaqqao Hey Btw Thanks For Such a Nice Library
Please add support for implementing Serializable
Thanks

**Comment by kaqqao** [comment]
@AmirHosein-Farhadi Any chance you provide an example that replicates the issue?
There's absolutely nothing in SPQR I'm aware of that cares about `Serializable`...

**Comment by daviestobialex** [comment]
Am having the same issue. I was able to get it to work from the test case I wrote

```
@Slf4j
@RunWith(SpringRunner.class)
public class TestSchemaInheritanceGeneration {

    @MockBean
    private DataServiceInterface<Groups> groupsDataService;

    @Test
    public void contextLoads() {
        GraphQLSchema schema = new GraphQLSchemaGenerator()
                .withBasePackages("com.sheeft.microservices.library")
                .withOperationsFromSingleton(new groupsService())
//                .withOperationsFromSingleton(new )
                .generate();
        GraphQL graphQL = GraphQL.newGraphQL(schema).build();

        String query = "{\n"
                + " getAllPagable(pageNumber : 1, numberOfRecords : 3) { responseCode groups  { groupName }  }\n"
                + "}";
        ExecutionResult executionResult = graphQL.execute(query);

        assertEquals("[]", String.valueOf(executionResult.getErrors()));
        log.info("==== RESULT =====");
        log.info(executionResult.getData().toString());
        query = "{\n"
                + "        \"getAllPagable\": {\n"
                + "            \"responseCode\": 97\n"
                + "            \"groups\": null\n"
                + "        }";
//        Gson g = new Gson();
//        assertEquals(query,g.toJson(executionResult.getData(), GetAllGroupResponse.class));
    }

    public class groupsService {

        @GraphQLQuery(name = "getAllPagable")
        public com.sheeft.mircoservice.groups.models.responses.GetAllGroupResponse getAllPagable(@GraphQLArgument(name = "pageNumber", defaultValue = "0") int pageNumber, @GraphQLArgument(name = "numberOfRecords", defaultValue = "0") int numberOfRecords) {
            com.sheeft.mircoservice.groups.models.responses.GetAllGroupResponse getAllGroupResponse = new com.sheeft.mircoservice.groups.models.responses.GetAllGroupResponse();

            List<Groups> findAllByViewable = groupsDataService.findAllByViewable('Y', pageNumber, numberOfRecords);

            if (findAllByViewable == null || findAllByViewable.isEmpty()) {
                getAllGroupResponse.setResponseCode(ResponseCodeEnum.SH_97.getRespCode());
                getAllGroupResponse.setResponseDescription(ResponseCodeEnum.SH_97.getRespDescription());
            } else {
                List<Group> groups = new ArrayList<>();
                findAllByViewable.forEach((group) -> {
                    Group g = new Group();
                    BeanUtils.copyProperties(group, g);
                    g.setSource(group.getRoute().getSource().getName());
                    g.setDestination(group.getRoute().getDestination().getName());
                    g.setMembersLeft(group.getMembersCount() - group.getBusType().getNumberOfSeats());
                    groups.add(g);
                });
                getAllGroupResponse.setGroups(groups);
                getAllGroupResponse.setResponseCode(ResponseCodeEnum.SH_00.getRespCode());
                getAllGroupResponse.setResponseDescription(ResponseCodeEnum.SH_00.getRespDescription());
            }
            log.info("========= RESPONSE =========");
            log.info(getAllGroupResponse.toString());
            return getAllGroupResponse;
        }
    }
}
```

But I can not get it to work from the main project. I have my project on github at https://github.com/daviestobialex/groups-spqr

but basically I have a super class

```
@GraphQLInterface(name = "BaseResponse", implementationAutoDiscovery = true)
@ToString
@Data
@AllArgsConstructor
public class BaseResponse {

    @JsonInclude(Include.NON_NULL)
    protected String responseCode;

    @JsonInclude(Include.NON_NULL)
    protected String responseDescription;

    protected String hash;

    public BaseResponse() {
    }
}
```

Another class extends this the above parent class

```
@ToString(callSuper = true)
@Data
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@GraphQLType(name = "GetAllGroupResponse")
public class GetAllGroupResponse extends BaseResponse {

    private List<Group> groups;

    @JsonCreator
    public GetAllGroupResponse() {
        super(null, null, null);
    }

    @JsonCreator
    public GetAllGroupResponse(String responseCode, String responseDescription, List<Group> groups) {
        super(responseCode, responseDescription, null);
        this.groups = groups;
    }

    public String getResponseCode() {
        return responseCode;
    }

    public String getResponseDescription() {
        return responseDescription;
    }

    public String getHash() {
        return hash;
    }

}
```
and finally my controller class
```
@Slf4j
@GraphQLApi
@Service
public class GroupsController {

    @Autowired
    private GroupsFacade groupsFacade;

    @GraphQLQuery(name = "getAllPagable")
    public GetAllGroupResponse getAllPagable(@GraphQLArgument(name = "pageNumber", defaultValue = "0") int pageNumber, @GraphQLArgument(name = "numberOfRecords", defaultValue = "0") int numberOfRecords) {
        return groupsFacade.getAllActiveGroups(pageNumber, numberOfRecords);
    }
}
```

Basically, I keep getting the following error below :
>Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is graphql.AssertException: Object required to be not null] with root cause

>graphql.AssertException: Object required to be not null
	at graphql.Assert.assertNotNull(Assert.java:22) ~[graphql-java-12.0.jar:na]
	at graphql.execution.instrumentation.DocumentAndVariables.<init>(DocumentAndVariables.java:19) ~[graphql-java-12.0.jar:na]
	at graphql.execution.instrumentation.DocumentAndVariables.<init>(DocumentAndVariables.java:13) ~[graphql-java-12.0.jar:na]
	at graphql.execution.instrumentation.DocumentAndVariables$Builder.build(DocumentAndVariables.java:55) ~[graphql-java-12.0.jar:na]
	at graphql.GraphQL.parse(GraphQL.java:561) ~[graphql-java-12.0.jar:na]


and I have done everything @kaqqao has suggested to me please check the project

**Comment by daviestobialex** [comment]
@kaqqao I deeply apologize. I was using an older version of your library version 0.03 I switched to version 0.05 and it works now.
