### ISSUE TITLE
GraphQLMutation appears also in query section in schema

### ISSUE THREAD

**Issue by piotr-swierczynski** [leangen/graphql-spqr#67]
Hey, I have a problem with my mutation method. Having something like this:
`@Component
public class Query {

    @GraphQLQuery
    public MyList getSomething() {
        return new MyList();
    }

    @GraphQLMutation
    public Long doSomething() {
        return 1l;
    }
}`

I ended up with doSomething method in mutation section of the schema, which is correct, but also doSomething appears in query along with getSomething. I think it has something to do with my configuration, and maybe I should've moved mutation implemetation to another class and put it differently in config. Right now it looks like this:
`public GraphQLController(Query query) {

        //Schema generated from query classes
        GraphQLSchema schemaFromAnnotated = new GraphQLSchemaGenerator()
                .withResolverBuilders(
                        //Resolve by annotations
                        new AnnotatedResolverBuilder(),
                        //Resolve public methods inside root package
                        new PublicResolverBuilder("com.example.demo"))
                .withOperationsFromSingleton(query)
                .withValueMapperFactory(new JacksonValueMapperFactory())
                .generate();
        graphQlFromAnnotated = GraphQL.newGraphQL(schemaFromAnnotated).build();
        LOGGER.info("Generated GraphQL schema using SPQR");
    }`
How to get rid of the mutation in query section of my schema?

**Comment by kaqqao** [comment]
If you don't actually need the `PublicResolverBuilder`, removing it will fix the issue. What happens is that both resolver builders decide the method should be exposed, but `AnnotatedResooverBuilder` exposes it as a mutation, while the `PublicResolverBuilder` decides it's a query. Normally the duplicates get removed and the first one wins, but because here they end up in different groups (queries and mutations), they end up duplicated.

I'll see to update this logic to detect duplicates across operations types.

**Comment by piotr-swierczynski** [comment]
Thanks, your advice worked as expected. Could you think of situation where PublicResolverBuilder would be needed though? Because, as I understand, `AnnotatedResolverBuilder` takes only annotated methods etc. On The other hand `PublicResolverBuilder` takes method that are public. How does it refer to other annotation that are, for example, for classes or method arguments?

**Comment by kaqqao** [comment]
You'd normally need `PublicResolverBuilder` in cases when you're exposing a third-party class where you can't add annotations. Another use-case would be when your classes simply have a lot of methods and you don't need to rename and fine tune things.

The important thing to note here is that you can supply a `ResolverBuilder` per bean, and only globally, e.g. `generator.withOperationsFromSingleton(bean, resolverBuilder`. So you can control the process more precisely.

Another point is that all the out-of-the-box ResolverBuilders are customizable. E.g. `resolverBuilder.withFilter` will let you filter some methods out. There's more configuration options to control how the operations get named, how arguments get detected etc.

It's also quite easy to create your own ResolverBuilders (maybe by subclassing an existing), e.g. to use existing annotations, from Jackon, JaxRS or anything else.

`PublicResolverBuilder` will not make use of any annotations and it's meant for cases where you don't have annotations.

When multiple ResolverBuilders are registered, and they pick the same method - the first one wins. So you can register both `Annotated` and `Public` and one will pick only the annotated while the other will pick the rest.

**Comment by kaqqao** [comment]
As for the annotations on arguments, every ResolverBuilder has an instance of `ResolverArgumentBuilder` (customizable) that takes care of detecting and naming the arguments.
