### ISSUE TITLE
node query not added to Query root

### ISSUE THREAD

**Issue by ellebrecht** [leangen/graphql-spqr#68]
In whatever examples I could come up with, the node query for Relay support is never added to the Query root as expected.

For example in SPQR's own RelayTest, the prerequisites are met: class User has a property named "id" annotated to be a Relay id, and class UserService provides getUserById() with its argument also property annotated.

Still, even though the Node type is properly generated, the node root query is not.
I noticed a test query using node in RelayTest.nodeQuery, however it's not being used.
Is it supposed to work?

Digging around, I found that OperationMapper.createNodeResolver() is never called because the condition in generateQueries() is never met. This in turn is because in getNodeQueriesByType() the unwrappedQueryType is of class GraphQLTypeReference, thus not satisfying either of the two conditions given there. Does the GraphQLTypeReference maybe need to be resolved first at that time?

**Comment by kaqqao** [comment]
Yes, this should definitely work. I'll look into it to see what goes wrong later today.

Just to clear the basics, you're on a recent SPQR version (0.9.5 or 0.9.6)?

**Comment by kaqqao** [comment]
Tested just now, and you're indeed correct - it is broken. Not sure from which point... I'll get it fixed asap.

**Comment by ellebrecht** [comment]
Ok cool, I wasn't perfectly sure. Let me know if I can help.
I was using SPQR 0.96 release BTW.
