### ISSUE TITLE
java.sql.Date exception

### ISSUE THREAD

**Issue by PastorPL** [leangen/graphql-spqr#69]
Hello,

Firstly, I would like to underline that I've just started using your lib, so please forgive me if I ask an obvious question. 

I have a problem with java.sql.Date. Using it is causing exception:
```
java.lang.UnsupportedOperationException: null
	at java.sql.Date.toInstant(Date.java:304)
	at io.leangen.graphql.util.Scalars$5.serialize(Scalars.java:202)
	at io.leangen.graphql.util.Scalars$5.serialize(Scalars.java:198)
...

```
This is because  java.sql.Date is exteding  java.util.Date, but method "toInstant()" is throwing java.lang.UnsupportedOperationException() (this method is user in Scalars.java:202). 

I don't know if this is desired behaviour? Maybe there is workaround?

BTW. Great for really nice pice of software :).

**Comment by kaqqao** [comment]
Argh... the terrible hack that is `java.sql.Date` strikes again :tired_face:
It seems it needs it's own special scalar. I'll add it in the next release. In the meantime, you can register your own mapper and a custom scalar that you can make along these lines:

```java
public static final GraphQLScalarType GraphQLSqlDate = temporalScalar(java.sql.Date.class, "SqlDate",
            s -> java.sql.Date.valueOf(LocalDate.parse(s)), i -> new java.sql.Date(i.toEpochMilli()), d -> d.toLocalDate().toString());
```

**Comment by kaqqao** [comment]
This is, of course, in case you're OK with treating the `java.sql.Date` as a `LocalDate`. Theoretically, the time zone could be lost in this conversion, but this depends on everything, from the DB to the JDBC driver implementation, and there seems to be no safe or sane way to deal with it without know the entrails of both :(

**Comment by PastorPL** [comment]
Thanks for answer :)

But I'm not sure if I understand you correctly - shall I edit `io.leangen.graphql.util.Scalars` class and add what you have adviced? There is no other way to "inject" this update to existing version of lib ?:)

**Comment by kaqqao** [comment]
Ah, no need for that, you can create a custom mapper that handles only this type. E.g.

```java
public class SqlDateMapper extends ScalarMapper {

    public static final GraphQLScalarType GraphQLSqlDate = temporalScalar(java.sql.Date.class, "SqlDate",
            s -> java.sql.Date.valueOf(LocalDate.parse(s)), i -> new java.sql.Date(i.toEpochMilli()), d -> d.toLocalDate().toString());

    @Override
    public GraphQLScalarType toGraphQLType(String typeName, AnnotatedType javaType, Set<Type> abstractTypes, OperationMapper operationMapper, BuildContext buildContext) {
        buildContext.knownInputTypes.add(typeName);
        return GraphQLSqlDate;
    }

    @Override
    public GraphQLScalarType toGraphQLInputType(String typeName, AnnotatedType javaType, Set<Type> abstractTypes, OperationMapper operationMapper, BuildContext buildContext) {
        buildContext.knownTypes.add(typeName);
        return GraphQLSqlDate;
    }

    @Override
    public boolean supports(AnnotatedType type) {
        return java.sql.Date.class.equals(type.getType());
    }
}
```

and then register it with the generator: 
```java
generator.withTypeMappers((config, defaults) -> defaults.insertBefore(ScalarMapper.class, new SqlDateMapper()))
```

**Comment by kaqqao** [comment]
In general., you can add support for any type that doesn't work out-of-the-box this way: create a mapper for it, and register it with the generator.

Btw, I'm push a commit that takes care of this issue in a few minutes. I'll do a release in a week of so.

**Comment by kaqqao** [comment]
Pushed [f1b2c07](https://github.com/leangen/graphql-spqr/commit/f1b2c070790d4a2e709adedae5834fec045eebc6)
