### ISSUE TITLE
GraphQLIgnore annotation is not backward compatible in the current master

### ISSUE THREAD

**Issue by jestan** [leangen/graphql-spqr#73]
Hi,

It seems, ElementType.TYPE has been removed from GraphQLIgnore in the current master.
It was there in 0.9.6 version, any idea why it has been removed ?
I am using it to ignore some implementations of a GraphQLInterface,  without ElementType.TYPE, it doesn't compile, is there any other way to do it?

thanks

**Comment by kaqqao** [comment]
Huh, interesting. `ElementType.TYPE` got replaced by `ElementType.ANNOTATION_TYPE` as that was the intention all along - to use it as a meta-annotation. It seems you discovered an accidentally working use-case!

Could you please exemplify the usage that worked for you?

**Comment by jestan** [comment]
I have a marker interface called `ResourceList`
```java
@GraphQLInterface(
        name = "ResourceList",
        implementationAutoDiscovery = true,
        scanPackages = {"domain.fhir"}
)
public interface ResourceList {
}
```

and it has may public api list implementations

and my use case was to hide an internal implementation which i don't want to show in GraphQL schema

```java
@GraphQLIgnore
public class EmptyResourceList implements ResourceList {
}
```

**Comment by jestan** [comment]
and i got following compilation error (with 0.9.7-SNAPSHOT)


: Compilation failure: Compilation failure: 
[ERROR] domain/fhir/EmptyResourceList.java:[10,1] annotation type not applicable to this kind of declaration

BTW
I am using Java 9 with Lombok, may be that is why i am getting this error ?

**Comment by kaqqao** [comment]
So... this worked for you? It was completely unintended! Ok, I'll take a look if I can add proper support for this use-case.
