### ISSUE TITLE
Changing schema dynamically

### ISSUE THREAD

**Issue by piotr-swierczynski** [leangen/graphql-spqr#74]
I have a situation in which I change my schema with regards to my database situation. Not getting into unnecessary details, I'm using CustomTypeMapper to change the way types are presented in the schema. The thing is my CustomTypeMapper is only executed once during schema generation. Is there  a way to run my CustomTypeMapper per schema request (so it could analyse db state) without the need to rebuild the whole schema?

**Comment by kaqqao** [comment]
I updated the comment above, because it contained bad assumptions... If you're reading it from the email, please see the updated version.

**Comment by piotr-swierczynski** [comment]
Sorry for quite a delay. As far as I'm concerned, every time I have to call `generate()` it basically recreates the whole schema, and I don't see the possibility of reusing baseSchema as u said.

**Comment by piotr-swierczynski** [comment]
Maybe, there's a chance of manipulating the schema object itself. The`GraphQLSchema` has `typeMap` and `additinalTypes` fields. If it is possible, I would replace my old graphql type with newly generated, but I'm not experienced in pure Java GraphQL implementation.

**Comment by piotr-swierczynski** [comment]
I'm closing the issue, because changing schema dynamically is IMHO, after some thoughts, against the schema concept itself. Schema should be fixed at the end, and only modifications that are reasonable, are those connected, for instance, with security, where we want to hide some parts of it from certain group of users.
