### ISSUE TITLE
Some kind of subscription sample using spring events

### ISSUE THREAD

**Issue by estebes** [leangen/graphql-spqr#80]
First of all thanks for this awesome project. I'm trying to make subscriptions work with spring events using your subscription test as a starting point but after quite a few hours still nothing is worthing. If you could add somekind of sample to the spqr samples it would be much appreciated. Thanks in advance

**Comment by kaqqao** [comment]
I was planning to make an example of that nature when I get a chance.

In the meantime, see my answer on [this SO question](https://stackoverflow.com/questions/44270248/graphql-java-how-to-use-subscriptions-with-spring-boot) and @bbakerman's [awesome subscription example](https://github.com/graphql-java/graphql-java-subscription-example) with pure graphql-java and websockets.

Post back if you get somewhere.

**Comment by estebes** [comment]
I managed to get it working. Will create a sample project so you can link it if anyone else asks. Thanks for your help.

**Comment by kaqqao** [comment]
Ah, it seems I misunderstood you. I thought you wanted something using Spring's `ApplicationEventPublisher` under the hood.

Anyway, good that you have it running! Thanks for posting back.

**Comment by estebes** [comment]
I was but i found it was easier to do it this way and seems to work better. It is basically @bbakerman's but with spring boot and graphql-spqr so a lot less boiler plate code.

**Comment by kaqqao** [comment]
Yup, I understand. If you don't mind, I'll probably add your example in some form to the [samples project](https://github.com/leangen/graphql-spqr-samples).
Or maybe you could make a PR if you're interested?

I'll close this issue now, but I opened a related one on the other project: https://github.com/leangen/graphql-spqr-samples/issues/7

**Comment by estebes** [comment]
Sure you can. I'll take a look at a PR later.
