### ISSUE TITLE
Required field only on input object

### ISSUE THREAD

**Issue by piotr-swierczynski** [leangen/graphql-spqr#81]
Currently I'm trying to figure it out how to make certain field on my input object required while the same field on output object remains optional. For example, I have my dto:
`public class Pet {
    private Integer id;
}`
So in GraphQL I want to have
id: Int
for Pet and
id: Int!
for PetInput.
What is more, how to achieve this only on one of the mutations that use PetInput?

**Comment by kaqqao** [comment]
The annotations you put on a setter only apply to input fields. So if you have:

```java
public static class Pet {
        private Integer id;

        public Integer getId() {
            return id;
        }

        public void setId(@GraphQLNonNull Integer id) {
            this.id = id;
        }
    }
```

`PetInput` will have `id: Int!` and `Pet` will have `id: Int`.

As for having it in only one mutation, I'm afraid that's not possible. How would you even express that in GraphQL directly? You'd have to have 2 separate input types, like:

```graphql
input PetInput {
  id: Int
}

input PetInput2 {
  id: Int!
}
```

There was a feature that allowed to generate multiple different types from the same Java class in the very early versions, but it required an incredibly convoluted logic and was very unintuitive to use, so I decided to drop it.

The same way you'd need 2 different types in GraphQL, you'd need 2 different types in Java. E.g.

```java
public static class Pet {
      private Integer id;

      public Integer getId() {
          return id;
      }

      public void setId(Integer id) {
          this.id = id;
      }
}

public static class Pet2 extends Pet {

      public void setId(@GraphQLNonNull Integer id) {
          super.setId(id);
      }
}
```

**Comment by piotr-swierczynski** [comment]
Thanks for quick reply. Yes, I totally agree with you. Keeping it 1:1 makes it more intuitive and much less error prone.
