### ISSUE TITLE
Question on how to define queries on Domain types? 

### ISSUE THREAD

**Issue by bidgal** [leangen/graphql-spqr#82]
I am new to GraphQL so any help would be appreciated. Currently I understand if I have to define queries on Domain types, I will need to add annotations in the same file, something like this:

```java
public class A {
    private String id;
    private List<B> bList;

    @GraphQLQuery(name = "bList")
    public List<B> getBListByX(@GraphQLArgument(name = "x") final String x)
   }
```
This generates schema like: 

```graphql
 type A {
   id: String
   bList(x: String): [B]
 }
```
 
We have existing POJOs which we want to use for generating the schema but I do not want to add the query annotations on the POJO itself. Is there any way in which I can add the queries separately in a different file, without having to handwrite all POJOs

**Comment by kaqqao** [comment]
Certainly! Fields (queries) can be attached to types from the outside and, in all cases, annotations are optional. In fact, I'd argue if you need to modify your POJOs to fit a library/framework - something is wrong.

Let's say you have these classes:

```java
public class Book { //POJO

    private String title;
    private String isbn;

   public getTitle() {...} //no annotations needed on getters here by default
   public getIsbn() {...}
}

public class BookService { //top-level stateless singleton

    @GraphQLQuery //here you need the annotation by default, but can be changed
    public List<Book> books(String title) {
        return ...; //find all books with the given title
    }
}
```

Here's some things to be aware of:

* You can attach a field (query) to any type from the outside. You don't want to nest logic into POJOs, so any nested queries that are not simple getters can be attached from the outside:

```java
public class BookService { //top-level stateless singleton

     //notice @GraphQLContext 
    public List<Review> reviews(@GraphQLContext Book book, LocalDate publishedAfter) {
        return ...; //find review by book
    }

    public List<Book> books(String title) { // same as before
        return ...; //find all books with the given title
    }
}
```

Now, the type `Book` will have the `reviews` field, even though the `Book` POJO itself was unchanged. The extra field was attached via `@GraphQLContext`.

```graphql
 type Book {
   title:  String
   isbn: String
   reviews(publishedAfter: LocalDate): [Review]
 }
```

* Top-level queries are normally methods on singletons (like `BookService` above). By default, they need `@GraphQLQuery` to be exposed, but this is configurable. Lower-level queries are normally POJO fields. They *do not* need the annotation to be exposed by default, but again, this is configurable.

So, by default, with the situation from the start, you'll end up with:

```graphql
 type Book {
   title:  String
   isbn: String
 }

type Query {
   books(title: String): [Book]
}
```

* The way you configure what methods are exposed as queries is via choosing a `ResolverBuilder` implementation. You can configure different `ResolverBuilder`s to be used for top-level and lower-levels, and also per type. There's 3 built-in implementations: `AnnotatedResolverBuilder` which exposes only the annotated methods, `PublicResolverBuilder` which exposes all public methods, and `BeanResolverBuilder` which exposes only public getters. By default, `AnnotatedResolverBuilder` is used for top-level, and both `AnnotatedResolverBuilder` and `BeanResolverBuilder` for deeper levels. This is why POJOs typically don't need explicit annotations - their getters will get exposed anyway. You can also implement your own `ResolverBuilder` to perform custom selection, or modify the provided ones, e.g. to change the way the queries they produce are named.

Let;s now say you `BookService` without annotations:

```java
public class BookService { //top-level stateless singleton

    public List<Book> books(String title) { //no annotations any more
        return ...; //find all books with the given title
    }
}
```

You would register `PublicResolverBuilder` and get the same behavior as above:

```java
generator
    .withResolverBuilder(new PublicResolverBuilder()) //globally use PublicResolverBuilder for top-level
    .withOperationsFromSingleton(new BookService())
```

You could also only use `PublicResolverBuilder` for a specific bean:

```java
generator
    .withOperationsFromSingleton(new BookService(), new PublicResolverBuilder())
```

* `ResolverBuilder`s also give names to operations, and this is done via `OperationNameGenerator`. You can change the name generator a builder is using:

```java
generator
    .withResolverBuilder(new PublicResolverBuilder()
        .withOperationNameGenerator(...)) //existing or custom implementation
    .withOperationsFromSingleton(new BookService())
```

**Comment by kaqqao** [comment]
Does this clear things up for you?
It's probably more info than you wanted, but my goal was to arm you with enough knowledge to handle most cases. I hope you're not overwhelmed :)

**Comment by bidgal** [comment]
Thanks for the suggestion I really  appreciate the details you provided. But this is what keeps on happening. Taking the BookService example, This is my code structure:

```java

public class Book { //POJO

    private String title;
    private String isbn;
    private Author author;

    public getTitle() {...} //no annotations needed on getters here by default
    public getIsbn() {...}
}

public class BookService {
   @GraphQLQuery
    public List<Book> books(String title) { //no annotations any more
        return ...; //find all books with the given titl
    }
}
```
 Now I want to filter by author name, so I add the the following to the BookService
```java

public class BookService {
   @GraphQLQuery
    public List<Book> books(String title) { //no annotations any more
        return ...; //find all books with the given title
    }

   @GraphQLQuery
   public Author getAuthor(
                 @GraphQLContext Author author,
                 @GraphQLArgument String authornameFilter) {
       ... 
   }
}
```
The generated schema is updated as:
```graphql
type QUERY_ROOT {
  author(arg0: AuthorInput, authornameFilter: String): Author
}

type Book {
   title:  String
   isbn: String
   author(arg0: AuthorInput, authornameFilter: String): Author
}
```
I have removed the mutations from the schema, still for some reason I am getting AuthorInput as the first argument for the query

**Comment by kaqqao** [comment]
Oh, just by the name of `QUERY_ROOT` I can tell you're using an old version of SPQR. Earlier implementations used to behave differently in that nested queries would also be exposed as top level (taking the context argument explicitly). Plus, there may have been a bug making the nested one also expect an argument.
Please try using the latest (0.9.6 at the moment, and 0.9.7 coming out by the end of the week).

**Comment by bidgal** [comment]
Yes we were using the 0.9.3 version of SPQR library I have updated to the latest and it works as expected. Thanks. 
Just another question on the latest version. I saw that both queries and mutations are showing up under the type `Query`. Whereas in the previous version they had both `QUERY_ROOT` and `MUTATION_ROOT`

Is that expected?

**Comment by kaqqao** [comment]
Hmm, no, it is not. It should have appeared under `Mutation`. Something must have gone wrong with the discovery.

What `ResolverBuilder`s do you have configured? Certain combinations of builders can lead to this issue. E.g. `AnnotatedResolverBuilder` could decide something is a mutation, while `PublicResolverBuilder` coild decide the same method is a query. But even then, you should at least see it duplicated under both `Mutation` and `Query` roots, not only under `Query`... Is this the case?

If you could exemplify your schema generator config, it would help me troubleshoot this.

**Comment by bidgal** [comment]
Yes I figured that one out. The PublicResolveBuilder was also being used for the Mutation. I have fixed that and it works as expected. Thanks!!

**Comment by kaqqao** [comment]
Great!
v0.9.7 will have deduping logic for methods between queries and mutations (the current logic dedupes only with lin one type), so these errors should go away permanently.
Closing this one.
