### ISSUE TITLE
Is there any way to customize errors?

### ISSUE THREAD

**Issue by jlaw311** [leangen/graphql-spqr#83]
For instance, say I would like to validate an input to ensure it's 6 digits. If it doesn't match, I'd like to be able to return an error message to the client, something other than "Internal Server Error Occurred".

**Comment by kaqqao** [comment]
SPQR doesn't deal with errors at all - it only generates the schema for you and errors are an execution-time thing.

If you thow an exception from a resolver method, you'll receive it in the `ExecutionResult`. It's up to the `ExecutionStrategy` to wrap it into a `GraphQLError` and up to you to send it to the client or not.

Are you maybe using graphql-java-servlet? That could be why you're getting a generic error, as the servlet has its own logic for deciding what messages should be obscured.

**Comment by jlaw311** [comment]
Valid point. Thank you!

**Comment by kaqqao** [comment]
Cheers, glad to help :)
