### ISSUE TITLE
Problem with decoding Relay id input values

### ISSUE THREAD

**Issue by ellebrecht** [leangen/graphql-spqr#84]
I think there is a problem with Relay id values when used as input. It occurs where Base64-encoded Relay id fields from a query are used as input values in a subsequent mutation, manifesting itself in added double quotes around the decoded id value.
The problem I think is that IdAdapter.convertInput adds double quotes around the decoded value when the expected result type is String, however double quotes where already added before encoding the value in the previous query.
I'll add a PR to illustrate.

**Comment by kaqqao** [comment]
Fixed as #134.
