### ISSUE TITLE
Adding parameter to getter results in a wrong mutation type

### ISSUE THREAD

**Issue by evader1337** [leangen/graphql-spqr#86]
I have a Student class, which has a following getter for subjects (Sort is my object for sorting):
![image](https://user-images.githubusercontent.com/17454517/37206632-bce40a12-2399-11e8-864e-42e6641e25e1.png)
This works fine, when I'm querying:
![image](https://user-images.githubusercontent.com/17454517/37206734-315fd7d6-239a-11e8-95b8-18c4d9173d78.png)
but if I want to add a Student, the StudentInput has a wrong field:
![image](https://user-images.githubusercontent.com/17454517/37206693-0d8ab04c-239a-11e8-85ea-1d2c5ee4dc0f.png)
The type for subjects should be [Subject] and not SortInput.

**Comment by kaqqao** [comment]
This sounds... not right.
The subject says _mutation_ while your example is  a query.  Also, this is a very basic scenario that definitely works.
There has to be something more you're not showing... For example, if the `Sort` and `Subject` were to somehow get the same name this could happen. But it's impossible to tell without a better example.

Make sure you're on version 0.9.6, and please post a full minimal example demonstrating the issue. And please use real code tags instead of screenshots, so it can be copied.

**Comment by evader1337** [comment]
I have a mutation and a query:
```
    @GraphQLMutation
    public Student addStudent(Student student) { 
        List<Student> students = ctx.getStudentList();
        students.add(student);
        return student;
    }

    @GraphQLQuery
    public PaginationWrapper<Student> allStudents(Pagination pagination, Sort sort) {
        return GraphQLUtils.process(ctx.getStudentList(), pagination, sort);
    }
```
Student is a class:
```
public class Student extends Person {
    private int studentNumber;
    private List<Subject> subjects;

    public Student() {
        this.subjects = new ArrayList<>();
    }

    public Student(int studentNumber, String name, String surname) {
        this.studentNumber = studentNumber;
        super.setName(name);
        super.setSurname(surname);
        this.subjects = new ArrayList<>();
    }

    public void addSubject(Subject p) {
        subjects.add(p);
    }

    public int getStudentNumber() {
        return studentNumber;
    }

    @GraphQLQuery(name="subjects")
    public List<Subject> getSubjects(Sort sort) {
        return GraphQLUtils.sort(subjects, sort);
    }
}
```
When I perform query on allStudents, I can use sorting. Example query:
```
query Q {
  allStudents(pagination: {offset: 0, limit: 10}, sort: {fields: [{field: "name", order: DESC}]}) {
    result { //pagination wrapper
      subjects(sort: {fields: [{field: "name", order: DESC}]}) { --> this works as intended
        name
        classroom
      }
    }
    pagination {
      offset
      limit
      total
    }
  }
}

```

The problem is when performing a mutation:
```
mutation M {
  addStudent(student: {studentNumber: 12345, name: "Test", surname: "Test"}) {
    name
  }
}
```
Student is type of StudentInput, which has wrong fields, like I posted in the original post. Because of that, I can not add any subjects in this mutation. I will try to reproduce, but I'm not sure how to do it outside my envinroment (I'm playing around with KumuluzEE).

**Comment by kaqqao** [comment]
I managed to replicate it... For some reason Jackson thinks your `List<Subject> getSubjects(Sort sort)` method is a setter... so it concludes the type is `Sort` as that's the setter's argument.
I'm now investigating if this is a misconfiguration of Jackson in SPQR or a strange behavior in Jackson itself.

For the time being, you can work around it by replacing the `subjects` query with a simple getter and moving the actual query out of the `Student` class and into the top level, e.g.:

```java
public class Student extends Person {
    private int studentNumber;
    private List<Subject> subjects;

    public Student() {
        this.subjects = new ArrayList<>();
    }

    public Student(int studentNumber, String name, String surname) {
        this.studentNumber = studentNumber;
        super.setName(name);
        super.setSurname(surname);
        this.subjects = new ArrayList<>();
    }

    public void addSubject(Subject p) {
        subjects.add(p);
    }

    public int getStudentNumber() {
        return studentNumber;
    }

    @GraphQLignore //ignore it since the real query is outside
    public List<Subject> getSubjects() { //now a simple getter
        return subjects;
    }

   // needed because Jackson needs a way to set the deserialized subjects
   // can also be replaced by a @JsonCreator constructor
   public void setSubjects(List<Subject> subjects) {
       this.subjects = subjects;
   }
}

... //on the top level

@GraphQLMutation
public Student addStudent(Student student) { 
    List<Student> students = ctx.getStudentList();
    students.add(student);
    return student;
}

@GraphQLQuery
public PaginationWrapper<Student> allStudents(Pagination pagination, Sort sort) {
    return GraphQLUtils.process(ctx.getStudentList(), pagination, sort);
}

@GraphQLQuery //this will get nested into the Student type to replace the removed query
public List<Subject> subjects(@GraphQLContext Student student, Sort sort) {
    return GraphQLUtils.sort(student.getSubjects(), sort);
}
```

**Comment by evader1337** [comment]
Thanks, it works like a charm now. Btw, do I need to define setters? I've defined all the getters, because they are needed for resolving fields, but I didn't need to add any setters when performing mutations. Even now with the workaround you sent, my app works without the setter you added. Why is that?

**Comment by kaqqao** [comment]
The setters are not strictly needed, but if a type is used as an input, Jackson needs a way to populate the instance fields when deserializing it from JSON. But there's multiple ways to do this, setters are just the most basic way.

Not sure what kind of setup do you have... if it works without setters, I guess you're good.

**Comment by kaqqao** [comment]
I think I found and fixed the issue... The fix will be released in 0.9.7.

 As for the setters, the symptom of missing setters is missing fields in the `*Input` types.
E.g. `Student` would end up having 4 fields: `studentNumber`, `name`, `surname` and `subjects`, while `StudentInput` would have less, as it would miss the ones that don't have setters or `@JsonCreator` constructor arguments. Of course, it's all different if you're using Gson, or differently configured Jackson. So your milage may vary. Good to be aware of it, though.

**Comment by evader1337** [comment]
The field is not detected wrongly anymore, which is good. The problem now is, that type StudentInput doesn't even have the subjects field. I tried adding setters for subjects. By doing that, StudentInput had subjects input again, but then the Student type lost argument sort.

My getter and setter:
```
    @GraphQLQuery(name="subjects")
    public List<Subject> getSubjects(Sort sort) {
        return GraphQLUtils.sort(subjects, sort);
    }

    public void setSubjects(List<Subject> subjects) {
        this.subjects = subjects;
    }
```

**Comment by kaqqao** [comment]
We discussed this in the Gitter channel, but I'll briefly explain it here too for posterity.

Normally, only the input fields that the JSON library you use (Jackson or Gson) decides are deserializable get mapped. In your specific case, Jackson decides that the `subjects` field is not deserializable without either the setter or getter (the method you have isn't really a JavaBean getter), so it doesn't get mapped.

Gson normally considers all fields as writable, so using `GsonValueMapper` would lead to a different result.
