### ISSUE TITLE
Question regarding passing data from grand-parent node to child node

### ISSUE THREAD

**Issue by bidgal** [leangen/graphql-spqr#89]
My query is of the format

```graphql
person (id:'123' ) {
    phoneNumber (count: '1') {
        someOtherField {

       }
    }
}
```
In the resolver for `someOtherField` I want to access the person entity fetched in the root. Using the GraphQLEnvironment Context, I have access to `PhoneNumber` type but not `Person` type. Is there any way to fetch that?

**Comment by kaqqao** [comment]
This question pops up very often in graphql-java as well. In GraphQL in general (unrelated to SPQR), the resolvers only have access to the arguments, the parent and the shared context.
So if you can't design it in a way that doesn't require extra context (or that the needed context is contained in the parent), you're mostly stuck with piggy-backing the needed info on the shared context, which you can get access to via `@GraphQLRootContext` annotated argument.
Do pay attention that you're introducing state this way and have to take care about concurrency if your execution strategy is multi-threaded for example.

See e.g. [this answer](https://stackoverflow.com/questions/44159753/java-graphql-pass-field-values-to-resolver-for-objects/44179252#44179252) I've give on SO for some more details.
