### ISSUE TITLE
Upgrade to graphql-java v8.0

### ISSUE THREAD

**Issue by elenigen** [leangen/graphql-spqr#93]
When are you planning to bump the version of graphql-java to v8.0?

Many improvements and bug fixes are very interesting.

Thanks!

**Comment by kaqqao** [comment]
As soon as I get a chance. Directive support open up some very interesting possibilities. I'll start the work immediately after 0.9.7 release.

**Comment by kaqqao** [comment]
I was intending to release it today, but got tangled. I'll try to finish up tomorrow, but even in the worst case it will be out by weekend.
