### ISSUE TITLE
Errors element must not be present when empty

### ISSUE THREAD

**Issue by ricardomercado** [leangen/graphql-spqr#96]
Hello,
Not sure if this is a big ask, but according to the GraphQL spec, the `errors` element in the response should only be present if it contains error data.
This is not a big deal for most uses, but it can break some client libraries like Apollo, which adhere strictly to the spec.

**Comment by kaqqao** [comment]
Did you forget to call `ExecutionResult#toSpecification`? That produces a spec-compliant map that you're supposed to send to the client.

Either case, SPQR neither executes the query nor constructs the result - graphl-java does that - SPQR only generates the schema.

**Comment by kaqqao** [comment]
See [the sample](https://github.com/leangen/graphql-spqr-samples/blob/master/src/main/java/io/leangen/spqr/samples/demo/controller/GraphQLSampleController.java#L70) as well.
