### ISSUE TITLE
How to implement pagination?

### ISSUE THREAD

**Issue by gadieichhorn** [leangen/graphql-spqr#97]
Thanks for this great lib!

If I have a large data set (SQL/Ignite), what is the best approach to do pagination?
Can you provide some code examples?

Thanks

**Comment by kaqqao** [comment]
Do you mean pagination as specified by the [Relay's Connection spec](https://facebook.github.io/relay/docs/en/graphql-server-specification.html#connections)? [Here's](http://graphql.org/learn/pagination/) some reasoning behind it. Or just pagination in general?

If you're talking about the Relay spec, just make your method return `Page<Something>`. There's a helper class calles `PageFactory` that can create instances from common parameters, but you can also create your own. If you wish to add more fields, either to the `Connection` or the `Edge`, see the examples [here](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/RelayTest.java#L234) and [here](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/RelayTest.java#L245).

If you were talking about pagination in general... It's in no way different from any other query. Accept the arguments you need (e.g. `count` and `offset`, or `page` and `size`) and return a list.

**Comment by gadieichhorn** [comment]
Thanks for the detaild answer.

So the implementation is depending on the client lib I am using?
I was planning to use Angular (TypeScript) with appollo client. I dont think Realy is suitable here. I will explore what this client lib has for pagination

For some reason I thought the default GraphiQL UI defines some pagination standards and this will work if the backend service is compatible. :)

**Comment by kaqqao** [comment]
I don't think there's any expectation in GraphiQL itself. But you can fire any query, so whatever style you implement will be usable.

You don't need to be using Relay to go for their pagination style, it's just that Relay has that expectation and will use it internally. It's often regarded as best practice to use it anyway, although I find it too cumbersome for the common case of having a relational database in the backend.
In that case, I find the simple offset-based pagination much more convenient.

**Comment by gadieichhorn** [comment]
ok, thats great, thanks!
