### ISSUE TITLE
Multiple references in @GraphQLContext

### ISSUE THREAD

**Issue by paulkore** [leangen/graphql-spqr#99]
Hello,

Here's a simple use case of the ```@GraphQLContext``` annotation to add a ```description``` property to ```Widget``` type:

```graphql
query q1 {
    findAllWidgets() {
        description
    }
}
```
```java
@GraphQLQuery
public String description(@GraphQLContext Widget widget) {
     return "Widget " + widget.getId();
}
```
Suppose that another query looks like this:
```graphql
query q2 {
    findAllBoxes() {
        widgets {
            description
        }
    }
}
```
We'd like ```description``` to return a different value, depending on the context of the entire query. Is it possible to use ```@GraphQLContext``` with multiple type references, like so?
```java
@GraphQLQuery
public String description(@GraphQLContext Widget widget, @GraphQLContext Box box) {
     return "Widget " + widget.getId() + " inside box number " + box.getNumber();
}
```

**Comment by kaqqao** [comment]
Closing this as it's answered. Please reopen if you feel something is left unaddressed.
